---
title: ""
author: ""
date: ""
output: 
  pdf_document:
     keep_tex: yes
     includes:
      in_header: header.tex
---
<!-- ************************************************************************************************--> 
<!-- **********************************BEGIN APPENDICES**********************************************--> 
<!-- ************************************************************************************************--> 
\FloatBarrier
\newpage



<!-- ************************************DATA FITS************************************************--> 
#Appendix A. Detailed Fit to Length Composition Data 
<!--\renewcommand{\thepage}{A-\arabic{page}}
\setcounter{page}{1}-->


```{r, results='asis'}

plot.vec = c(1, 5:8, 12, 16, 20, 24, 28,32)

for (a in 1:length(plot.vec)){

  cat('\n![', LenComp_mod1[plot.vec[a],caption_col], ' \\label{fig:length_fits}](', LenComp_mod1[plot.vec[a], path_col], ')\n', sep='')
  
}

```

\FloatBarrier

#Appendix B. Detailed Fit to Age Composition Data 
<!--\renewcommand{\thepage}{B-\arabic{page}}
\setcounter{page}{1}-->

```{r, results='asis'}

plot.vec = c(1:2, 6, 10, 14, 18, 23)
name.vec = c("")

for (a in 1:length(plot.vec)){

  cat('\n![', AgeComp_mod1[plot.vec[a],caption_col], ' \\label{fig:age_fits}](', AgeComp_mod1[plot.vec[a], path_col], ')\n', sep='')
  
}

```

\FloatBarrier
\newpage

<!-- ************************************DATA FILE(S)************************************************--> 
<!--#Appendix C. SS data file {-}
\renewcommand{\thepage}{C-\arabic{page}}
\setcounter{page}{1}

```{r, echo=FALSE, eval=TRUE,results='markup', comment=NA}
mod1_data = writeLines(readLines('./SS/linebreak_files/2017pop.dat'))
```

\newpage -->

<!-- **********************************CONTROL FILE(S)***********************************************-->
<!--#Appendix D. SS control file{-}
\renewcommand{\thepage}{D-\arabic{page}}
\setcounter{page}{1}

```{r, echo=FALSE, eval=TRUE,results='markup', comment=NA}
mod1_control = writeLines(readLines('./SS/linebreak_files/2017pop.ctl'))
```

\newpage -->

<!-- *********************************STARTER FILE(S)*************************************************-->
<!--#Appendix E. SS starter file{-}
\renewcommand{\thepage}{E-\arabic{page}}
\setcounter{page}{1}

```{r, echo=FALSE, eval=TRUE,results='markup', comment=NA}
mod1_starter = writeLines(readLines('./SS/linebreak_files/starter.ss'))
```
\newpage -->

<!-- ********************************FORECAST FILE(S)**************************************************-->
<!--#Appendix F. SS forecast file{-}
\renewcommand{\thepage}{F-\arabic{page}}
\setcounter{page}{1}

```{r, echo=FALSE, eval=TRUE,results='markup', comment=NA}
mod1_forecast = writeLines(readLines('./SS/linebreak_files/forecast.ss'))
```
\newpage -->



<!--********************ADD ADDITIONAL APPENDICES AS NEEDED********************************************-->
<!--********************cHANGE APPENDIX TITLE AND THE APPENDIX LETTER**********************************-->
<!--#Appendix E. Appendix Title{-}
\label{sec:AppendixE}
\renewcommand{\thepage}{E-\arabic{page}}
\renewcommand{\thefigure}{E\arabic{figure}}
\renewcommand{\thetable}{E\arabic{table}}
\setcounter{page}{1}
\setcounter{figure}{0}
\setcounter{table}{0}

Add Appendix text, tables and figuers here. -->