<!-- ************DATA SECTION**************************************** -->
#Data
Data used in the `r spp` assessment are summarized in Figure \ref{fig:data_plot}. A description of each data source is provided below.

<!-- ********************************************************************** -->
<!-- ************FISHERY-INDEPENDENT DATA********************************** -->
<!-- ********************************************************************** -->

##Fishery-Independent Data

Research surveys have been used to provide fishery-independent information about the abundance, distribution, and biological characteristics of `r spp`.  A coast-wide survey was conducted in 1977 [@gunderson_distribution_1980] and repeated every three years through 2004 (referred to as the 'Triennial shelf survey'). The NMFS coordinated a cooperative research survey of the `r spp` stocks off Washington and Oregon with the Washington Department of Fish and Wildlife (WDFW) and the Oregon Department of Fish and Wildlife (ODFW) in March-May 1979 [@wilkins_condition_1983]. This survey was repeated in 1985 (referred to as the `r spp` survey). Two slope surveys have been conducted off the West Coast in recent years, one using the research vessel Miller Freeman, which ended in 2001 (referred to as the 'AFSC slope survey'), and another ongoing cooperative survey using commercial fishing vessels which began in 1998 as a DTS (Dover sole, thornyhead, and sablefish) survey and was expanded to other groundfish in 1999 (referred to as the 'NWFSC slope survey'). In 2003, this survey was expanded spatially to include the shelf. This last survey, conducted by the NWFSC, continues to cover depths from 30-700 fathoms (55-1280 meters) on an annual basis (referred to as the 'NWFSC shelf-slope survey').

Age estimates for `r spp` prior to the 1980s were made via surface ageing of otoliths, which misses the very tight annuli at the edge of the otolith once the fish reaches near maximum size. Ages are highly biased by age 14, and maximum age was estimated to be in the 20s, which lead to an overestimate of the natural mortality rate and the productivity of the stock. Using break and burn methods, `r spp` have been aged to over 100 years. Otoliths from fishery-independent and -dependent sources that were only surface age reads were excluded from this assessment due to the bias associated with these age reads.  The previous assessment also excluded the surface read otoliths. 

###Northwest Fisheries Science Center (NWFSC) Shelf-Slope Survey

The NWFSC shelf-slope survey is based on a random-grid design; covering the coastal waters from a depth of 55 m to 1,280 m [@bradburn_2003_2011]. This design uses four chartered industry vessels in most years, assigned to a roughly equal number of randomly selected grid cells. The survey, which has been conducted from late-May to early-October each year, is divided into two 2-vessel passes off the coast, which are executed from north to south. This design therefore incorporates both vessel-to-vessel differences in catchability as well as variance associated with selecting a relatively small number (approximately 700) of cells from a very large population of possible cells (greater than 11,000) distributed from the Mexican to the Canadian border. 

The data from the NWFSC shelf-slope survey was analyzed using a spatio-temporal delta-model [@thorson_geostatistical_2015], implemented as an R package, VAST [@thorson_comparing_2017], which is publicly available online (https://github.com/James-Thorson/VAST).  Spatial and spatio-temporal variation is specifically included in both encounter probability and positive catch rates, a logit-link for encounter probability and a log-link for positive catch rates.  Vessel-year effects were included for each unique combination of vessel and year in the data to account for the random selection of commercial vessels used during sampling [@helser_generalized_2004; @thorson_accounting_2014].  Spatial variation was approximated using 1,000 knots, and the model used the bias-correction algorithm [@thorson_implementing_2016] in Template Model Builder [@kristensen_tmb:_2016].  Further details regarding model structure are available in the user manual (https://github.com/James-Thorson/VAST/blob/master/examples/VAST_user_manual.pdf).  The stratification and modeling configuration are provided in Table \ref{tab:strata}.

The smallest `r spp` tend to occur in the shallower depths (< 200 m) with only larger individuals occurring at depths deeper than 300 m. Data collected by the NWFSC shelf-slope survey between depths of 55 - 549 m and north of $42^\circ$ and south of $49^\circ$ were used to generate an index of abundance from 2003-2016. The estimated index of abundance is shown in Table \ref{tab:Index_Summary}.  For contrast, the design based values are shown in Table \ref{tab:Design_Based}.  The lognormal distribution with random strata-year and vessel effects had the lowest AIC and was chosen as the final model.  The Q-Q plot does not show any departures from the assumed distribution (Figure \ref{fig:nw_qq}).  The indices for the NWFSC shelf-slope survey show a tentative decline in the population between 2003 and 2009, with an increasing trend in biomass between the 2009 and 2016 median point estimates.

Length compositions were expanded based upon the stratification and the age data was used as conditional age-at-length data.  The number of tows with length data ranged from 33 in 2006 to 69 in 2015 (Table \ref{tab:NWcombo_Lengths}), where ages were collected for `r spp` in nearly every tow length data were collected (Table \ref{tab:NWcombo_Ages}).  The expanded length frequencies from this survey show an increase in small fish starting in 2010 (Figure \ref{fig:nw_Length}).  The age frequencies provide clear evidence of large year-classes moving through the population from the 1999, 2000, and 2008 recruitments; with early indications of a large 2013 recruitment (Figure \ref{fig:nw_Age}).

The input sample sizes for length and marginal age-composition data for all fishery-independent surveys were calculated according to Stewart and Hamel [-@stewart_bootstrapping_2014], which determined that the approximate realized sample size for shelf/slope rockfish species was $2.43*N_{\text{tow}}$.  The effective sample size of conditional-age-at-length data was set at the number of fish at each length by sex and by year. The conditional-age-at-length data were not expanded and were binned by according to length, age, sex, and year.

Fish with ages also have an associated length and each type of data have been used in the model. Age data from the NWFSC shelf-slope survey were used as conditional-age-at-length data within the model, which avoids double of the length and age data by explicitly stating the length associated with each aged fish.  Hence, the length and conditional-age-at-length data from the NWFSC shelf-slope survey were given full weight in likelihood calculations when model fitting. 

###Northwest Fisheries Science Center (NWFSC) Slope Survey  

The NWFSC slope survey covered waters throughout the summer from 183 m to 1,280 m north of $34^\circ 30^\prime$ S, which is near Point Conception, from 1999 and 2002.  Tows conducted between the depths of 183 and 549 m were used to create an index of abundance using a bayesian delta-GLMM model. The VAST delta-GLMM model was also explored but due to poor diagnostics this modeling approach was not used to create the final index.  The estimated index of abundance is shown in Table \ref{tab:Index_Summary}.  The stratification and modeling configuration are provided in Table \ref{tab:strata}.  Based on the diagnostics of the bayesian delta-GLMM, which does not account for spatial effects, a gamma distribution allowing for additional probability of extreme catch events with year-vessel random effects was selected as the final model.  The Q-Q plot does show a minimal departure from the assumed distribution (Figure \ref{fig:nw_slope_qq}), but was determined to be acceptable based on the alternative model distributions.  The trend of abundance across the four surveys years was generally flat with high estimated annual variance.  Sensitivities (not shown) were done evaluating the excluding of this index within the base model or using the VAST estimated index and neither approach was found to be influential on the model estimates.  

Length and age compositions were available for 2001 and 2002 and were expanded based upon the survey stratification (Tables \ref{tab:NWslope_Lengths} and \ref{tab:NWslope_Ages}).  The expanded length frequencies from this survey shows that primarily only large fish were captured both years (Figure \ref{fig:nw_slope_Length}).  The majority of fish observed by this survey were aged at greater than 10 years (Figure \ref{fig:nw_slope_Age}).

The input sample sizes for length and marginal age-composition data were calculated according to Stewart and Hamel [-@stewart_bootstrapping_2014] described in Section \ref{northwest-fisheries-science-center-nwfsc-shelf-slope-survey}. 

Fish with ages also have an associated length and each type of data have been used in the model. To avoid double use of the length and age data from individual fish, the length and age data sources were each given 0.50 weight in the likelihood calculations when model fitting.


###Alaska Fisheries Science Center (AFSC) Slope Survey 

The AFSC slope survey operated during autumn (October-November) aboard the R/V Miller Freeman. Partial survey coverage of the US west coast occurred during 1988-96 and complete coverage (north of $34^\circ 30^\prime$ S) during 1997, 1999, 2000, and 2001. Only the four years of consistent and complete surveys (1997, 1999, 2000, and 2001) plus 1996, which surveyed north of $43^\circ$ N latitude to the US-Canada border, were used in this assessment.  These same data years were used in the last assessment. The number of tows with length data ranged from 19 in 2000 to 48 in 1996 (Table \ref{tab:AFSC_Lengths}).  Because a large number of positive tows occurred in 1996, it was decided to include that year, which surveyed from $43^\circ$ N latitude to the US-Canada border. Therefore, only tows from $43^\circ$ N latitude to the US-Canada border were used across all years to create and index of abundance.  

An index of abundance was estimated based on the data using the VAST delta-GLMM model.  The estimated index of abundance is shown in Table \ref{tab:Index_Summary}.  The stratification and modeling configuration are provided in Table \ref{tab:strata}.  The lognormal distribution with random strata-year had the lowest AIC and was chosen as the final model.  The Q-Q plot does not show any departures from the assumed distribution (Figure \ref{fig:afsc_qq}).  The trend in the indices was generally flat over time.

Length compositions were available for each year the survey was conducted.  No age data were available from this survey.  The expanded length frequencies from this survey were generally of larger fish ( > 30 cm), except for 1997 where the highest frequency of fish were between 20 and 30 cm for both females and males (Figure \ref{fig:afsc_Length}). 

The input sample sizes for length and marginal age composition data were calculated according to Stewart and Hamel [-@stewart_bootstrapping_2014] described above in Section \ref{northwest-fisheries-science-center-nwfsc-shelf-slope-survey}. 


###Pacific Ocean Perch Survey

A survey designed to sample `r spp` was conducted in 1979 and again in 1985 (for a detailed description see Ianelli et al. [-@ianelli_status_1992]).  An index of abundance was estimated based on the data using the VAST delta-GLMM model.  The estimated index of abundance is shown in Table \ref{tab:Index_Summary}.  The stratification and modeling configuration are provided in Table \ref{tab:strata}.  The lognormal distribution with random strata-year had the lowest AIC and was chosen as the final model.  The Q-Q plot does not show any departures from the assumed distribution (Figure \ref{fig:pop_qq}).  The index shows a clear decline in abundance between the two survey years. 

Length and age compositions were expanded based on the survey stratification. The survey had 125 and 126 `r spp` tows (Table \ref{tab:POP_Lengths}) and break-and-burn ages were available for 1985 (Table \ref{tab:POP_Ages}). Only surface reads, considered to be biased, were available for the 1979 data. The length frequencies for both years are highest between the 30-45 cm range (Figure \ref{fig:POP_Length}) with ages in 1985 having a large number of fish age 40 and greater (Figure \ref{fig:POP_Age}).

The input sample sizes for length and marginal age-composition data were calculated according to Stewart and Hamel [-@stewart_bootstrapping_2014] described above in Section \ref{northwest-fisheries-science-center-nwfsc-shelf-slope-survey}. To avoid double use of the length and age data from individual fish, the length and age data sources were each given 0.50 weight in the likelihood calculations when model fitting.

###Fishery Independent Data Not Included in the Base Model

The follow datasets were evaluated but not included in the base model.

####Triennial Shelf Survey
The Triennial shelf survey was first conducted by the AFSC in 1977 and spanned the time-frame from 1977-2004. The survey's design and sampling methods are most recently described in Weinberg et al. [-@weinberg_estimation_2002]. Its basic design was a series of equally-spaced transects from which searches for tows in a specific depth range were initiated. The survey design has changed slightly over the period of time. In general, all of the surveys were conducted in the mid-summer through early fall: the 1977 survey was conducted from early July through late September; the surveys from 1980 through 1989 ran from mid-July to late September; the 1992 survey spanned from mid-July through early October; the 1995 survey was conducted from early June to late August; the 1998 survey ran from early June through early August; and the 2001 and 2004 surveys were conducted in May-July.

Haul depths ranged from 91-457 m during the 1977 survey with no hauls shallower than 91 m. The surveys in 1980, 1983, and 1986 covered the West Coast south to $36.8^\circ$ N latitude and a depth range of 55-366 m. The surveys in 1989 and 1992 covered the same depth range but extended the southern range to $34.5^\circ$ N (near Point Conception). From 1995 through 2004, the surveys covered the depth range 55-500 m and surveyed south to $34.5^\circ$ N. In the final year of the Triennial series, 2004, the NWFSC's Fishery Resource and Monitoring division (FRAM) conducted the survey and followed very similar protocols as the AFSC.

Although the Triennial shelf survey was used in the 2011 assessment, it was not used in the final base model for the current assessment for a number of reasons.  First, there were concerns regarding the varying sampling and targeting of specific species by year across the time-series.  Secondly, the Triennial shelf survey targeted the shelf of the West Coast and would not be expected to sample well slope species such as `r spp`.  There were limited observations of `r spp` relative to other surveys (e.g. NWFSC shelf-slope survey) and the length and age distributions varied in such a manner that would indicate either poor sampling of `r spp` or inconsistent sampling of the population.  

Information regarding the Triennial shelf survey index of abundance and the number of samples available and plots of the composition data are available in Appendix C, section \ref{appendix-c.-description-of-cpue-and-triennial-data}.

#### Washington Research Lengths
Research length and ages were provided by WDFW.  However, the information regarding the nature of the research cruise and collection methods have been lost to time.  The data set includes lengths and ages that were collected between 1967-1972 and in 1979.  The distribution of lengths across years collected were consistent with primarily only larger `r spp`, 35-40 cm, being selected.  All age data were based upon surface reads which unfortunately are highly biased at relatively young ages for `r spp`.  Due to the lack of information regarding the collection of these data, they were not selected to be a part of the base model but a sensitivity was conducted which evaluated the impact of these data.

<!-- ********************************************************************** -->
<!-- ************FISHERY-DEPENDENT DATA************************************ -->
<!-- ********************************************************************** -->
##Fishery-Dependent Data

###Commercial Fishery Landings

**Washington**

Historical commercial fishery landings of `r spp` in Washington for the years 1908-2016 were obtained from Theresa Tsou (WDFW) and Phillip Weyland (WDFW).  This assessment is the first `r spp` assessment to include a historical catch reconstruction provided by Washington state and, hence, the historical catches for Washington differ from those used in the 2011 assessment.  WDFW also provided catches for the 1981-2016 period to include re-distribution of the "URCK" landings in the PacFIN database.  These data are currently not available from PacFIN. 

**Oregon**

Historical commercial fishery landings of `r spp` in Oregon for the years 1892-1986 were obtained from Alison Whitman (ODFW). A description of the methods can be found in Karnowski et al. [-@karnowski_historical_2014]. Recent landings (1987-2016) were obtained from PacFIN (retrieval dated May 2, 2017, Pacific States Marine Fisheries Commission, Portland, Oregon; www.psmfc.org).  The catch data from the POP and POP2 categories contained within PacFIN for `r spp` were used for this assessment.  Additional catches from 1987-1999 for `r spp` under the URCK category not yet available in PacFIN were received directly from the state and combined with the landings data available for that period within PacFIN (Patrick Mirrick, personal communication, ODFW).

**California**

Historical commercial fishery landings of `r spp` were obtained directly from John Field at the SWFSC due to database issues for the historical period for the  California Cooperative Groundfish Survey data system, also known as CALCOM Database (128.114.3.187) for the years 1916-1980. The catches received included revisions in the catch history from 1948-1960 based on fish that were caught north of the California-Oregon border and landed in northern California which were not included in the original reconstruction.  A description of the historical reconstruction methods can be found in Ralston et al. [-@ralston_documentation_2010]. Recent landings  (1981-2016) were obtained from PacFIN (retrieval dated May 2, 2017, Pacific States Marine Fisheries Commission, Portland, Oregon; www.psmfc.org).

**At-Sea Hake Fishery**

Catches of `r spp` are monitored aboard the vessel by observers in the at-sea hake Observer program (ASHOP) and were available for the years of 1975-2016. Observers use a spatial sample design, based on weight, to randomly choose a portion of the haul to sample for species composition. For the last decade, this is typically 30-50% of the total weight. The total weight of the sample is determined by all catch passing over a flow scale. All species other than hake are removed and weighed by species on a motion compensated flatbed scale. Observers record the weights of all non-hake species. Non-hake species total weights are expanded in the database by using the proportion of the haul sampled to the total weight of the haul. The catches of non-hake species in unsampled hauls is determined using bycatch rates determined from sampled hauls. Since 2001, more than 97% of the hauls have been observed and sampled. 

**Foreign Catches**

From the 1960s through the early 1970s, foreign trawling enterprises harvested considerable amounts of rockfish off Washington and Oregon, and along with the domestic trawling fleet, landed large quantities of `r spp`. Foreign catches of individual species were estimated by @rogers_species_2003 and attributed to INPFC areas for the years of 1966-1976 for `r spp`. The foreign catches were combined across areas for a coastwide removal total.

###Discards

Data on discards of `r spp` are available from two different data sources.  The earliest source is referred to as the Pikitch data and comes from a study organized by Ellen Pikitch that collected trawl discards from 1985-1987 [@pikitch_evaluation_1988].  The northern and southern boundaries of the study were $48^\circ 42^\prime$ N latitude and $42^\circ 60^\prime$ N latitude respectively, which is primarily within the Columbia INPFC area [@pikitch_evaluation_1988; @rogers_numerical_1992].  Participation in the study was voluntary and included vessels using bottom, midwater, and shrimp trawl gears.  Observers of normal fishing operations on commercial vessels collected the data, estimated the total weight of the catch by tow, and recorded the weight of species retained and discarded in the sample.  Results of the Pikitch data were obtained from John Wallace (personal communication, NWFSC, NOAA) in the form of ratios of discard weight to retained weight of `r spp` and sex-specific length frequencies.  Discard estimates are shown in Table \ref{tab:Discard}.   

The second source is from the West Coast Groundfish Observer Program (WCGOP).  This program is part of the NWFSC and has been recording discard observations since 2003. Table \ref{tab:Discard} shows the discard ratios (discarded/(discarded + retained)) of `r spp` from WCGOP.  Since 2011, when the trawl rationalization program was implemented, observer coverage rates increased to nearly 100% for all the limited entry trawl vessels in the program and discard rates declined compared to pre-2011 rates.  Discard rates were obtained for both the catch-share and the non-catch share sector for `r spp`.  A single discard rate was calculated by weighting discard rates based on the commercial landings by each sector.  Coefficient of variations were calculated for the non-catch shares sector and pre-catch share years by bootstrapping vessels within ports because the observer program randomly chooses vessels within ports to be observed. Post-ITQ, all catch-share vessels have 100% observer coverage and discarding is assumed to be known.  Discard length composition for the trawl fleet varied by year, with larger fish being discarded prior to 2011 (Figure \ref{fig:WCGOP_discard}).
 

###Fishery Length and Age Data

####Commercial Fishery
Biological data from commercial fisheries that caught `r spp` were extracted from PacFIN on May 4, 2017.  Lengths taken during port sampling in Oregon and Washington were used to calculate length and age compositions.  There were no biological data from California for `r spp` available within PacFIN or CALCOM databases.  The overwhelming majority of these data were collected from the mid-water and bottom trawl gear, but additional biological data were collected from non-trawl gear which was grouped together with trawl gear data. Tables \ref{tab:Comm_Lengths} and \ref{tab:Comm_Ages} show the number of trips and fish sampled, along with the calculated sample sizes.  Length and age data were acquired at the trip level and then aggregated to the state level.  The input sample sizes were calculated via the Stewart method (Ian Stewart, personal communication, IPHC):

\begin{centering}

Input effN = $N_{\text{trips}} + 0.138 * N_{\text{fish}}$ if $N_{\text{fish}}/N_{\text{trips}}$ is $<$ 44

Input effN = $7.06 * N_{\text{trips}}$ if $N_{\text{fish}}/N_{\text{trips}}$ is $\geq$ 44

\end{centering}

The fishery fleet observed `r spp` that were generally greater than 30 cm across all years of available data (Figure \ref{fig:Comm_Length}). The fishery fleet age data has clear patterns showing two large cohorts moving through the population near the end of the time-series (Figure \ref{fig:Comm_Age}). Lengths and ages were also available for the at-sea hake fishery and are shown in Figures \ref{fig:ASHOP_Length} and \ref{fig:ASHOP_Age}. 

To avoid double use of the length and age data from individual fish, the length and age data sources were each given 0.50 weight in the likelihood calculations when model fitting.  

####At-Sea Hake Fishery
Available biological data from the at-sea hake fishery were included in the assessment.  Length data were available from 2003-2016 (Table \ref{tab:ASHOP_Lengths}) with annual sample sizes ranging from a low of 63 in 2009 to a high of 470 in 2007.  Age data were available from 2003, 2006, 2007, and 2014 (Table \ref{tab:ASHOP_Ages}). Sample sizes were calculated based on the equation described above in Section \ref{commercial-fishery}. To avoid double use of the length and age data from individual fish, the length and age data sources were each given 0.50 weight in the likelihood calculations when model fitting.  

###Fishery Data Not Included in the Base Model
Several datasets available from the fishery were explored but not used in the final assessment.

####Historical Commercial Catch-Per-Unit Effort

Data on catch-per-unit-effort (CPUE) in mt/hr from the domestic fishery were combined for the INPFC Vancouver and Columbia areas from Gunderson [-@gunderson_population_1977].  Although these data reflect catch rates for the US fleet, the highest catch rates coincided with the beginning of removals by the foreign fleet.  This suggests that, barring unaccounted changes in fishing efficiency during this period, the level of abundance was high at that time.  Unfortunately, the original data and the analysis methods used to create this CPUE series have been lost to time precluding a re-analysis of these data.  Due to the inability to examine the assumptions made during the original analysis or the data used this time-series has been excluded from the base model.  These data were included in the previous assessment but were deemed not influential in the model estimates.  Information regarding the fishery CPUE are available in Appendix C, section  \ref{appendix-c.-description-of-cpue-and-triennial-data}.

####Oregon Special Projects Length and Age Data
Oregon special project data were provided by ODFW.  These data represent samples made at either the dock or at processing plants from fishery landings.  Length data were collected primarily from 1970-1986, with limited samples from more recent years.  Age data were primarily available from 1981-1984.  These data were collected for special projects and may not have been sampled randomly from the fishery landings.  Due to these concerns, these data were not included in the base model but were included in a model sensitivity.  This was the first time these data were explored for consideration in the assessment.



<!--************BIOLOGICAL DATA*********************************************-->
##Biological Data

###Natural Mortality

Historical `r spp` ages determined using scales and surface reading methods of otoliths resulted in estimates of natural mortality ($M$) between 0.10 and 0.20 yr^-1^ with a longevity less than 30 years [@gunderson_population_1977].  Based on the break-and-burn method of age determination using otoliths, the maximum age of `r spp` was revised to be 90 years [@chilton_age_1982]. The updated understanding concerning `r spp` longevity reduced the estimate of natural mortality based on Hoenig's [-@hoenig_empirical_1983] relationship to 0.059 yr^-1^. The previous assessment applied a prior distribution on natural mortality based upon multiple life-history correlates (including Hoenig's method, Gunderson [-@gunderson_trade-off_1997] gonadosomatic index, and McCoy and Gillooly's [-@mccoy_predicting_2008] theoretical relationship) developed separately for female and male `r spp`.  

Hamel [-@hamel_method_2015] developed a method for combining meta-analytic approaches relating the $M$ rate to other life-history parameters such as longevity, size, growth rate, and reproductive effort to provide a prior on $M$. In that same issue of *ICES Journal of Marine Science*, Then et al. [-@then_evaluating_2015] provided an updated data set of estimates of $M$ and related life history parameters across a large number of fish species from which to develop an $M$ estimator for fish species in general. They concluded by recommending $M$ estimates be based on maximum age alone, based on an updated Hoenig non-linear least squares estimator $M=4.899A^{-0.916}_{max}$. The approach of basing $M$ priors on maximum age alone was one that was already being used for West Coast rockfish assessments. However, in fitting the alternative model forms relating $M$ to $A_{\text{max}}$, Then et al. [-@then_evaluating_2015] did not consistently apply their transformation. In particular, in real space, one would expect substantial heteroscedasticity in both the observation and process error associated with the observed relationship of $M$ to $A_{\text{max}}$. Therefore, it would be reasonable to fit all models under a log transformation. This was not done. Re-evaluating the data used in Then et al. [-@then_evaluating_2015] by fitting the one-parameter $A_{\text{max}}$ model under a log-log transformation (such that the slope is forced to be -1 in the transformed space [@hamel_method_2015]), the point estimate for $M$ is:

\begin{centering}

$M=\frac{5.4}{A_{\text{max}}}$

\end{centering}

The above is also the median of the prior. The prior is defined as a lognormal distribution with mean $ln(5.4/A_{\text{max}})$ and SE = 0.438. Using a maximum age of 100, the point estimate and median of the prior is 0.054 yr^-1^.  The maximum age was selected based on available age data from all West Coast data sources.  The oldest aged rockfish was 120 years, captured by the commercial fishery in 2007.  However, age data are subject to ageing error which could impact this estimate of longevity.  The selection of 100 years was based on the range of other ages available with multiple observations of fish between 90 and 102 years of age.      


###Sex Ratio, Maturation, and Fecundity

Examining all biological data sources, the sex ratio of young fish are within 5% of 1:1 by length until larger sizes which are dominated by females who reach a larger maximum size relative to males (Figure \ref{fig:sexratio}), with the sex ratio being approximately equal across ages (Figure \ref{fig:sexratio_Age}), and hence this assessment assumed the sex ratio at birth was 1:1. This assessment assumed a logistic maturity-at-length curve based on analysis of 537 fish maturity samples collected from the NWFSC shelf-slope survey.  This is revised from the previous assessment that assumed maturity-at-age based on the work of Hannah and Parker [-@hannah_age-modulated_2007].  Additionally, the new maturity-at-length curve is based on the estimate of functional maturity, an approach that classifies rockfish maturity with developing oocytes as mature or immature based on the proportion of vitellogenin in the cytoplasm and the measured frequency of atretic cells (Melissa Head, personal communication, NWFSC, NOAA).  The 50% size-at-maturity was estimated at 32.1 cm with maturity asymptoting to 1.0 for larger fish (Figure \ref{fig:mat}).  Comparison between the maturity-at-age used in the previous assessment and the updated functional maturity-at-length is shown in Figure \ref{fig:mat_compare} showing that the new maturity curve has fish reaching 50% maturity at older ages relative to the maturity-at-age used in the 2011 assessment.

The fecundity-at-length has also been updated from the previous assessment based on new research.  Dick et al. [-@dick_meta-analysis_2017] estimated new fecundity relationships for select West Coast stocks where fecundity for `r spp` was estimated equal to `r format(mod1$MGparmAdj$Eggs_scalar_Fem[1], scientific = TRUE)`$L$^`r round(mod1$MGparmAdj$Eggs_exp_len_Fem[1],2)`^ in millions of eggs where $L$ is length in cm. Fecundity-at-length is shown in Figure \ref{fig:fecundity}.


###Length-Weight Relationship

The length-weight relationship for `r spp` was estimated outside the model using all biological data available from fishery-dependent and -independent data sources, where the female weight-at-length in grams was estimated at `r format(mod1$MGparmAdj$Wtlen_1_Fem[1], scientific = TRUE)`$L$^`r round(mod1$MGparmAdj$Wtlen_2_Fem[1],2)`^ and males at `r format(mod1$MGparmAdj$Wtlen_1_Mal[1], scientific = TRUE)`$L$^`r round(mod1$MGparmAdj$Wtlen_2_Mal[1], 2)`^ where $L$ is length in cm (Figures \ref{fig:Wt_len} and \ref{fig:Wt_len_pred}).


###Growth (Length-at-Age)

The length-at-age was estimated for male and female `r spp` using data collected from both fishery-dependent and -independent data sources that were collected from 1981-2016. Figure \ref{fig:Len_Age} shows the lengths and ages for all years and all data as well as predicted von Bertalanffy fits to the data. Females grow larger than males and sex-specific growth parameters were estimated at the following values:

\begin{centering}

Females $L_{\infty}$ = 42.32; $k$ = 0.169; $t_0$ = -1.466

Males $L_{\infty}$ = 39.03; $k$ = 0.212; $t_0$ = -1.02

\end{centering}

These values were used as starting parameter values within the base model prior to estimating each parameter for male and female `r spp`.


###Ageing Precision and Bias

Uncertainty surrounding the age-reading error process for `r spp` was incorporated by estimating ageing error by age. Age-composition data used in the model were from break-and-burn otolith reads aged by the Cooperative Ageing Project (CAP) in Newport, Oregon. Break-and-burn double reads of more than 1500 otoliths were provided by the CAP lab.  An ageing-error estimate was made based on these double reads using a computational tool specifically developed for estimating ageing error [@punt_quantifying_2008] and using release 1.0.0 of the R package nwfscAgeingError [@thorson_nwfscageingerror:_2012] for input and output diagnostics, publicly available at: https://github.com/nwfsc-assess/nwfscAgeingError. A non-linear standard error was estimated by age, where there is more variability in the age of older fish (Table \ref{tab:Age_Error} and Figure \ref{fig:Age_Error}).  The 2011 assessment assumed a linear ageing error vector and is shown in Figure \ref{fig:Age_Error} for comparison with the updated ageing error applied in the current assessment.  


<!-- ********************************************************************** -->
<!-- ***********HISTORY AND CURRENT ASSESSMENT***************************** -->
<!-- ********************************************************************** -->
##History of Modeling Approaches Used for This Stock

###Previous Assessments
The status of `r spp` off British Columbia, Washington, and Oregon have been periodically assessed since the intensive exploitation that occurred in the 1960s.  Concerns regarding `r spp` status off the coast the US west coast were raised in the late 1970s [@gunderson_results_1978; @gunderson_updated_1981] and in 1981 the PFMC adopted a 20-year plan to rebuild the stock. 

The 1992 assessment determined that `r spp` remained at low levels relative to the population size in 1960 [@ianelli_status_1992] and recommended additional harvest restrictions to allow for stock rebuilding.  The 1998 assessment [@ianelli_status_1998] estimated that the stock was 13% of the unfished level, leading the National Marine Fishery Service (NMFS) to declare the stock overfished in 1999.  A formal rebuilding plan was implemented in 2001.  The rebuilding plan reduced the SPR harvest rate used to determine catches to 0.864 (in contrast to the default harvest rate of 0.50).  The last full assessment of `r spp` was conducted in 2011 [@hamel_stock_2011], which concluded that the stock was still well below the target biomass of $40\%SB_{0}$, estimating the relative stock status at 19.1%. 



