\documentclass[12pt,]{article}
%\usepackage{lmodern}  Melissa removed to deal with font rendering issue
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript

%Melissa removed the following section to deal with font rendering issue
%\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
%  \usepackage[T1]{fontenc}
%  \usepackage[utf8]{inputenc}
%%\else % if luatex or xelatex
%  \ifxetex
%    \usepackage{mathspec}
%  \else
%    \usepackage{fontspec}
%  \fi
%  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
%  \newcommand{\euro}{€}
%%%%%%\fi

% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\PassOptionsToPackage{usenames,dvipsnames}{color} % color is loaded by hyperref
\hypersetup{unicode=true,
            pdftitle={Status of Pacific ocean perch (Sebastes alutus) along the U.S. west coast in 2017},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}
  \title{Status of Pacific ocean perch (\emph{Sebastes alutus}) along the U.S.
west coast in 2017}
  \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
  \author{}
  \preauthor{}\postauthor{}
  \date{}
  \predate{}\postdate{}


% This file contains all of the LaTeX packages you may need to compile the document
% Documentation for each package can be found onlines
\usepackage{tabularx}                                             % table environment providing flexibility
\usepackage{caption}                                              % for creating captions  
\usepackage{longtable}                                            % allows tables to span multiple pages
\usepackage{rotating}                                             % allows for sideways tables
\usepackage{float}                                                % floating environments; may not need in rmarkdown
\usepackage{placeins}                                             % keeps floats from moving
\usepackage{indentfirst}                                          % indents first paragraph of a section
\usepackage{mdwtab}                                               % continued float multi-page figure
\usepackage{enumerate}                                            % create lists
\usepackage{hyperref}                                             % highlight cross references
\hypersetup{colorlinks=true, urlcolor=blue, linktoc=page, linkcolor=blue, citecolor=blue} %define referencing colors
%\usepackage{makebox}                                             % make boxes around text
\usepackage[usenames,dvipsnames]{xcolor}                          % color name options
%\usepackage[space]{grffile}                                      % spaces in file name path
\usepackage{soul}                                                 % highlight text
\usepackage{enumitem}                                             % numbered lists
\usepackage{lineno}                                               % Line numbers; comment out for final
\usepackage{upquote}                                              % produce grave accent in latex
\usepackage{verbatim}                                             % produces verbatim results
\usepackage{fancyvrb}                                             % verbatim in a box
%\usepackage{draftwatermark}                                      % places Draft watermark in background; comment out for final
\usepackage{textcomp}                                             % fixes error with packages interfering
\usepackage{lscape}                                               % rotate pages - to allow for landscape longtables
%\pdfinterwordspaceon                                             % fix loss of inter word spacing
\usepackage{cmap}                                                 % fix mapping characters to unicode
\RequirePackage[linewidth = 1]{pdfcomment}                        % pdf comments
\RequirePackage[l2tabu, orthodox]{nag}                            % checks packages related to the accessibility?
\usepackage[inline]{showlabels}                                   % show table and figure labels; comment out for final
%\RequirePackage[tagged]{accessibilityMeta}


\linenumbers                                                      % specify use of line numbers


\definecolor{light-gray}{gray}{.85}                               % define light-gray as a color
%\usepackage[tagged]{accessibility-meta}

 
%\showlabels[\color{mred}]{label}

% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

\begin{document}
\maketitle


\begin{center}
\thispagestyle{empty}


\vspace{.5cm}

\includegraphics{Sebastes_alutus}~\\[0.5cm]
%\pdftooltip{\includegraphics{Sebastes_alutus}}{This is a fish.}



Chantel R. Wetzel\textsuperscript{1}\\
Kelli Johnson\textsuperscript{2}\\
Lee Cronin-Fine\textsuperscript{3}\\

\vspace{.5cm}

\small
\textsuperscript{1}Northwest Fisheries Science Center, U.S. Department of Commerce, National Oceanic and Atmospheric Administration, National Marine Fisheries Service, 2725 Montlake Boulevard East, Seattle, Washington 98112\\

\vspace{.3cm}

\textsuperscript{2}Northwest Fisheries Science Center, U.S. Department of Commerce, National Oceanic and Atmospheric Administration, National Marine Fisheries Service, 2725 Montlake Boulevard East, Seattle, Washington 98112\\

\vspace{.3cm}

\textsuperscript{3}University of Washington, School of Aquatic and Fishery Sciences\\

\vspace{.3cm}

%\textsuperscript{4}Oregon Department of Fish and Wildlife, 2040 SE Marine Science Drive, Newport, OR 97365\\


\vspace{.5cm}

\vfill
DRAFT SAFE\\
Disclaimer: This information is distributed solely for the purpose of pre-dissemination
peer review under applicable information quality guidelines. It has not been formally
disseminated by NOAA Fisheries. It does not represent and should not be construed to
represent any agency determination or policy. 

\vspace{.3cm}
%Bottom of the page
%{\large \today}

\maketitle

\pagenumbering{roman}
\setcounter{page}{1}
\end{center}

{
\setcounter{tocdepth}{4}
\tableofcontents
}
\setlength{\parskip}{5mm plus1mm minus1mm} \pagebreak

\pagenumbering{arabic} \setcounter{page}{1}
\renewcommand{\thefigure}{\alph{figure}}
\renewcommand{\thetable}{\alph{table}}

\section*{Executive Summary}\label{executive-summary}
\addcontentsline{toc}{section}{Executive Summary}

\subsection*{Stock}\label{stock}
\addcontentsline{toc}{subsection}{Stock}

\hl{Include: species/area, including an evaluation of any potential biological basis 
for regional management.}

This assessment reports the status of the Pacific ocean perch
(\emph{Sebastes alutus}) resource in U.S. waters off the coast of the
California, Oregon, and Washington using data through 2011. Etc\ldots{}

\subsection*{Catches}\label{catches}
\addcontentsline{toc}{subsection}{Catches}

\hl{Include: trends and current levels-include table for last ten years and graph with 
long term data}

Catch figure(s) with fleets: (Figures
\ref{fig:Exec_catch1}-\ref{fig:Exec_catch3})\\
Catch table: (Table \ref{tab:Exec_catch})

\FloatBarrier

\begin{figure}
\centering
\includegraphics{Assessment_template_files/figure-latex/unnamed-chunk-2-1.pdf}
\caption{Pacific ocean perch landings in \ldots{}..
\label{fig:Exec_catch1}}
\end{figure}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/catch2 landings stacked.png}
\caption{Landings history of Pacific ocean perch in the Base model.
\label{fig:r4ss_catches}}
\end{figure}

\begin{table}[ht]
\centering
\caption{Recent Pacific ocean perch landings (mt) by 
                                            fleet.} 
\label{tab:Exec_catch}
\begin{tabular}{l>{\centering}p{0.7in}>{\centering}p{0.7in}>{\centering}p{0.7in}>{\centering}p{0.7in}>{\centering}p{0.7in}>{\centering}p{0.7in}>{\centering}p{0.7in}}
  \hline
Year & Washington & Oregon & California & At-sea-hake & Survey & Total Catch & Total Dead \\ 
  \hline
2001 &  20 &  20 &  20 &  20 &  20 & 264 & 264 \\ 
  2002 &  20 &  20 &  20 &  20 &  20 & 150 & 150 \\ 
  2003 &  20 &  20 &  20 &  20 &  20 & 134 & 134 \\ 
  2004 &  20 &  20 &  20 &  20 &  20 & 122 & 122 \\ 
  2005 &  20 &  20 &  20 &  20 &  20 &  64 &  64 \\ 
  2006 &  20 &  20 &  20 &  20 &  20 &  72 &  72 \\ 
  2007 &  20 &  20 &  20 &  20 &  20 & 132 & 132 \\ 
  2008 &  20 &  20 &  20 &  20 &  20 &  86 &  86 \\ 
  2009 &  20 &  20 &  20 &  20 &  20 &  95 &  95 \\ 
  2010 &  20 &  20 &  20 &  20 &  20 &  91 &  91 \\ 
   \hline
\end{tabular}
\end{table}

\FloatBarrier

\newpage

\subsection*{Data and Assessment}\label{data-and-assessment}
\addcontentsline{toc}{subsection}{Data and Assessment}

\hl{Include: date of last assessment, type of assessment model, data available, new 
information, and information lacking.}

Pacific ocean perch was assessed\ldots{}. This assessment uses the
newest version of Stock Synthesis (3.30). The model begins in 1940, and
assumes the stock was at an unfished equilibrium that year.

\FloatBarrier

\subsection*{Stock Biomass}\label{stock-biomass}
\addcontentsline{toc}{subsection}{Stock Biomass}

\hl{Include: trends and current levels relative to virgin or historic levels, 
description of uncertainty-include table for last 10 years and graph with 
long term estimates.}

Spawning output Figure: Figure \ref{fig:Spawnbio_all}\\
Spawning output Table(s): Table \ref{tab:SpawningDeplete_mod1}\\
Relative depletion Figure: Figure \ref{fig:RelDeplete_all}

Example text (remove Models 2 and 3 if not needed - if using, remove the
\# in-line comments!!!)\\
The estimated relative depletion level (spawning output relative to
unfished spawning output) of the the base-case model in 2011 is 19.5\%
(\textasciitilde{}95\% asymptotic interval: \(\pm\) 12.9\%-26\%) (Figure
\ref{fig:RelDeplete_all}).

The estimated relative depletion level of model 2 in 2011 is
(\textasciitilde{}95\% asymptotic interval: \(\pm\) ) (Figure
\ref{fig:RelDeplete_all}).

The estimated relative depletion level of model 3 in 2011 is
(\textasciitilde{}95\% asymptotic interval: \(\pm\) ) (Figure
\ref{fig:RelDeplete_all}).

\FloatBarrier

\begin{table}[ht]
\centering
\caption{Recent trend in beginning of the 
                                      year spawning output and depletion for
                                      the Base model for Pacific ocean perch.} 
\label{tab:SpawningDeplete_mod1}
\begin{tabular}{l>{\centering}p{1.3in}>{\centering}p{1.2in}>{\centering}p{1in}>{\centering}p{1.2in}}
  \hline
Year & Spawning Output (billion eggs) & \~{} 95\% confidence interval & Estimated depletion & \~{} 95\% confidence interval \\ 
  \hline
2002 & 9812.00 & 5399 - 14225 & 0.15 & 0.099 - 0.198 \\ 
  2003 & 10044.00 & 5500 - 14588 & 0.15 & 0.101 - 0.203 \\ 
  2004 & 10330.00 & 5634 - 15025 & 0.16 & 0.104 - 0.209 \\ 
  2005 & 10706.00 & 5825 - 15587 & 0.16 & 0.107 - 0.217 \\ 
  2006 & 11220.00 & 6110 - 16330 & 0.17 & 0.113 - 0.227 \\ 
  2007 & 11802.00 & 6431 - 17173 & 0.18 & 0.119 - 0.239 \\ 
  2008 & 12291.00 & 6684 - 17897 & 0.19 & 0.124 - 0.249 \\ 
  2009 & 12632.00 & 6862 - 18403 & 0.19 & 0.127 - 0.256 \\ 
  2010 & 12769.00 & 6913 - 18624 & 0.19 & 0.128 - 0.258 \\ 
  2011 & 12852.00 & 6954 - 18751 & 0.20 & 0.129 - 0.260 \\ 
   \hline
\end{tabular}
\end{table}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/ts7_Spawning_output_with_95_asymptotic_intervals_intervals.png}
\caption{Time series of spawning output trajectory (circles and line:
median; light broken lines: 95\% credibility intervals) for the base
case assessment model. \label{fig:Spawnbio_all}}
\end{figure}

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/ts9_Spawning_depletion_with_95_asymptotic_intervals_intervals.png}
\caption{Estimated relative depletion with approximate 95\% asymptotic
confidnce intervals (dashed lines) for the base case assessment model.
\label{fig:RelDeplete_all}}
\end{figure}

\FloatBarrier

\subsection*{Recruitment}\label{recruitment}
\addcontentsline{toc}{subsection}{Recruitment}

\hl{Include: trends and current levels relative to virgin or historic levels-include 
table for last 10 years and graph with long term estimates.}

Recruitment Figure: (Figure \ref{fig:Recruits_all})\\
Recruitment Tables: (Tables \ref{tab:Recruit_mod1},
\ref{tab:Recruit_mod2} and \ref{tab:Recruit_mod3})

\begin{table}[ht]
\centering
\caption{Recent recruitment for the Base model.} 
\label{tab:Recruit_mod1}
\begin{tabular}{>{\centering}p{.8in}>{\centering}p{1.6in}>{\centering}p{1.3in}}
  \hline
Year & Estimated Recruitment (1,000s) & \~{} 95\% confidence interval \\ 
  \hline
2002 & 2030.00 & 1104 - 3733 \\ 
  2003 & 820.00 & 374 - 1799 \\ 
  2004 & 2983.00 & 1663 - 5348 \\ 
  2005 & 2055.00 & 1029 - 4102 \\ 
  2006 & 1270.00 & 558 - 2887 \\ 
  2007 & 1210.00 & 485 - 3016 \\ 
  2008 & 10906.00 & 5555 - 21412 \\ 
  2009 & 2753.00 & 871 - 8700 \\ 
  2010 & 3664.00 & 1023 - 13130 \\ 
  2011 & 3683.00 & 1384 - 9798 \\ 
   \hline
\end{tabular}
\end{table}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/ts11_Age-0_recruits_(1000s)_with_95_asymptotic_intervals.png}
\caption{Time series of estimated Pacific ocean perch recruitments for
the base-case model with 95\% confidence or credibility intervals.
\label{fig:Recruits_all}}
\end{figure}

\FloatBarrier

\subsection*{Exploitation status}\label{exploitation-status}
\addcontentsline{toc}{subsection}{Exploitation status}

\hl{Include: exploitation rates (i.e., total catch divided by exploitable biomass, or the annual SPR harvest rate) â include a table with the last 10 years of data and a graph showing the trend in fishing mortality relative to the target (y-axis) plotted against the trend in biomass relative to the target (x-axis).}

Exploitation Tables: Table \ref{tab:SPR_Exploit_mod1}, Table
\ref{tab:SPR_Exploit_mod2}, Table \ref{tab:SPR_Exploit_mod3}
Exploitation Figure: Figure \ref{fig:SPR_all}).

A summary of Pacific ocean perch exploitation histories for base model
is provided as Figure \ref{fig:Phase_all}.

\FloatBarrier

\begin{table}[ht]
\centering
\caption{Recent trend in spawning potential 
                                        ratio and exploitation for Pacific ocean perch in the Base model.  Fishing intensity is (1-SPR) 
                                        divided by 50\% (the SPR target) and exploitation 
                                        is F divided by F\textsubscript{SPR}.} 
\label{tab:SPR_Exploit_mod1}
\begin{tabular}{l>{\centering}p{1in}>{\centering}p{1.2in}>{\centering}p{1in}>{\centering}p{1.2in}}
  \hline
Year & Fishing intensity & \~{} 95\% confidence interval & Exploitation rate & \~{} 95\% confidence interval \\ 
  \hline
2001 & 0.616 & 0.416 - 0.816 & 0.016 & 0.009 - 0.023 \\ 
  2002 & 0.388 & 0.243 - 0.533 & 0.009 & 0.005 - 0.013 \\ 
  2003 & 0.347 & 0.214 - 0.481 & 0.007 & 0.004 - 0.011 \\ 
  2004 & 0.315 & 0.192 - 0.439 & 0.006 & 0.004 - 0.009 \\ 
  2005 & 0.172 & 0.100 - 0.243 & 0.003 & 0.002 - 0.005 \\ 
  2006 & 0.183 & 0.107 - 0.259 & 0.004 & 0.002 - 0.005 \\ 
  2007 & 0.300 & 0.182 - 0.419 & 0.006 & 0.004 - 0.009 \\ 
  2008 & 0.254 & 0.149 - 0.358 & 0.005 & 0.003 - 0.008 \\ 
  2009 & 0.354 & 0.208 - 0.500 & 0.008 & 0.004 - 0.012 \\ 
  2010 & 0.255 & 0.150 - 0.360 & 0.006 & 0.003 - 0.008 \\ 
   \hline
\end{tabular}
\end{table}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/SPR3_ratiointerval.png}
\caption{Estimated spawning potential ratio (SPR) for the base-case
model. One minus SPR is plotted so that higher exploitation rates occur
on the upper portion of the y-axis. The management target is plotted as
a red horizontal line and values above this reflect harvests in excess
of the overfishing proxy based on the SPR\textsubscript{50\%} harvest
rate. The last year in the time series is 2010. \label{fig:SPR_all}}
\end{figure}

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/SPR4_phase.png}
\caption{Phase plot of estimated relative (1-SPR) vs.~relative spawning
biomass for the base case model. The relative (1-SPR) is (1-SPR) divided
by 50\% (the SPR target). Relative depletion is the annual spawning
biomass divided by the unfished spawning biomass. \label{fig:Phase_all}}
\end{figure}

\FloatBarrier

\subsection*{Ecosystem Considerations}\label{ecosystem-considerations}
\addcontentsline{toc}{subsection}{Ecosystem Considerations}

In this assessment, ecosystem considerations were\ldots{}..

\subsection*{Reference Points}\label{reference-points}
\addcontentsline{toc}{subsection}{Reference Points}

\hl{Include:} management targets and definition of overfishing,
including the harvest rate that brings the stock to equilibrium at
\(B_{40\%}\) (the \(B_{MSY}\) proxy) and the equilibrium stock size that
results from fishing at the default harvest rate (the \(F_{MSY}\)
proxy). Include a summary table that compares estimated reference points
for SSB, SPR, Exploitation Rate and Yield based on SSBproxy for MSY,
SPRproxy for MSY, and estimated MSY values

\hl{Write intro paragraph....and remove text for Models 2 and 3 if not needed}

This stock assessment estimates that Pacific ocean perch in the Base
model are below the biomass target, but below the minimum stock size
threshold. \hl{Add sentence about spawning output trend.} The estimated
relative depletion level for \hl{Model 1} in 2011 is 19.5\%
(\textasciitilde{}95\% asymptotic interval: \(\pm\) 12.9\%-26\%,
corresponding to an unfished spawning output of 12852 billion eggs
(\textasciitilde{}95\% asymptotic interval:
6953.7119917681-18751.0880082319 billion eggs) of spawning output in the
base model (Table \ref{tab:Ref_pts_mod1}). Unfished age 3+ biomass was
estimated to be 121380 mt in the base case model. The target spawning
output based on the biomass target (\(SB_{40\%}\)) is 26418.6 billion
eggs, which gives a catch of 1064.7 mt. Equilibrium yield at the proxy
\(F_{MSY}\) harvest rate corresponding to \(SPR_{50\%}\) is 869.6 mt.

This stock assessment estimates that Pacific ocean perch in the are

the biomass target, but\\
the minimum stock size threshold.
\hl{Add sentence about spawning output trend.} The estimated relative
depletion level for \hl{Model 2} in 2011 is (\textasciitilde{}95\%
asymptotic interval: \(\pm\) ), corresponding to an unfished spawning
output of (\textasciitilde{}95\% asymptotic interval: ) of spawning
output in the base model (Table \ref{tab:Ref_pts_mod2}). Unfished age 3+
biomass was estimated to be\\
mt in the base case model. The target spawning output based on the
biomass target (\(SB_{40\%}\)) is , which gives a catch of mt.
Equilibrium yield at the proxy \(F_{MSY}\) harvest rate corresponding to
\(SPR_{50\%}\) is mt.

This stock assessment estimates that Pacific ocean perch in the are

the biomass target, but\\
the minimum stock size threshold.
\hl{Add sentence about spawning output trend.} The estimated relative
depletion level or \hl{Model 3} in 2011 is (\textasciitilde{}95\%
asymptotic interval: \(\pm\) ), corresponding to an unfished spawning
output of (\textasciitilde{}95\% asymptotic interval: ) of spawning
output in the base model (Table \ref{tab:Ref_pts_mod3}). Unfished age 3+
biomass was estimated to be mt in the base case model. The target
spawning output based on the biomass target (\(SB_{40\%}\)) is , which
gives a catch of mt. Equilibrium yield at the proxy \(F_{MSY}\) harvest
rate corresponding to \(SPR_{50\%}\) is mt.

\FloatBarrier

\begin{table}[ht]
\centering
\caption{Summary of reference 
                                      points and management quantities for the 
                                      base case Base model.} 
\label{tab:Ref_pts_mod1}
\begin{tabular}{>{\raggedright}p{4.1in}>{\centering}p{.65in}>{\centering}p{1.4in}}
  \hline
\textbf{Quantity} & \textbf{Estimate} & \textbf{\~95\%  Confidence Interval} \\ 
  \hline
Unfished spawning output (billion eggs) & 66046.4 &   54008 -  78084.8 \\ 
  Unfished age 3+ biomass (mt) & 121380 & 99829.6 - 142930.4 \\ 
  Unfished recruitment (R0, thousands) & 9398.2 &  7835.3 -  11272.9 \\ 
  Spawning output(2011 billion eggs) & 12852.4 &  6953.7 -  18751.1 \\ 
  Depletion (2011) & 0.195 &   0.129 -     0.26 \\ 
  \textbf{$\text{Reference points based on } \mathbf{SB_{40\%}}$} &  &  \\ 
  Proxy spawning output ($B_{40\%}$) & 26418.6 & 21603.2 -    31234 \\ 
  SPR resulting in $B_{40\%}$ ($SPR_{B40\%}$) & 0.625 &   0.625 -    0.625 \\ 
  Exploitation rate resulting in $B_{40\%}$ & 0.021 &    0.02 -    0.021 \\ 
  Yield with $SPR_{B40\%}$ at $B_{40\%}$ (mt) & 1064.7 &   875.1 -   1254.2 \\ 
  \textbf{\textit{Reference points based on SPR proxy for MSY}} &  &  \\ 
  Spawning output & 13209.3 & 10801.6 -    15617 \\ 
  $SPR_{proxy}$ & 0.5 &  \\ 
  Exploitation rate corresponding to $SPR_{proxy}$ & 0.032 &   0.032 -    0.032 \\ 
  Yield with $SPR_{proxy}$ at $SB_{SPR}$ (mt) & 869.6 &   714.5 -   1024.6 \\ 
  \textbf{\textit{Reference points based on estimated MSY values}} &  &  \\ 
  Spawning output at $MSY$ ($SB_{MSY}$) & 25790.9 & 21104.1 -  30477.7 \\ 
  $SPR_{MSY}$ & 0.619 &   0.618 -     0.62 \\ 
  Exploitation rate at $MSY$ & 0.021 &   0.021 -    0.021 \\ 
  $MSY$ (mt)  & 1065.1 &   875.4 -   1254.7 \\ 
   \hline
\end{tabular}
\end{table}

\FloatBarrier

\subsection*{Management Performance}\label{management-performance}
\addcontentsline{toc}{subsection}{Management Performance}

\hl{Include: catches in comparison to OFL, ABC and OY/ACL values for the most 
recent 10 years (when available), overfishing levels, actual catch and discard. 
Include OFL(encountered), OFL(retained) and OFL(dead) if different due to discard 
and discard mortality.}

Management performance table: Table \ref{tab:mnmgt_perform}

\begin{table}[ht]
\centering
\caption{Recent trend in total catch and commercial 
                              landings (mt) relative to the management guidelines. 
                              Estimated total catch reflect the commercial landings 
                              plus the model estimated discarded biomass.} 
\label{tab:mnmgt_perform}
\scalebox{0.9}{
\begin{tabular}{>{\raggedleft}p{1in}>{\centering}p{1in}>{\centering}p{1in}>{\centering}p{1in}>{\centering}p{1in}}
  \hline
Year & OFL (mt; ABC prior to 2011) & ABC (mt) & ACL (mt; OY prior to 2011) & Estimated total catch (mt) \\ 
  \hline
\textbf{2007} & - & - & - & - \\ 
  \textbf{2008} & - & - & - & - \\ 
  \textbf{2009} & - & - & - & - \\ 
  \textbf{2010} & - & - & - & - \\ 
  \textbf{2011} & - & - & - & - \\ 
  \textbf{2012} & - & - & - & - \\ 
  \textbf{2013} & - & - & - & - \\ 
  \textbf{2014} & - & - & - & - \\ 
  \textbf{2015} & - & - & - & - \\ 
  \textbf{2016} & - & - & - & - \\ 
   \hline
\end{tabular}
}
\end{table}

\subsection*{Unresolved Problems And Major
Uncertainties}\label{unresolved-problems-and-major-uncertainties}
\addcontentsline{toc}{subsection}{Unresolved Problems And Major
Uncertainties}

TBD after STAR panel

\FloatBarrier

\subsection*{Decision Table(s) (groundfish
only)}\label{decision-tables-groundfish-only}
\addcontentsline{toc}{subsection}{Decision Table(s) (groundfish only)}

\hl{Include: projected yields (OFL, ABC and ACL), spawning biomass, and stock 
depletion levels for each year. Not required in draft assessments undergoing review.}

OFL projection table: Table \ref{tab:OFL_projection}

Decision table(s) Table \ref{tab:Decision_table_mod1}, Table
\ref{tab:Decision_table_mod2}, Table \ref{tab:Decision_table_mod3}

\begin{verbatim}
Yield curve: Figure \ref{fig:Yield_all}
\end{verbatim}

\begin{table}[ht]
\centering
\caption{Projections of potential OFL (mt) and the ACL (mt) for each model, using the base model forecast.} 
\label{tab:OFL_projection}
\begin{tabular}{lrr}
  \hline
Year & OFL & ACL \\ 
  \hline
2011 & 857.65 & 180.00 \\ 
  2012 & 859.55 & 183.00 \\ 
  2013 & 865.17 & 577.91 \\ 
  2014 & 868.10 & 588.62 \\ 
  2015 & 881.24 & 608.91 \\ 
  2016 & 897.89 & 629.76 \\ 
  2017 & 912.69 & 646.89 \\ 
  2018 & 923.94 & 657.16 \\ 
  2019 & 932.33 & 663.60 \\ 
  2020 & 939.09 & 669.01 \\ 
  2021 & 945.15 & 677.76 \\ 
  2022 & 950.93 & 688.08 \\ 
   \hline
\end{tabular}
\end{table}\begin{table}[ht]
\centering
\caption{Summary of 10-year 
                                             projections beginning in 2013 
                                             for alternate states of nature based on 
                                             an axis of uncertainty for the Base model.  Columns range over low, mid, and high
                                             states of nature, and rows range over different 
                                             assumptions of catch levels. An entry of "--" 
                                             indicates that the stock is driven to very low 
                                             abundance under the particular scenario.} 
\label{tab:Decision_table_mod1}
\scalebox{0.85}{
\begin{tabular}{l|cc|>{\centering}p{.7in}c|>{\centering}p{.7in}c|>{\centering}p{.7in}c}
   \multicolumn{3}{c}{}  &  \multicolumn{2}{c}{} 
                               & \multicolumn{2}{c}{\textbf{States of nature}} 
                               & \multicolumn{2}{c}{} \\
  \multicolumn{3}{c}{}  &  \multicolumn{2}{c}{Low M 0.05} 
                               & \multicolumn{2}{c}{Base M 0.07} 
                               &  \multicolumn{2}{c}{High M 0.09} \\
 \hline
 & Year & Catch & Spawning Output & Depletion & Spawning Output & Depletion & Spawning Output & Depletion \\ 
  \hline
 & 2019 & - & - & - & - & - & - & - \\ 
   & 2020 & - & - & - & - & - & - & - \\ 
   & 2021 & - & - & - & - & - & - & - \\ 
  40-10 Rule,  & 2022 & - & - & - & - & - & - & - \\ 
  Low M & 2023 & - & - & - & - & - & - & - \\ 
   & 2024 & - & - & - & - & - & - & - \\ 
   & 2025 & - & - & - & - & - & - & - \\ 
   & 2026 & - & - & - & - & - & - & - \\ 
   & 2027 & - & - & - & - & - & - & - \\ 
   & 2028 & - & - & - & - & - & - & - \\ 
   \hline
 & 2019 & - & - & - & - & - & - & - \\ 
   & 2020 & - & - & - & - & - & - & - \\ 
   & 2021 & - & - & - & - & - & - & - \\ 
  40-10 Rule & 2022 & - & - & - & - & - & - & - \\ 
   & 2023 & - & - & - & - & - & - & - \\ 
   & 2024 & - & - & - & - & - & - & - \\ 
   & 2025 & - & - & - & - & - & - & - \\ 
   & 2026 & - & - & - & - & - & - & - \\ 
   & 2027 & - & - & - & - & - & - & - \\ 
   & 2028 & - & - & - & - & - & - & - \\ 
   \hline
 & 2019 & - & - & - & - & - & - & - \\ 
   & 2020 & - & - & - & - & - & - & - \\ 
   & 2021 & - & - & - & - & - & - & - \\ 
  40-10 Rule, & 2022 & - & - & - & - & - & - & - \\ 
  High M & 2023 & - & - & - & - & - & - & - \\ 
   & 2024 & - & - & - & - & - & - & - \\ 
   & 2025 & - & - & - & - & - & - & - \\ 
   & 2026 & - & - & - & - & - & - & - \\ 
   & 2027 & - & - & - & - & - & - & - \\ 
   & 2028 & - & - & - & - & - & - & - \\ 
   \hline
 & 2019 & - & - & - & - & - & - & - \\ 
   & 2020 & - & - & - & - & - & - & - \\ 
   & 2021 & - & - & - & - & - & - & - \\ 
  Average & 2022 & - & - & - & - & - & - & - \\ 
  Catch & 2023 & - & - & - & - & - & - & - \\ 
   & 2024 & - & - & - & - & - & - & - \\ 
   & 2025 & - & - & - & - & - & - & - \\ 
   & 2026 & - & - & - & - & - & - & - \\ 
   & 2027 & - & - & - & - & - & - & - \\ 
   & 2028 & - & - & - & - & - & - & - \\ 
   \hline
\end{tabular}
}
\end{table}

\begin{sidewaystable}[ht]
\centering
\caption{Base case results summary.} 
\label{tab:base_summary}
\scalebox{0.6}{
\begin{tabular}{r>{\centering}p{1.1in}>{\centering}p{1.1in}>{\centering}p{1.1in}>{\centering}p{1.1in}>{\centering}p{1.1in}>{\centering}p{1.1in}>{\centering}p{1.1in}>{\centering}p{1.1in}>{\centering}p{1.1in}>{\centering}p{1.1in}}
  \hline
Quantity & 2002 & 2003 & 2004 & 2005 & 2006 & 2007 & 2008 & 2009 & 2010 & 2011 \\ 
  \hline
Landings (mt) &  &  &  &  &  &  &  &  &  &  \\ 
  Total Est. Catch (mt) &  &  &  &  &  &  &  &  &  &  \\ 
  OFL (mt) &  &  &  &  &  &  &  &  &  &  \\ 
  ACL (mt) &  &  &  &  &  &  &  &  &  &  \\ 
   \hline
(1-$SPR$)(1-$SPR_{50\%}$) &  & 0.39 & 0.35 & 0.32 & 0.17 & 0.18 & 0.30 & 0.25 & 0.35 & 0.26 \\ 
   \hline
Exploitation rate &  & 0.01 & 0.01 & 0.01 & 0.00 & 0.00 & 0.01 & 0.01 & 0.01 & 0.01 \\ 
  Age 3+ biomass (mt) & 26104.0 & 20233.4 & 21304.4 & 22166.0 & 22909.4 & 23497.1 & 24161.9 & 24600.9 & 24881.0 & 24963.3 \\ 
   \hline
Spawning Output & 12852 &  9812 & 10044 & 10330 & 10706 & 11220 & 11802 & 12291 & 12632 & 12769 \\ 
  ~95\% CI & 6954 - 18751 & 5399 - 14225 & 5500 - 14588 & 5634 - 15025 & 5825 - 15587 & 6110 - 16330 & 6431 - 17173 & 6684 - 17897 & 6862 - 18403 & 6913 - 18624 \\ 
   \hline
Depletion & 0.195 & 0.149 & 0.152 & 0.156 & 0.162 & 0.170 & 0.179 & 0.186 & 0.191 & 0.193 \\ 
  ~95\% CI & 0.129 - 0.260 & 0.099 - 0.198 & 0.101 - 0.203 & 0.104 - 0.209 & 0.107 - 0.217 & 0.113 - 0.227 & 0.119 - 0.239 & 0.124 - 0.249 & 0.127 - 0.256 & 0.128 - 0.258 \\ 
   \hline
Recruits &  3683 &  2030 &   820 &  2983 &  2055 &  1270 &  1210 & 10906 &  2753 &  3664 \\ 
  ~95\% CI & 1384 - 9798 & 1104 - 3733 & 374 - 1799 & 1663 - 5348 & 1029 - 4102 & 558 - 2887 & 485 - 3016 & 5555 - 21412 & 871 - 8700 & 1023 - 13130 \\ 
   \hline
\end{tabular}
}
\end{sidewaystable}

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/yield1_yield_curve.png}
\caption{Equilibrium yield curve for the base case model. Values are
based on the 2010 fishery selectivity and with steepness fixed
at\ldots{} \label{fig:Yield_all}}
\end{figure}

\FloatBarrier

\newpage

\subsection*{Research And Data Needs}\label{research-and-data-needs}
\addcontentsline{toc}{subsection}{Research And Data Needs}

\hl{Include: identify information gaps that seriously impede the stock assessment.}

We recommend the following research be conducted before the next
assessment:

\begin{enumerate}

\item List item No. 1 in the list

\item List item No. 2 in the list, etc.

\end{enumerate}

\subsection*{Rebuilding Projections}\label{rebuilding-projections}
\addcontentsline{toc}{subsection}{Rebuilding Projections}

\hl{Include: reference to the principal results from rebuilding analysis if the 
stock is overfished. This section should be included in the Final/SAFE version 
assessment document but is not required for draft assessments undergoing review. 
See Rebuilding Analysis terms of reference for detailed information on 
rebuilding analysis requirements.}

\FloatBarrier

\newpage

\renewcommand{\thefigure}{\arabic{figure}}
\renewcommand{\thetable}{\arabic{table}}

\setcounter{figure}{0} \setcounter{table}{0}

\section{Introduction}\label{introduction}

\subsection{Basic Information}\label{basic-information}

\hl{Include: Scientific name, distribution, the basis of the choice of stock structure, 
including regional differences in life history or other biological characteristics 
that should form the basis of management units.}

\subsection{Map}\label{map}

A map showing the scope of the assessment and depicting boundaries for
fisheries or data collection strata is provided in Figure
\ref{fig:boundary_map}.

\subsection{Life History}\label{life-history}

\hl{Include: Important features of life history that affect management (e.g., migration, 
sexual dimorphism, bathymetric demography).}

\subsection{Ecosystem Considerations}\label{ecosystem-considerations-1}

\hl{Include: Ecosystem considerations (e.g., ecosystem role and trophic relationships of 
the species, habitat requirements/preferences, relevant data on ecosystem processes 
that may affect stock or parameters used in the stock assessment, and/or cross-FMP 
interactions with other fisheries). This section should note if environmental 
correlations or food web interactions were incorporated into the assessment model. 
The length and depth of this section would depend on availability of data and reports 
from the IEA, expertise of the STAT, and whether ecosystem factors are informational 
to contribute quantitative information to the assessment.}

\subsection{Fishery Information}\label{fishery-information}

\hl{Include: Important features of current fishery and relevant history of fishery.}

Rockfish example: The rockfish fishery off the U.S. Pacific coast first
developed off California in the late 19th century as a hook-and-line
fishery (Love et al. \protect\hyperlink{ref-Love2002}{2002}).\\
The rockfish trawl fishery was established in the early 1940s, when the
United States became involved in World War II and wartime shortage of
red meat created an increased demand for other sources of protein (Harry
and Morgan \protect\hyperlink{ref-Harry1961}{1961}, Alverson et al.
\protect\hyperlink{ref-Alverson1964}{1964}). Etc\ldots{}.

\subsection{Summary of Management
History}\label{summary-of-management-history}

\hl{Include: Summary of management history (e.g., changes in mesh sizes, trip 
limits, or other management actions that may have significantly altered selection, 
catch rates, or discards).}

\subsection{Management Performance}\label{management-performance-1}

\hl{Include: Management performance, including a table or tables comparing 
Overfishing Limit (OFL), Annual Catch Limit (ACL), Harvest Guideline (HG) 
[CPS only], landings, and catch (i.e., landings plus discard) for each area and year.}

Management performance table: (Table \ref{tab:mnmgt_perform})\\
A summary of these values as well as other base case summary results can
be found in Table \ref{tab:base_summary}.

\subsection{Fisheries off Canada, Alaska, and/or
Mexico}\label{fisheries-off-canada-alaska-andor-mexico}

Include if necessary.

\section{Assessment}\label{assessment}

\subsection{Data}\label{data}

Data used in the Pacific ocean perch assessment are summarized in Figure
\ref{fig:data_plot}.\\
A description of each data source is below.

\subsubsection{Commercial Fishery
Landings}\label{commercial-fishery-landings}

\textbf{Sub-heading 1}

\textbf{Sub-heading 2}

\textbf{Sub-heading 3}

\subsubsection{Sport Fishery Removals}\label{sport-fishery-removals}

\textbf{Sub-heading 1}

\textbf{Sub-heading 2}

\textbf{Sub-heading 3}

\subsubsection{Estimated Discards}\label{estimated-discards}

\textbf{Sub-heading 1}

\textbf{Sub-heading 2}

\textbf{Sub-heading 3}

\subsubsection{Abundance Indices}\label{abundance-indices}

\textbf{Sub-heading 1}

\textbf{Sub-heading 2}

\subsubsection{Fishery-Independent Data: possible
sources}\label{fishery-independent-data-possible-sources}

\emph{Northwest Fisheries Science Center (NWFSC) slope survey}\\
The NWFSC slope survey was conducted annually from 1999 to 2002.\\
The depth range of this survey is 100-700 fm.

\emph{Northwest Fisheries Science Center (NWFSC) shelf-slope survey}\\
This survey is referred to as the âcombo,â conducted annually since
2003.\\
The survey consistently covered depths between 30 and 700 fm.

\emph{Alaska Fisheries Science Center (AFSC) shelf survey}\\
The survey, often referred to as the âtriennialâ survey was
conducted every third year between 1977 and (and conducted in 2004 by
the NWFSC using the same protocols). The triennial survey trawls in
depths of 30 to 275 fm.

\emph{Pikitch Study}\\
The Pikitch study was conducted between 1985 and 1987 (Pikitch et al.
\protect\hyperlink{ref-Pikitch1988}{1988}). The northern and southern
boundaries of the study were \(48^\circ 42^\prime\) N latitude and
\(42^\circ 60^\prime\) N. latitude respectively, which is primarily
within the Columbia INPFC area (Pikitch et al.
\protect\hyperlink{ref-Pikitch1988}{1988} , Rogers and Pikitch
\protect\hyperlink{ref-Rogers1992}{1992}). Participation in the study
was voluntary and included vessels using bottom, midwater, and shrimp
trawl gears.\\
Observers of normal fishing operations on commercial vessels collected
the data, estimated the total weight of the catch by tow and recorded
the weight of species retained and discarded in the sample.

\emph{Enhanced Data Collection Project (EDCP)}\\
The EDCP was conducted by ODFW to collect information on bycatch and
discard groundfish species off the coast of Oregon from late 1995 to
early 1999.\\
EDCP had limited spatial coverage in Oregon waters only.

\emph{Partnership For Interdisciplinary Studies of Coastal Oceans
(PISCO)}\\
Blurb on species presence in PISCO surveys

\subsubsection{Biological Parameters and
Data}\label{biological-parameters-and-data}

\textbf{Length And Age Compositions}

Include: Sample size information for length and age composition data by
area, year, gear, market category, etc., including both the number of
trips and fish sampled.

Length compositions were provided from the following sources, by region,
with brief descriptions below:

\emph{Model 1}

\begin{itemize}[noitemsep,nolistsep,topsep=0pt]
  \item Source No. 1 (\emph{ex. research, commerical dead fish, live fish, etc},\\     
        date range (ex. 2010-2011)
  \item Source No. 2 (\emph{ex. research, commerical dead fish, live fish, etc},\\      
        date range (ex. 2010-2011) 
  \item etc...      
  \item Begin sublist if desired 
    \begin{itemize}[noitemsep,nolistsep]
      \item Sublist source No. 1     
      \item Sublist source No. 2        
      \item etc...     
    \end{itemize}
  \item Back to main list, next Source     
  \item Last Source     
\end{itemize}

Can duplicate this list if you have more than one assessment model

Possible sources of age and length data:

\emph{Recreational: Washington (WDFW)}

\emph{Recreational: California MRFSS And CRFS Length Composition Data}
Individual fish lengths recorded by MRFSS (1980-2003) and CRFS
(2004-2011) samplers were downloaded from the RecFIN website
(www.recfin.org). CRFS data from 2012-2014 were obtained directly from
CDFW.

\emph{Recreational: Oregon Recreational Boat Survey (ORBS)} Biological
data from the ORBS program were provided by ODFW. The ORBS is a dockside
sampling program for the both the recreational CPFV and private modes.
Length composition samples from north of Florence for the CPFV and
private fleets were provided from 1980-2014. Samples from south of
Florence spanned 1984-2014

\emph{Recreational: Miller and Gotshall
(\protect\hyperlink{ref-Miller1965}{1965})}\\
The Northern California Marine Sport Fish Survey conducted an assessment
survey with goals that included estimation of annual fishing effort by
all recreational fishing modes, catch by weight, CPUE, and collection of
data to analyze length compositions

\emph{Commercial: PacFIN (Oregon and California)}

\emph{Research: NMFS Groundfish Ecology Survey}

From 2001-2005, the SWFSC Fisheries Ecology Division conducted longline
surveys aboard a chartered commercial longline vessel at various
stations between Monterey and Davenport, CA (\(36^\circ\) N. latitude to
\(37.5^\circ\) N. latitude) (pers. comm. Don Pearson, SWFSC). Longline
gear was set in various depths from 10 meters to 700 meters, parallel to
the depth contour. Each longline set consisted of 3-5 skates, each with
about 250 2/0 circle hooks baited with squid.\\
In nearshore habitats, the gear soaked for roughly 30 minutes.

\emph{Research: California Collaborative Fisheries Research Program
(CCFRP)}

\emph{Research: NWFSC shelf-slope survey}

\emph{Research: NWFSC slope survey}

\emph{Research: Abrams Thesis}

\vspace{.5cm} \textbf{Age Structures}

Age structure data were available from the following sources:

\emph{Model Region 1}

\begin{itemize}[noitemsep,nolistsep,topsep=0pt]
  \item Source No. 1 (\emph{ex. research, commericla dead fish, live fish, etc},\\ 
        date range (ex. 2010-2011)
  \item Source No. 2 (\emph{ex. research, commericla dead fish, live fish, etc},\\
        date range (ex. 2010-2011) 
  \item etc...      
  \item Begin sublist if desired 
    \begin{itemize}[noitemsep,nolistsep]
      \item Sublist source No. 1     
      \item Sublist source No. 2        
      \item etc...     
    \end{itemize}
  \item Back to main list, next Source     
  \item Last Source     
\end{itemize}

Can duplicate this list if you have more than one assessment model

Length-at-age was initially estimated external to the population
dynamics models using the von Bertalanffy growth curve (Bertalanffy
\protect\hyperlink{ref-vonB1938}{1938}),
\(L_i = L_{\infty}e^{(-k[t-t_0])}\), where \(L_i\) is the length (cm) at
age \(i\), \(t\) is age in years, \(k\) is rate of increase in growth,
\(t_0\) is the intercept, and \(L_{\infty}\) is the asymptotic length.

\vspace{.5cm} \textbf{Aging Precision And Bias}

\vspace{.5cm} \textbf{Weight-Length}

The weight-length relationship is based on the standard power function:
\(W = \alpha(L^\beta)\) where \(W\) is individual weight (kg), \(L\) is
length (cm), and \(\alpha\) and \(\beta\) are coefficients used as
constants.

\vspace{.5cm} \textbf{Maturity And Fecundity}

\vspace{.5cm} \textbf{Natural Mortality}

Natural mortality for wild fish populations is extremely difficult to
estimate.

\vspace{.5cm} \textbf{Sex ratios}

\subsubsection{Environmental Or Ecosystem Data Included In The
Assessment}\label{environmental-or-ecosystem-data-included-in-the-assessment}

\subsection{History Of Modeling Approaches Used For This
Stock}\label{history-of-modeling-approaches-used-for-this-stock}

\subsubsection{Previous Assessments}\label{previous-assessments}

\subsubsection{Previous Assessment
Recommendations}\label{previous-assessment-recommendations}

Include: Response to STAR panel recommendations from the most recent
previous assessment.

\begin{description}[style=unboxed]

  \item[Recommendation 1: blah blah blah.] \hfill \\

   STAT response: blah blah blah....

\item[Recommendation 2: blah blah blah.] \hfill \\

  STAT response: blah blah blah....

\item[Recommendation 3: blah blah blah., etc.] \hfill \\

  STAT response: Continue recommendations as needed


\end{description}

\subsection{Model Description}\label{model-description}

\subsubsection{Transition To The Current Stock
Assessment}\label{transition-to-the-current-stock-assessment}

Include: Complete description of any new modeling approaches

Below, we describe the most important changes made since the last full
assessment and explain rationale for each change.:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Change No. 1. \emph{Rationale}: blah blah blah.
\item
  Change No. 2. \emph{Rationale}: blah blah blah.
\item
  Change No. 3. \emph{Rationale}: Continue list as needed.
\end{enumerate}

\subsubsection{Definition of Fleets and
Areas}\label{definition-of-fleets-and-areas}

We generated data sources for each of the models. Fleets by model
include:

\textbf{Model Region 1 or remove this line if only one model}

\emph{Commercial}: The commercial fleets include\ldots{}

\emph{Recreational}: The recreational fleets include\ldots{}

\emph{Research}: Research derived-data include\ldots{}

\subsubsection{Summary of Data for Fleets and
Areas}\label{summary-of-data-for-fleets-and-areas}

\subsubsection{Modeling Software}\label{modeling-software}

The STAT team used Stock Synthesis 3 version 3.24u by Dr.~Richard Methot
at the NWFSC. This most recent version (SS-V3.24u) was used, since it
included improvements and corrections to older versions.

\subsubsection{Data Weighting}\label{data-weighting}

Citation for Francis method (Francis
\protect\hyperlink{ref-Francis2011}{2011})\\
Citation for Ianelli-McAllister harmonic mean method (McAllister and
Ianelli \protect\hyperlink{ref-McAllister1997}{1997})

\subsubsection{Priors}\label{priors}

Citation for Hamel prior on natural mortality (Hamel
\protect\hyperlink{ref-Hamel2015}{2015})

\subsubsection{General Model
Specifications}\label{general-model-specifications}

Citation for posterior predictive fecundity relationship from Dick
(\protect\hyperlink{ref-Dick2009}{2009})\\
Model data, control, starter, and forecast files can be found in
Appendices A-D.

\subsubsection{Estimated And Fixed
Parameters}\label{estimated-and-fixed-parameters}

A full list of all estimated and fixed parameters is provided in
Tables\ldots{}. Estimated and fixed parameters tables currently read in
from .csv file, EXAMPLE: Table \ref{tab:Model1_params}

\subsection{Model Selection and
Evaluation}\label{model-selection-and-evaluation}

\subsubsection{Key Assumptions and Structural
Choices}\label{key-assumptions-and-structural-choices}

Include: Evidence of search for balance between model realism and
parsimony.\\
Comparison of key model assumptions, include comparisons based on nested
models (e.g., asymptotic vs.~domed selectivities, constant
vs.~time-varying selectivities).

\subsubsection{Alternate Models
Considered}\label{alternate-models-considered}

Include: Summary of alternate model configurations that were tried but
rejected.

\subsubsection{Convergence}\label{convergence}

Include: Randomization run results or other evidence of search for
global best estimates.

Convergence testing through use of dispersed starting values often
requires extreme values to actually explore new areas of the
multivariate likelihood surface. Jitter is a SS option that generates
random starting values from a normal distribution logistically
transformed into each parameter's range (Methot
\protect\hyperlink{ref-Methot2015}{2015}). Table \ref{tab:jitter} shows
the results of running 100 jitters for each pre-STAR base model\ldots{}.

\subsection{Response To The Current STAR Panel
Requests}\label{response-to-the-current-star-panel-requests}

\begin{description}[style=unboxed]

\item[Request No. 1: Add after STAR panel.] \hfill \\

    \textbf{Rationale:} Add after STAR panel.  

    \textbf{STAT Response:} Add after STAR panel.

\item[Request No. 2: Add after STAR panel.] \hfill \\

    \textbf{Rationale:} Add after STAR panel.

    \textbf{STAT Response:} Add after STAR panel.

\item[Request No. 3: Add after STAR panel.] \hfill \\

    \textbf{Rationale:} Add after STAR panel.
  
    \textbf{STAT Response:} Add after STAR panel.

\item[Request No. 4: Example of a request that may have a list:] \hfill \\
\begin{itemize}
\item \textbf{Item No. 1}
\item \textbf{Item No. 2}
\item \textbf{Item No. 3, etc.}
\end{itemize}

    \textbf{Rationale:} Add after STAR panel.

    \textbf{STAT Response:} Continue requests as needed.


\end{description}

\subsection{Model 1}\label{model-1}

\subsubsection{Model 1 Base Case
Results}\label{model-1-base-case-results}

Table \ref{tab:Model1_params}

\subsubsection{Model 1 Uncertainty and Sensitivity
Analyses}\label{model-1-uncertainty-and-sensitivity-analyses}

Table \ref{tab:Sensitivity_model1}

\subsubsection{Model 1 Retrospective
Analysis}\label{model-1-retrospective-analysis}

\subsubsection{Model 1 Likelihood
Profiles}\label{model-1-likelihood-profiles}

\subsubsection{Model 1 Harvest Control Rules (CPS
only)}\label{model-1-harvest-control-rules-cps-only}

\subsubsection{Model 1 Reference Points (groundfish
only)}\label{model-1-reference-points-groundfish-only}

Intro sentence or two\ldots{}.(Table \ref{tab:Timeseries_mod1}).

Equilibrium yield at the proxy \(F_{MSY}\) harvest rate corresponding to
\(SPR_{50\%}\) is 869.6 mt. Table \ref{tab:Ref_pts_mod1} shows the full
suite of estimated reference points for the northern area model and
Figure \ref{fig:Yield_all} shows the equilibrium yield curve.

\subsection{Model 2}\label{model-2}

\subsubsection{Model 2 Base Case
Results}\label{model-2-base-case-results}

\subsubsection{Model 2 Uncertainty and Sensitivity
Analyses}\label{model-2-uncertainty-and-sensitivity-analyses}

\subsubsection{Model 2 Retrospective
Analysis}\label{model-2-retrospective-analysis}

\subsubsection{Model 2 Likelihood
Profiles}\label{model-2-likelihood-profiles}

\subsubsection{Model 2 Harvest Control Rules (CPS
only)}\label{model-2-harvest-control-rules-cps-only}

\subsubsection{Model 2 Reference Points (groundfish
only)}\label{model-2-reference-points-groundfish-only}

\subsection{Model 3}\label{model-3}

\subsubsection{Model 3 Base Case
Results}\label{model-3-base-case-results}

\subsubsection{Model 3 Uncertainty and Sensitivity
Analyses}\label{model-3-uncertainty-and-sensitivity-analyses}

\subsubsection{Model 3 Retrospective
Analysis}\label{model-3-retrospective-analysis}

\subsubsection{Model 3 Likelihood
profiles}\label{model-3-likelihood-profiles}

\subsubsection{Model 3 Harvest Control Rules (CPS
only)}\label{model-3-harvest-control-rules-cps-only}

\subsubsection{Model 3 Reference Points (groundfish
only)}\label{model-3-reference-points-groundfish-only}

\section{Harvest Projections and Decision
Tables}\label{harvest-projections-and-decision-tables}

Table \ref{tab:mnmgt_perform}

\textbf{Model 1 Projections and Decision Table (groundfish only)} (Table
\ref{tab:Forecast_mod1}

Table \ref{tab:Decision_table_mod1}

\textbf{Model 2 Projections and Decision Table (groundfish only)}

\textbf{Model 3 Projections and Decision Table (groundfish only)}

\section{Regional Management
Considerations}\label{regional-management-considerations}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  For stocks where current practice is to allocate harvests by
  management area, a recommended method of allocating harvests based on
  the distribution of biomass should be provided. The MT advisor should
  be consulted on the appropriate management areas for each stock.
\item
  Discuss whether a regional management approach makes sense for the
  species from a biological perspective.
\item
  If there are insufficient data to analyze a regional management
  approach, what are the research and data needs to answer this
  question?
\end{enumerate}

\section{Research Needs}\label{research-needs}

\begin{enumerate}

\item Research need No. 1

\item Research need No. 2

\item Research need No. 3

\item etc.

\end{enumerate}

\section{Acknowledgments}\label{acknowledgments}

Include: STAR panel members and affiliations as well as names and
affiliations of persons who contributed data, advice or information but
were not part of the assessment team. Not required in draft assessment
undergoing review.

\newpage

\FloatBarrier

\section{Tables}\label{tables}

\FloatBarrier

\FloatBarrier

\begin{landscape}
\begin{longtable}{rlrrcccl}
\caption{List of parameters used in
                                              the base model, including estimated 
                                              values and standard deviations (SD), 
                                              bounds (minimum and maximum), 
                                              estimation phase (negative values indicate
                                              not estimated), status (indicates if 
                                              parameters are near bounds, and prior type
                                              information (mean, SD).} \\ 
  \hline
No. & Parameter & Value & Phase & Bounds & Status & SD & Prior (Exp.Val, SD)  \\ 
  \hline 
\endhead 
\hline 
\multicolumn{3}{l}{\footnotesize Continued on next page} 
\endfoot 
\endlastfoot 
 \hline
1 & NatM\_p\_1\_Fem\_GP\_1 & 0.050 & -2 & (0.02, 0.1) &  &  & None \\ 
  2 & L\_at\_Amin\_Fem\_GP\_1 & 21.211 & -3 & (15, 25) &  &  & None \\ 
  3 & L\_at\_Amax\_Fem\_GP\_1 & 41.983 & -2 & (35, 45) &  &  & None \\ 
  4 & VonBert\_K\_Fem\_GP\_1 & 0.159 & -3 & (0.1, 0.4) &  &  & None \\ 
  5 & CV\_young\_Fem\_GP\_1 & 0.072 & -5 & (0.03, 0.16) &  &  & None \\ 
  6 & CV\_old\_Fem\_GP\_1 & 0.064 & -5 & (0.03, 0.16) &  &  & None \\ 
  7 & Wtlen\_1\_Fem & 0.000 & -50 & (0, 3) &  &  & None \\ 
  8 & Wtlen\_2\_Fem & 3.080 & -50 & (2, 4) &  &  & None \\ 
  9 & Mat50\%\_Fem & 8.000 & -50 & (2, 12) &  &  & None \\ 
  10 & Mat\_slope\_Fem & -2.000 & -50 & (-2, 4) &  &  & None \\ 
  11 & Eggs\_scalar\_Fem & 1.086 & -50 & (0, 6) &  &  & None \\ 
  12 & Eggs\_exp\_wt\_Fem & 1.440 & -50 & (-3, 3) &  &  & None \\ 
  13 & NatM\_p\_1\_Mal\_GP\_1 & 0.028 & 2 & (-1, 1) & OK & 0.020 & Normal (0.05, 0.1) \\ 
  14 & L\_at\_Amin\_Mal\_GP\_1 & 0.000 & -2 & (-1, 1) &  &  & None \\ 
  15 & L\_at\_Amax\_Mal\_GP\_1 & -0.059 & -2 & (-1, 1) &  &  & None \\ 
  16 & VonBert\_K\_Mal\_GP\_1 & 0.195 & -2 & (-1, 1) &  &  & None \\ 
  17 & CV\_young\_Mal\_GP\_1 & 0.049 & -2 & (-1, 1) &  &  & None \\ 
  18 & CV\_old\_Mal\_GP\_1 & -0.189 & -2 & (-1, 1) &  &  & None \\ 
  19 & Wtlen\_1\_Mal & 0.000 & -50 & (0, 3) &  &  & None \\ 
  20 & Wtlen\_2\_Mal & 3.000 & -50 & (2, 4) &  &  & None \\ 
  24 & CohortGrowDev & 1.000 & -50 & (0, 2) &  &  & None \\ 
  25 & FracFemale\_GP\_1 & 0.500 & -99 & (0.000001, 0.999999) &  &  & None \\ 
  26 & SR\_LN(R0) & 9.148 & 1 & (5, 20) & OK & 0.093 & None \\ 
  27 & SR\_BH\_steep & 0.400 & -3 & (0.2, 1) &  &  & None \\ 
  28 & SR\_sigmaR & 0.700 & -6 & (0.5, 1.2) &  &  & None \\ 
  29 & SR\_regime & 0.000 & -50 & (-5, 5) &  &  & None \\ 
  30 & SR\_autocorr & 0.000 & -50 & (0, 2) &  &  & None \\ 
  31 & Early\_InitAge\_8 & -0.041 & 3 & (-6, 6) & act & 0.684 & dev (NA, NA) \\ 
  32 & Early\_InitAge\_7 & -0.043 & 3 & (-6, 6) & act & 0.683 & dev (NA, NA) \\ 
  33 & Early\_InitAge\_6 & -0.043 & 3 & (-6, 6) & act & 0.683 & dev (NA, NA) \\ 
  34 & Early\_InitAge\_5 & -0.042 & 3 & (-6, 6) & act & 0.683 & dev (NA, NA) \\ 
  35 & Early\_InitAge\_4 & -0.038 & 3 & (-6, 6) & act & 0.684 & dev (NA, NA) \\ 
  36 & Early\_InitAge\_3 & -0.033 & 3 & (-6, 6) & act & 0.685 & dev (NA, NA) \\ 
  37 & Early\_InitAge\_2 & -0.027 & 3 & (-6, 6) & act & 0.685 & dev (NA, NA) \\ 
  38 & Early\_InitAge\_1 & -0.025 & 3 & (-6, 6) & act & 0.685 & dev (NA, NA) \\ 
  134 & LnQ\_base\_Fishery(1) & -12.158 & -1 & (-15, 15) &  &  & None \\ 
  135 & LnQ\_base\_POP(2) & -0.218 & -1 & (-15, 15) &  &  & None \\ 
  136 & LnQ\_base\_EarlyTriennial(3) & -1.427 & -1 & (-15, 15) &  &  & None \\ 
  137 & LnQ\_base\_LateTriennial(4) & -1.714 & -1 & (-15, 15) &  &  & None \\ 
  138 & LnQ\_base\_AFSCSlope(5) & -1.329 & -1 & (-15, 15) &  &  & None \\ 
  139 & LnQ\_base\_NWFSCSlope(6) & -1.787 & -1 & (-15, 15) &  &  & None \\ 
  140 & LnQ\_base\_NWFSCcombo(7) & -0.749 & -1 & (-15, 15) &  &  & None \\ 
  141 & SizeSel\_P1\_Fishery(1) & 36.604 & 2 & (20, 45) & OK & 0.319 & None \\ 
  142 & SizeSel\_P2\_Fishery(1) & -5.000 & -2 & (-6, 4) &  &  & None \\ 
  143 & SizeSel\_P3\_Fishery(1) & 3.256 & 3 & (-1, 9) & OK & 0.147 & None \\ 
  144 & SizeSel\_P4\_Fishery(1) & 0.644 & 3 & (-1, 9) & OK & 0.714 & None \\ 
  145 & SizeSel\_P5\_Fishery(1) & -2.734 & 4 & (-5, 9) & OK & 0.244 & None \\ 
  146 & SizeSel\_P6\_Fishery(1) & 0.993 & 2 & (-5, 9) & OK & 0.169 & None \\ 
  147 & Retain\_P1\_Fishery(1) & 30.937 & 1 & (15, 45) & OK & 0.285 & None \\ 
  148 & Retain\_P2\_Fishery(1) & 1.876 & 1 & (0.1, 10) & OK & 0.217 & None \\ 
  149 & Retain\_P3\_Fishery(1) & 0.681 & 1 & (0.001, 1) & OK & 0.030 & None \\ 
  150 & Retain\_P4\_Fishery(1) & 0.000 & -3 & (0, 0) &  &  & None \\ 
  151 & SizeSel\_P1\_POP(2) & 22.997 & 2 & (20, 70) & OK & 1.018 & None \\ 
  152 & SizeSel\_P2\_POP(2) & 9.304 & 3 & (0.001, 50) & OK & 1.805 & None \\ 
  153 & SizeSel\_P1\_EarlyTriennial(3) & 20.332 & 2 & (18, 70) & OK & 0.666 & None \\ 
  154 & SizeSel\_P2\_EarlyTriennial(3) & 5.424 & 3 & (0.001, 50) & OK & 1.438 & None \\ 
  155 & SizeSel\_P1\_NWFSCcombo(7) & 25.783 & 2 & (20, 70) & OK & 2.693 & None \\ 
  156 & SizeSel\_P2\_NWFSCcombo(7) & 17.243 & 3 & (0.001, 50) & OK & 4.202 & None \\ 
  157 & Retain\_P3\_Fishery(1)\_BLK1repl\_1940 & 0.999 & -1 & (0.001, 1) &  &  & Normal (0.9, 99) \\ 
  158 & Retain\_P3\_Fishery(1)\_BLK1repl\_1982 & 0.980 & -1 & (0.001, 1) &  &  & Normal (0.9, 99) \\ 
  159 & Retain\_P3\_Fishery(1)\_BLK1repl\_1989 & 0.964 & 1 & (0.001, 1) & OK & 0.034 & Normal (0.88, 99) \\ 
  160 & Retain\_P3\_Fishery(1)\_BLK1repl\_1995 & 0.906 & 1 & (0.001, 1) & OK & 0.011 & Normal (0.82, 99) \\ 
  161 & Retain\_P3\_Fishery(1)\_BLK1repl\_2009 & 0.497 & 1 & (0.001, 1) & OK & 0.041 & Normal (0.65, 99) \\ 
   \hline
\hline
\label{tab:model_params}
\end{longtable}
\end{landscape}

\newpage

\begin{table}[ht]
\centering
\caption{Summary of the biomass/abundance
                                              time series used in the stock
                                              assessment.} 
\label{tab:Index_summary}
\begin{tabular}{>{\centering}p{.4in}>{\centering}p{.3in}>{\centering}p{.3in}>{\centering}p{.3in}>{\centering}p{.6in}>{\centering}p{.5in}>{\centering}p{.8in}>{\centering}p{.8in}>{\centering}p{.5in}}
  \hline
Region & ID & Fleet & Years & Name & Fishery ind. & Filtering & Method & Endorsed \\ 
  \hline
WA & 1 & 4 & 1981-2014 & Dockside CPUE & No & trip, area, month, Stephens-MacCall & delta-GLM (bin-gamma) & SSC \\ 
  - & - & - & - & - & - & - & - & - \\ 
  - & - & - & - & - & - & - & - & - \\ 
  - & - & - & - & - & - & - & - & - \\ 
   \hline
\end{tabular}
\end{table}

\newpage

\begin{table}[ht]
\centering
\caption{Results from 100 jitters from each of 
                                      the three models.} 
\label{tab:jitter}
\begin{tabular}{llll}
  \hline
Status & Model.1 & Model.2 & Model.3 \\ 
  \hline
Returned to base case & - & - & - \\ 
  Found local minimum & - & - & - \\ 
  Found better solution & - & - & - \\ 
  Error in likelihood & - & - & - \\ 
  Total & 100 & 100 & 100 \\ 
   \hline
\end{tabular}
\end{table}

\FloatBarrier

\newpage

\begin{sidewaystable}[ht]
\centering
\caption{Sensitivity of the base model 
                                          to dropping or down-weighting data 
                                          sources and alternative assumptions 
                                          about growth.} 
\label{tab:Sensitivity_model1}
\scalebox{0.9}{
\begin{tabular}{l>{\centering}p{.6in}>{\centering}p{.6in}>{\centering}p{.6in}>{\centering}p{.6in}>{\centering}p{.6in}>{\centering}p{.6in}>{\centering}p{.6in}>{\centering}p{.6in}}
  \hline
Label & Base (Francis weights) & Harmonic mean weights & Drop index & Drop ages & Down-weight lengths & Free size Age0 & Free CV Amin & External growth \\ 
  \hline
TOTAL\_like & - & - & - & - & - & - & - & - \\ 
  Catch\_like & - & - & - & - & - & - & - & - \\ 
  Equil\_catch\_like & - & - & - & - & - & - & - & - \\ 
  Survey\_like & - & - & - & - & - & - & - & - \\ 
  Length\_comp\_like & - & - & - & - & - & - & - & - \\ 
  Age\_comp\_like & - & - & - & - & - & - & - & - \\ 
  Parm\_priors\_like & - & - & - & - & - & - & - & - \\ 
  SSB\_Unfished\_thousand\_mt & - & - & - & - & - & - & - & - \\ 
  TotBio\_Unfished & - & - & - & - & - & - & - & - \\ 
  SmryBio\_Unfished & - & - & - & - & - & - & - & - \\ 
  Recr\_Unfished\_billions & - & - & - & - & - & - & - & - \\ 
  SSB\_Btgt\_thousand\_mt & - & - & - & - & - & - & - & - \\ 
  SPR\_Btgt & - & - & - & - & - & - & - & - \\ 
  Fstd\_Btgt & - & - & - & - & - & - & - & - \\ 
  TotYield\_Btgt\_thousand\_mt & - & - & - & - & - & - & - & - \\ 
  SSB\_SPRtgt\_thousand\_mt & - & - & - & - & - & - & - & - \\ 
  Fstd\_SPRtgt & - & - & - & - & - & - & - & - \\ 
  TotYield\_SPRtgt\_thousand\_mt & - & - & - & - & - & - & - & - \\ 
  SSB\_MSY\_thousand\_mt & - & - & - & - & - & - & - & - \\ 
  SPR\_MSY & - & - & - & - & - & - & - & - \\ 
  Fstd\_MSY & - & - & - & - & - & - & - & - \\ 
  TotYield\_MSY\_thousand\_mt & - & - & - & - & - & - & - & - \\ 
  RetYield\_MSY & - & - & - & - & - & - & - & - \\ 
  Bratio\_2015 & - & - & - & - & - & - & - & - \\ 
  F\_2015 & - & - & - & - & - & - & - & - \\ 
  SPRratio\_2015 & - & - & - & - & - & - & - & - \\ 
  Recr\_2015 & - & - & - & - & - & - & - & - \\ 
  Recr\_Virgin\_billions & - & - & - & - & - & - & - & - \\ 
  L\_at\_Amin\_Fem\_GP\_1 & - & - & - & - & - & - & - & - \\ 
  L\_at\_Amax\_Fem\_GP\_1 & - & - & - & - & - & - & - & - \\ 
  VonBert\_K\_Fem\_GP\_1 & - & - & - & - & - & - & - & - \\ 
  CV\_young\_Fem\_GP\_1 & - & - & - & - & - & - & - & - \\ 
  CV\_old\_Fem\_GP\_1 & - & - & - & - & - & - & - & - \\ 
   \hline
\end{tabular}
}
\end{sidewaystable}

\newpage

\begin{longtable}{c>{\centering}p{.6in}>{\centering}p{.6in}>{\centering}p{.6in}>{\centering}p{.6in}>{\centering}p{.8in}>{\centering}p{.8in}c}
\caption{Time-series of population estimates 
                                        from the base-case model.} \\ 
  \hline
Year & Total biomass (mt) & Spawning biomass (mt) & Depletion & Age-0 recruits & Total catch (mt) & Relative exploitation rate & SPR \\ 
  \hline \endhead  \hline
1940 & 121094 & 65941 & 0.00 & 9163 & 13 & 0.00 & 1.00 \\ 
  1941 & 120951 & 65876 & 1.00 & 9117 & 19 & 0.00 & 1.00 \\ 
  1942 & 120618 & 65804 & 1.00 & 9048 & 33 & 0.00 & 0.99 \\ 
  1943 & 118701 & 65728 & 1.00 & 9002 & 119 & 0.00 & 0.97 \\ 
  1944 & 116740 & 65610 & 0.99 & 9020 & 208 & 0.00 & 0.96 \\ 
  1945 & 114457 & 65444 & 0.99 & 9177 & 316 & 0.00 & 0.93 \\ 
  1946 & 115838 & 65217 & 0.99 & 9526 & 249 & 0.00 & 0.95 \\ 
  1947 & 116629 & 65026 & 0.98 & 10139 & 212 & 0.00 & 0.96 \\ 
  1948 & 116301 & 64853 & 0.98 & 11035 & 226 & 0.00 & 0.95 \\ 
  1949 & 108799 & 64671 & 0.98 & 12065 & 594 & 0.01 & 0.88 \\ 
  1950 & 103740 & 64288 & 0.97 & 13081 & 865 & 0.01 & 0.83 \\ 
  1951 & 100348 & 63770 & 0.97 & 14517 & 1056 & 0.01 & 0.80 \\ 
  1952 & 81069 & 63184 & 0.96 & 16205 & 2441 & 0.02 & 0.62 \\ 
  1953 & 88712 & 61895 & 0.94 & 15215 & 1786 & 0.02 & 0.69 \\ 
  1954 & 78636 & 61083 & 0.92 & 12637 & 2583 & 0.02 & 0.60 \\ 
  1955 & 85279 & 59968 & 0.91 & 10551 & 1995 & 0.02 & 0.66 \\ 
  1956 & 71270 & 59359 & 0.90 & 9200 & 3248 & 0.03 & 0.53 \\ 
  1957 & 75500 & 58272 & 0.88 & 8109 & 2784 & 0.02 & 0.57 \\ 
  1958 & 82301 & 57652 & 0.87 & 7088 & 2182 & 0.02 & 0.63 \\ 
  1959 & 93523 & 57502 & 0.87 & 6761 & 1390 & 0.01 & 0.74 \\ 
  1960 & 80561 & 57804 & 0.88 & 8371 & 2364 & 0.02 & 0.62 \\ 
  1961 & 70426 & 57475 & 0.87 & 13917 & 3338 & 0.03 & 0.52 \\ 
  1962 & 61240 & 56439 & 0.85 & 11506 & 4416 & 0.04 & 0.44 \\ 
  1963 & 51452 & 54635 & 0.83 & 7380 & 5851 & 0.06 & 0.35 \\ 
  1964 & 48022 & 51925 & 0.79 & 6306 & 6212 & 0.06 & 0.32 \\ 
  1965 & 39475 & 48976 & 0.74 & 5558 & 7851 & 0.08 & 0.24 \\ 
  1966 & 18667 & 45228 & 0.68 & 4247 & 19711 & 0.23 & 0.08 \\ 
  1967 & 18585 & 35149 & 0.53 & 3542 & 15293 & 0.22 & 0.08 \\ 
  1968 & 21824 & 27621 & 0.42 & 3910 & 9720 & 0.18 & 0.10 \\ 
  1969 & 56543 & 23201 & 0.35 & 6089 & 2083 & 0.05 & 0.39 \\ 
  1970 & 50739 & 22869 & 0.35 & 10718 & 2502 & 0.06 & 0.34 \\ 
  1971 & 53819 & 22157 & 0.34 & 4937 & 2218 & 0.05 & 0.37 \\ 
  1972 & 54015 & 21441 & 0.32 & 2601 & 2155 & 0.05 & 0.37 \\ 
  1973 & 42863 & 20678 & 0.31 & 1949 & 3034 & 0.07 & 0.27 \\ 
  1974 & 45463 & 19489 & 0.30 & 2415 & 2617 & 0.07 & 0.30 \\ 
  1975 & 61399 & 18691 & 0.28 & 2984 & 1490 & 0.04 & 0.44 \\ 
  1976 & 53541 & 18635 & 0.28 & 2470 & 1903 & 0.05 & 0.37 \\ 
  1977 & 54439 & 18405 & 0.28 & 3102 & 1823 & 0.05 & 0.38 \\ 
  1978 & 44605 & 18101 & 0.27 & 3377 & 2479 & 0.07 & 0.29 \\ 
  1979 & 49568 & 17228 & 0.26 & 3914 & 1998 & 0.06 & 0.33 \\ 
  1980 & 44855 & 16404 & 0.25 & 3145 & 2232 & 0.07 & 0.29 \\ 
  1981 & 55641 & 15362 & 0.23 & 6489 & 1467 & 0.05 & 0.39 \\ 
  1982 & 61546 & 14760 & 0.22 & 2561 & 1164 & 0.04 & 0.44 \\ 
  1983 & 47884 & 14420 & 0.22 & 2867 & 1751 & 0.06 & 0.32 \\ 
  1984 & 45929 & 13832 & 0.21 & 4153 & 1774 & 0.07 & 0.30 \\ 
  1985 & 47427 & 13236 & 0.20 & 4454 & 1605 & 0.06 & 0.31 \\ 
  1986 & 47243 & 12744 & 0.19 & 1785 & 1555 & 0.06 & 0.31 \\ 
  1987 & 53771 & 12276 & 0.19 & 3058 & 1219 & 0.05 & 0.37 \\ 
  1988 & 46397 & 12010 & 0.18 & 3522 & 1535 & 0.06 & 0.30 \\ 
  1989 & 44471 & 11584 & 0.18 & 4262 & 1596 & 0.07 & 0.29 \\ 
  1990 & 51835 & 11136 & 0.17 & 3654 & 1210 & 0.05 & 0.35 \\ 
  1991 & 43358 & 10874 & 0.16 & 4168 & 1584 & 0.07 & 0.28 \\ 
  1992 & 43023 & 10425 & 0.16 & 959 & 1546 & 0.07 & 0.27 \\ 
  1993 & 44868 & 10005 & 0.15 & 1724 & 1396 & 0.07 & 0.29 \\ 
  1994 & 49351 & 9684 & 0.15 & 4242 & 1164 & 0.06 & 0.33 \\ 
  1995 & 53484 & 9494 & 0.14 & 2936 & 1002 & 0.05 & 0.37 \\ 
  1996 & 55873 & 9436 & 0.14 & 1409 & 925 & 0.05 & 0.39 \\ 
  1997 & 62237 & 9410 & 0.14 & 1471 & 757 & 0.04 & 0.45 \\ 
  1998 & 62623 & 9425 & 0.14 & 2536 & 750 & 0.04 & 0.45 \\ 
  1999 & 69541 & 9390 & 0.14 & 6552 & 599 & 0.03 & 0.51 \\ 
  2000 & 102150 & 9407 & 0.14 & 7108 & 156 & 0.01 & 0.82 \\ 
  2001 & 88741 & 9641 & 0.15 & 3168 & 310 & 0.02 & 0.69 \\ 
  2002 & 100848 & 9812 & 0.15 & 2030 & 176 & 0.01 & 0.81 \\ 
  2003 & 103009 & 10044 & 0.15 & 820 & 157 & 0.01 & 0.83 \\ 
  2004 & 104707 & 10330 & 0.16 & 2983 & 144 & 0.01 & 0.84 \\ 
  2005 & 112320 & 10706 & 0.16 & 2055 & 76 & 0.00 & 0.91 \\ 
  2006 & 111721 & 11220 & 0.17 & 1270 & 86 & 0.00 & 0.91 \\ 
  2007 & 105501 & 11802 & 0.18 & 1210 & 156 & 0.01 & 0.85 \\ 
  2008 & 107972 & 12291 & 0.19 & 10906 & 134 & 0.01 & 0.87 \\ 
  2009 & 102652 & 12632 & 0.19 & 2753 & 202 & 0.01 & 0.82 \\ 
  2010 & 107903 & 12769 & 0.19 & 3664 & 141 & 0.01 & 0.87 \\ 
  2011 & 104764 & 12852 & 0.19 & 3683 &  &  &  \\ 
   \hline
\hline
\label{tab:Timeseries_mod1}
\end{longtable}

\FloatBarrier

\newpage

\begin{table}[ht]
\centering
\caption{Projection of potential
                                        OFL, spawning biomass, and depletion for the
                                        base case model.} 
\label{tab:Forecast_mod1}
\begin{tabular}{c>{\centering}p{1in}>{\centering}p{1in}>{\centering}p{1in}>{\centering}p{1in}>{\centering}p{1in}}
  \hline
Year & OFL contriubtion (mt) & ACL landings (mt) & Age 5+ biomass (mt) & Spawning Biomass (mt) & Depletion \\ 
  \hline
2011 & 857.65 & 116.44 & 26104.00 & 12852.40 & 0.19 \\ 
  2012 & 859.55 & 118.36 & 26677.40 & 12943.50 & 0.20 \\ 
  2013 & 865.17 & 372.19 & 27334.20 & 13234.70 & 0.20 \\ 
  2014 & 868.10 & 376.93 & 27609.90 & 13438.40 & 0.20 \\ 
  2015 & 881.24 & 388.84 & 27882.80 & 13708.40 & 0.21 \\ 
  2016 & 897.89 & 402.20 & 28141.40 & 13934.10 & 0.21 \\ 
  2017 & 912.69 & 413.65 & 28380.20 & 14099.20 & 0.21 \\ 
  2018 & 923.94 & 420.72 & 28603.10 & 14155.60 & 0.21 \\ 
  2019 & 932.33 & 425.19 & 28817.30 & 14167.00 & 0.21 \\ 
  2020 & 939.09 & 428.86 & 29026.90 & 14181.50 & 0.21 \\ 
  2021 & 945.15 & 434.57 & 29231.90 & 14289.40 & 0.22 \\ 
  2022 & 950.93 & 441.23 & 29427.80 & 14441.60 & 0.22 \\ 
   \hline
\end{tabular}
\end{table}

\FloatBarrier

\FloatBarrier

\newpage

\section{Figures}\label{figures}

\begin{figure}
\centering
\includegraphics{Figures/boundary_map.png}
\caption{Map showing the state boundary lines for management of the
recreational fishing fleets. CRFS Districts 1-6 in California are
presented as well as the WDFW Recreational Management Areas in
Washington. Florence, OR is shown as a potential location of model
stratification. \label{fig:boundary_map}}
\end{figure}

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/data_plot.png}
\caption{Summary of data sources used in the Base model.
\label{fig:data_plot}}
\end{figure}

\FloatBarrier

\FloatBarrier

\FloatBarrier

\FloatBarrier

\FloatBarrier

\FloatBarrier

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_flt1mkt1.png}
\caption{length comps, discard, Fishery
\label{fig:mod1_1_comp_lenfit_flt1mkt1}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_residsflt1mkt1.png}
\caption{Pearson residuals, discard, Fishery (max=6.56)\\
Closed bubbles are positive residuals (observed \textgreater{} expected)
and open bubbles are negative residuals (observed \textless{} expected).
\label{fig:mod1_2_comp_lenfit_residsflt1mkt1}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_sampsize_flt1mkt1.png}
\caption{N\_EffN comparison, length comps, discard, Fishery
\label{fig:mod1_3_comp_lenfit_sampsize_flt1mkt1}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_data_weighting_TA1.8_Fishery.png}
\caption{Francis data weighting method TA1.8 Fishery Suggested sample
size adjustment (with 95\% interval) for len data from Fishery: 0.2505
(0.1591\_0.5781)
\label{fig:mod1_4_comp_lenfit_data_weighting_TA1.8_Fishery}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_flt1mkt2.png}
\caption{length comps, retained, Fishery
\label{fig:mod1_5_comp_lenfit_flt1mkt2}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_residsflt1mkt2.png}
\caption{Pearson residuals, retained, Fishery (max=6.36)\\
Closed bubbles are positive residuals (observed \textgreater{} expected)
and open bubbles are negative residuals (observed \textless{} expected).
\label{fig:mod1_6_comp_lenfit_residsflt1mkt2}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_sampsize_flt1mkt2.png}
\caption{N\_EffN comparison, length comps, retained, Fishery
\label{fig:mod1_7_comp_lenfit_sampsize_flt1mkt2}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_data_weighting_TA1.8_Fishery.png}
\caption{Francis data weighting method TA1.8 Fishery Suggested sample
size adjustment (with 95\% interval) for len data from Fishery: 0.2505
(0.1568\_0.6379)
\label{fig:mod1_8_comp_lenfit_data_weighting_TA1.8_Fishery}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_flt2mkt0.png}
\caption{length comps, whole catch, POP
\label{fig:mod1_9_comp_lenfit_flt2mkt0}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_residsflt2mkt0.png}
\caption{Pearson residuals, whole catch, POP (max=3.32)\\
Closed bubbles are positive residuals (observed \textgreater{} expected)
and open bubbles are negative residuals (observed \textless{} expected).
\label{fig:mod1_10_comp_lenfit_residsflt2mkt0}}
\end{figure}

\FloatBarrier

\FloatBarrier

\FloatBarrier

\FloatBarrier

\FloatBarrier

\FloatBarrier

\FloatBarrier
<!-- ***********MODEL 2 REFERENCE POINTS FIGURES  -- IF NEEDED ************ -->

\newpage

\color{black}

\section*{References}\label{references}
\addcontentsline{toc}{section}{References}

\renewcommand{\thepage}{}

\hypertarget{refs}{}
\hypertarget{ref-Alverson1964}{}
Alverson, D.L., Pruter, a T., and Ronholt, L.L. 1964. A Study of
Demersal Fishes and Fisheries of the Northeastern Pacific Ocean.
Institute of Fisheries, University of British Columbia.

\hypertarget{ref-vonB1938}{}
Bertalanffy, L. von. 1938. A quantitative theory of organic growth.
Human Biology \textbf{10}: 181--213.

\hypertarget{ref-Dick2009}{}
Dick, E. 2009. Modeling the reproductive potential of rockfishes
(\emph{Sebastes} spp.). PhD Dissertation, University of California Santa
Cruz.

\hypertarget{ref-Francis2011}{}
Francis, R. 2011. Data weighting in statistical fisheries stock
assessment models. Canadian Journal of Fisheries and Aquatic Sciencies
\textbf{68}: 1124--1138.

\hypertarget{ref-Hamel2015}{}
Hamel, O. 2015. A method for calculating a meta-analytical prior for the
natural mortality rate using multiple life history correlates. ICES
Journal of Marine Science \textbf{72}: 62--69.

\hypertarget{ref-Harry1961}{}
Harry, G., and Morgan, A. 1961. History of the trawl fishery, 1884-1961.
Oregon Fish Commission Research Briefs \textbf{19}: 5--26.

\hypertarget{ref-Love2002}{}
Love, M., Yoklavich, M., and Thorsteinson, L. 2002. The rockfishes of
the northeast Pacific. University of California Press, Berkeley, CA,
USA.

\hypertarget{ref-McAllister1997}{}
McAllister, M.K., and Ianelli, J.N. 1997. Bayesian stock assessment
using catch-age data and the sampling - importance resampling algorithm.
Canadian Journal of Fisheries and Aquatic Sciences \textbf{54}(2):
284--300.

\hypertarget{ref-Methot2015}{}
Methot, R.D. 2015. User manual for Stock Synthesis model version 3.24s.
NOAA Fisheries, US Department of Commerce.

\hypertarget{ref-Miller1965}{}
Miller, D., and Gotshall, D. 1965. Ocean sportfish catch and effort from
Oregon to Point Arguello, California July 1, 1957-June 30, 1961. State
of California, The Resources Agency Department of Fish and Game, Fish
Bulletin \textbf{130}.

\hypertarget{ref-Pikitch1988}{}
Pikitch, E., Erickson, D., and Wallace, J. 1988. An evaluation of the
effectiveness of trip limits as a management tool. Northwest and Alaska
Fisheries Center, National Marine Fisheries Service, US Department of
Commerce.

\hypertarget{ref-Rogers1992}{}
Rogers, J., and Pikitch, E. 1992. Numerical definition of groundfish
assemblages caught off the coasts of Oregon and Washington using
commercial fishing strategies. Canadian Journal of Fisheries and and
Aquatic Sciences \textbf{49}: 2648--2656.

\end{document}
