\documentclass[12pt,]{article}
%\usepackage{lmodern}  Melissa removed to deal with font rendering issue
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript

%Melissa removed the following section to deal with font rendering issue
%\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
%  \usepackage[T1]{fontenc}
%  \usepackage[utf8]{inputenc}
%%\else % if luatex or xelatex
%  \ifxetex
%    \usepackage{mathspec}
%  \else
%    \usepackage{fontspec}
%  \fi
%  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
%  \newcommand{\euro}{€}
%%%%%%\fi

% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\PassOptionsToPackage{usenames,dvipsnames}{color} % color is loaded by hyperref
\hypersetup{unicode=true,
            pdftitle={Status of Pacific ocean perch (Sebastes alutus) along the US west coast in 2017},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}
  \title{Status of Pacific ocean perch (\emph{Sebastes alutus}) along the US west
coast in 2017}
  \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
  \author{}
  \preauthor{}\postauthor{}
  \date{}
  \predate{}\postdate{}


% This file contains all of the LaTeX packages you may need to compile the document
% Documentation for each package can be found onlines
\usepackage{tabularx}                                             % table environment providing flexibility
\usepackage{caption}                                              % for creating captions  
\usepackage{longtable}                                            % allows tables to span multiple pages
\usepackage{tabu}
\usepackage{rotating}                                             % allows for sideways tables
%\usepackage{float}                                                % floating environments; may not need in rmarkdown
\usepackage{placeins}                                             % keeps floats from moving
\usepackage{floatrow}                                             % package to put table captions at the top
\floatsetup[table]{capposition = top}                             % line to put captions at the top of pander tables
\usepackage{indentfirst}                                          % indents first paragraph of a section
\usepackage{mdwtab}                                               % continued float multi-page figure
\usepackage{enumerate}                                            % create lists
\usepackage{hyperref}                                             % highlight cross references
\hypersetup{colorlinks=true, urlcolor=blue, linktoc=page, linkcolor=blue, citecolor=blue} %define referencing colors
%\usepackage{makebox}                                             % make boxes around text
\usepackage[usenames,dvipsnames]{xcolor}                          % color name options
%\usepackage[space]{grffile}                                      % spaces in file name path
\usepackage{soul}                                                 % highlight text
\usepackage{enumitem}                                             % numbered lists
\usepackage{lineno}                                               % Line numbers; comment out for final
\usepackage{upquote}                                              % produce grave accent in latex
\usepackage{verbatim}                                             % produces verbatim results
\usepackage{fancyvrb}                                             % verbatim in a box
%\usepackage{draftwatermark}                                      % places Draft watermark in background; comment out for final
\usepackage{textcomp}                                             % fixes error with packages interfering
\usepackage{lscape}                                               % rotate pages - to allow for landscape longtables
%\pdfinterwordspaceon                                             % fix loss of inter word spacing
\usepackage{cmap}                                                 % fix mapping characters to unicode
\RequirePackage[linewidth = 1]{pdfcomment}                        % pdf comments
\RequirePackage[l2tabu, orthodox]{nag}                            % checks packages related to the accessibility?
\usepackage[inline]{showlabels}                                   % show table and figure labels; comment out for final
%\RequirePackage[tagged]{accessibilityMeta}


\linenumbers                                                      % specify use of line numbers


\definecolor{light-gray}{gray}{.85}                               % define light-gray as a color
%\usepackage[tagged]{accessibility-meta}

 
%\showlabels[\color{mred}]{label}

% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

\begin{document}
\maketitle


\begin{center}
\thispagestyle{empty}


\vspace{.5cm}

\includegraphics{Sebastes_alutus}~\\[0.5cm]
%\pdftooltip{\includegraphics{Sebastes_alutus}}{This is a fish.}



Chantel R. Wetzel\textsuperscript{1}\\
Lee Cronin-Fine\textsuperscript{2}\\

\vspace{.5cm}

\small
\textsuperscript{1}Northwest Fisheries Science Center, U.S. Department of Commerce, National Oceanic and Atmospheric Administration, National Marine Fisheries Service, 2725 Montlake Boulevard East, Seattle, Washington 98112\\

\vspace{.3cm}

\textsuperscript{3}University of Washington, School of Aquatic and Fishery Sciences\\





\vspace{1cm}

\vfill
DRAFT SAFE\\
Disclaimer: This information is distributed solely for the purpose of pre-dissemination
peer review under applicable information quality guidelines. It has not been formally
disseminated by NOAA Fisheries. It does not represent and should not be construed to
represent any agency determination or policy. 

\vspace{.3cm}
%Bottom of the page
%{\large \today}

\maketitle

\pagenumbering{roman}
\setcounter{page}{1}
\end{center}

{
\setcounter{tocdepth}{4}
\tableofcontents
}
\setlength{\parskip}{5mm plus1mm minus1mm} \pagebreak

\pagenumbering{arabic} \setcounter{page}{1}
\renewcommand{\thefigure}{\alph{figure}}
‼\renewcommand{\thetable}{\alph{table}}

\section*{Executive Summary}\label{executive-summary}
\addcontentsline{toc}{section}{Executive Summary}

\subsection*{Stock}\label{stock}
\addcontentsline{toc}{subsection}{Stock}

This assessment reports the status of the Pacific ocean perch
(\emph{Sebastes alutus}) species off rockfish off the U.S. West Coast
from Northern California to the Canadian Border using data through 2017.
Pacific ocean perch are most abundant in the Gulf of Alaska and have
observed off of Japan, in the Bering Sea, and south to Baja California,
although they are sparse south of Oregon and rare in southern
California. Although catches north of the US-Canada border were not
included in this assessment, it is not certain the connectivity of these
populations with contribution to the biomass possibly through adult
migration and/or larval dispersion. Composition data indicate that good
recruitment years coincide in Oregon and Washington. To date, no
significant genetic differences have been found in the range covered by
this assessment.

\subsection*{Landings}\label{landings}
\addcontentsline{toc}{subsection}{Landings}

The first year that harvest of Pacific ocean perch exceeded 1 mt off the
US West Coast first occured in 1929. Catches ramped up in the 1940s with
large removals in Washington waters. During the 1950s the removals
primarly occured in Oregon waters with catches from Washington declining
following the 1940s. The largest removals in 1966-1968 were largely a
result of harvest by foreing vessels. The fishery proceed with more
moderate removals ranging between 1,200 to 2,600 metric tons per year
between 1969 to 1980. Removals generally decined from 1981 to 1994 to
between 1,000 and 1,700 metric tons per year. Pacific ocean perch was
declared overfished in 1999 resulting in large reduction in harvest in
recent years since the declaration. Since 2000, catches of Pacific ocean
perch have ranged between 269 - 60 mt, with catches in 2016 totaling 67
mt.

Pacific ocean perch are a desirable market species and discarding has
historically been low. However, management restrictions (e.g.~trip
limits) have resulted in increased discarding since the early 1990s.
During the 2000s discarding increased for Pacific ocean perch due to
harvest restrictions imposed to allow rebuilding, with estimated discard
rates from the bottom trawl fishery peaking in 2009 and 2010, prior to
implementation of catch shares in 2011. Since 2011, discarding of
Pacific ocean perch has been estimated to be less than 4\% given
observer data.

\begin{table}[ht]
\centering
\caption{Landings (mt) for the past 10 years for Pacific ocean perch by fleet.} 
\label{tab:Exec_catch}
\begin{tabular}{l>{\centering}p{0.7in}>{\centering}p{0.7in}>{\centering}p{0.7in}>{\centering}p{0.7in}>{\centering}p{0.7in}>{\centering}p{0.7in}}
  \hline
Year & California & Oregon & Washington & At-sea Hake & Research & Total Landings \\ 
  \hline
2007 & 0.15 & 83.65 & 45.12 & 4.05 & 0.58 & 133.55 \\ 
  2008 & 0.39 & 58.64 & 16.61 & 15.93 & 0.80 & 92.36 \\ 
  2009 & 0.92 & 58.74 & 33.22 & 1.56 & 2.72 & 97.17 \\ 
  2010 & 0.14 & 58.00 & 22.29 & 16.87 & 1.68 & 98.98 \\ 
  2011 & 0.12 & 30.26 & 19.66 & 9.17 & 1.94 & 61.14 \\ 
  2012 & 0.18 & 30.41 & 21.79 & 4.52 & 1.62 & 58.51 \\ 
  2013 & 0.08 & 34.86 & 14.83 & 5.41 & 1.71 & 56.89 \\ 
  2014 & 0.18 & 33.91 & 15.82 & 3.92 & 0.57 & 54.40 \\ 
  2015 & 0.12 & 38.05 & 11.41 & 8.71 & 1.59 & 59.88 \\ 
  2016 & 0.23 & 40.81 & 13.12 & 10.30 & 3.10 & 67.56 \\ 
   \hline
\end{tabular}
\end{table}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{PacificOceanPerch2017_Assessment_files/figure-latex/unnamed-chunk-11-1.pdf}
\caption{Landings of Pacific ocean perch for California, Oregon,
Washington, the Foriegn fishery (1966-1976), At-Sea Hake fishery, and
fishery independent surveys. \label{fig:Exec_catch1}}
\end{figure}

\FloatBarrier

\subsection*{Data and Assessment}\label{data-and-assessment}
\addcontentsline{toc}{subsection}{Data and Assessment}

This a new full assessment for Pacific ocean perch which was last
assessed in 2011. In this assessment, all aspects of the model including
catches, data, and modelling assumptions were re-evaluated as much as
possible. The assessment was conducted using the length- and
age-structured modeling software Stock Synthesis (version 3.30.30.05).
The coastwide population was modeled assuming separate growth and
mortality parameters for each sex (a two-sex model) from 1918 to 2017,
and forecasted beyond 2017.

All of the sources of data for Pacific ocean perch have been
re-evaluated for 2017, excluding the historical fishery catch-per-unit
time series. Changes of varying degrees have occurred in the data from
those used in previous assessments. These current data represent the
best available scientific information. The landings history has been
updated and extended back to 1918, harvest was negligible before that
year. Survey data from the Alaska and Northwest Fisheries Science
Centers have been used to construct series of indices using a spatial
temporal delta GLMM model as well as length, age and conditional age-at
length compositions consistent with the stratifications used for
constructing the indices.

The definition of fishing fleets have been changed from those in the
2011 assessment. Three fishing fleets were specified within the model:
1) a combined bottom trawl, mid-water trawl and fixed gear fleet where
only a small fraction of Pacific ocean perch occuring by fixed gear, 2)
the historical foreign fleet, and 3) the at-sea hake fishery. The fleet
grouping were based on discarding practices. The trawl fishery estimated
a retention curve based upon discarding data and known management
restrictions. However, very little if any discarding is assumed to have
occured by the foreign fleet and the catch reported by the at-sea hake
fishery accounts for both discarded and landed fish and hence, no
additional mortality was estimated for each of these fleets.

The assessment uses landings data and discard-fraction estimates;
catch-per-unit-of-effort and survey indices; length or age composition
data for each year and fishery or survey (with conditional age at length
compositional data for the NWFSC shelf-slope survey); information on
weight-at-age, maturity-at-age, and fecundity-at-age; priors on natural
mortality and the steepness of the Beverton-Holt stock-recruitment
relationship; and estimates of ageing error. Recruitment at
``equilibrium biomass'', length-based selectivity of the fishery and
surveys, retention of the fishery, catchability of the surveys, growth,
the time series of biomass, age and size structure, and current and
projected future stock status are outputs of the model. Natural
mortality and steepness were fixed in the final model. This was done due
to relatively flat likelihood surfaces, such that fixing parameters and
then varying them was deemed the best way to characterize uncertainty.

A number of sources of uncertainty are explicitly included in this
assessment. For example, allowance is made for uncertainty in survey
catchability coefficients. Furthermore, this assessment includes gender
differences in growth, a non-linear relationship between individual
spawner biomass and effective spawning output, and an updated
relationship between length and maturity, based upon non-published
information (M. Head, personal communication). As is always the case,
overall uncertainty is greater than that predicted by a single model
specification. Among other sources of uncertainty that are not included
in the current model are the degree of connectivity between the stocks
of Pacific ocean perch off of Vancouver Island, British Columbia and
those in PFMC waters, and the effect of climatic variables on
recruitment, growth and survival of Pacific ocean perch.

A reference case was selected which adequately captures the central
tendency for those sources of uncertainty considered in the model.

\FloatBarrier

\subsection*{Stock Biomass}\label{stock-biomass}
\addcontentsline{toc}{subsection}{Stock Biomass}

\hl{Include: trends and current levels relative to virgin or historic levels, 
description of uncertainty-include table for last 10 years and graph with 
long term estimates.}

Spawning output Figure: Figure \ref{fig:Spawnbio_all}\\
Spawning output Table(s): Table \ref{tab:SpawningDeplete_mod1}\\
Relative depletion Figure: Figure \ref{fig:RelDeplete_all}

Example text (remove Models 2 and 3 if not needed - if using, remove the
\# in-line comments!!!)\\
The estimated relative depletion level (spawning output relative to
unfished spawning output) of the the base-case model in 2017 is 75.3\%
(\textasciitilde{}95\% asymptotic interval: \(\pm\) 52.9\%-97.7\%)
(Figure \ref{fig:RelDeplete_all}).

\FloatBarrier

\begin{table}[ht]
\centering
\caption{Recent trend in estimated spawning output (million eggs) and relative spawning output.} 
\label{tab:SpawningDeplete_mod1}
\begin{tabular}{l>{\centering}p{1.3in}>{\centering}p{1.2in}>{\centering}p{1in}>{\centering}p{1.2in}}
  \hline
Year & Spawning Output (million eggs) & \~{} 95\% confidence interval & Estimated depletion & \~{} 95\% confidence interval \\ 
  \hline
2008 & 3175.00 & 1321 - 5028 & 0.48 & 0.327 - 0.642 \\ 
  2009 & 3313.00 & 1385 - 5242 & 0.50 & 0.342 - 0.668 \\ 
  2010 & 3409.00 & 1428 - 5389 & 0.52 & 0.353 - 0.687 \\ 
  2011 & 3474.00 & 1458 - 5489 & 0.53 & 0.360 - 0.699 \\ 
  2012 & 3522.00 & 1484 - 5560 & 0.54 & 0.366 - 0.708 \\ 
  2013 & 3563.00 & 1508 - 5618 & 0.54 & 0.372 - 0.715 \\ 
  2014 & 3697.00 & 1578 - 5816 & 0.56 & 0.388 - 0.739 \\ 
  2015 & 4063.00 & 1758 - 6368 & 0.62 & 0.430 - 0.809 \\ 
  2016 & 4535.00 & 1986 - 7085 & 0.69 & 0.484 - 0.899 \\ 
  2017 & 4939.00 & 2179 - 7698 & 0.75 & 0.529 - 0.977 \\ 
   \hline
\end{tabular}
\end{table}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/ts7_Spawning_output_with_95_asymptotic_intervals_intervals.png}
\caption{Time series of spawning output trajectory (circles and line:
median; light broken lines: 95\% credibility intervals) for the base
case assessment model. \label{fig:Spawnbio_all}}
\end{figure}

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/ts9_Spawning_depletion_with_95_asymptotic_intervals_intervals.png}
\caption{Estimated relative depletion with approximate 95\% asymptotic
confidnce intervals (dashed lines) for the base case assessment model.
\label{fig:RelDeplete_all}}
\end{figure}

\FloatBarrier

\subsection*{Recruitment}\label{recruitment}
\addcontentsline{toc}{subsection}{Recruitment}

\hl{Include: trends and current levels relative to virgin or historic levels-include 
table for last 10 years and graph with long term estimates.}

Recruitment Figure: (Figure \ref{fig:Recruits_all})\\
Recruitment Tables: (Tables \ref{tab:Recruit_mod1})

\begin{table}[ht]
\centering
\caption{Recent estimated trend in recruitment with approximate 95% 
                                        confidence intervals determined from the base model} 
\label{tab:Recruit_mod1}
\begin{tabular}{>{\centering}p{.8in}>{\centering}p{1.0in}>{\centering}p{1.4in}>{\centering}p{1.0in}>{\centering}p{1.4in}}
  \hline
Year & Estimated Recruitment & \~{} 95\% confidence interval & Estimated Recruitment Devs. & \~{} 95\% confidence interval \\ 
  \hline
2008 & 127258.00 & 71750 - 225709 & 2.80 & 2.485 - 3.113 \\ 
  2009 & 4856.00 & 2030 - 11618 & -0.48 & -1.283 - 0.314 \\ 
  2010 & 7683.00 & 3639 - 16220 & -0.04 & -0.661 - 0.588 \\ 
  2011 & 14600.00 & 7244 - 29424 & 0.60 & 0.035 - 1.161 \\ 
  2012 & 2130.00 & 871 - 5206 & -1.33 & -2.173 - -0.492 \\ 
  2013 & 25607.00 & 11738 - 55865 & 1.06 & 0.382 - 1.747 \\ 
  2014 & 4445.00 & 1533 - 12885 & -0.79 & -1.862 - 0.289 \\ 
  2015 & 10066.00 & 2817 - 35967 & -0.00 & -1.372 - 1.366 \\ 
  2016 & 10478.00 & 2931 - 37454 & 0.00 & -1.372 - 1.372 \\ 
  2017 & 10763.00 & 3014 - 38432 & 0.00 & -1.372 - 1.372 \\ 
   \hline
\end{tabular}
\end{table}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/ts11_Age-0_recruits_(1000s)_with_95_asymptotic_intervals.png}
\caption{Time series of estimated Pacific ocean perch recruitments for
the base-case model with 95\% confidence or credibility intervals.
\label{fig:Recruits_all}}
\end{figure}

\FloatBarrier

\subsection*{Exploitation status}\label{exploitation-status}
\addcontentsline{toc}{subsection}{Exploitation status}

\hl{Include: exploitation rates (i.e., total catch divided by exploitable biomass, or the annual SPR harvest rate) – include a table with the last 10 years of data and a graph showing the trend in fishing mortality relative to the target (y-axis) plotted against the trend in biomass relative to the target (x-axis).}

Exploitation Tables: Table \ref{tab:SPR_Exploit_mod1}, Table
\ref{tab:SPR_Exploit_mod2}, Table \ref{tab:SPR_Exploit_mod3}
Exploitation Figure: Figure \ref{fig:SPR_all}).

A summary of Pacific ocean perch exploitation histories for base model
is provided as Figure \ref{fig:Phase_all}.

\FloatBarrier

\begin{table}[ht]
\centering
\caption{Recent trend in spawning potential 
                                        ratio (1-SPR) and summary exploitation rate forPacific ocean perch.} 
\label{tab:SPR_Exploit_mod1}
\begin{tabular}{l>{\centering}p{1in}>{\centering}p{1.2in}>{\centering}p{1in}>{\centering}p{1.2in}}
  \hline
Year & Fishing intensity & \~{} 95\% confidence interval & Exploitation rate & \~{} 95\% confidence interval \\ 
  \hline
2007 & 0.105 & 0.046 - 0.164 & 0.002 & 0.001 - 0.003 \\ 
  2008 & 0.087 & 0.036 - 0.137 & 0.002 & 0.001 - 0.003 \\ 
  2009 & 0.114 & 0.046 - 0.183 & 0.003 & 0.001 - 0.004 \\ 
  2010 & 0.108 & 0.044 - 0.173 & 0.002 & 0.001 - 0.004 \\ 
  2011 & 0.037 & 0.016 - 0.059 & 0.001 & 0.000 - 0.001 \\ 
  2012 & 0.035 & 0.015 - 0.055 & 0.001 & 0.000 - 0.001 \\ 
  2013 & 0.033 & 0.014 - 0.052 & 0.001 & 0.000 - 0.001 \\ 
  2014 & 0.029 & 0.013 - 0.046 & 0.001 & 0.000 - 0.001 \\ 
  2015 & 0.029 & 0.013 - 0.045 & 0.001 & 0.000 - 0.001 \\ 
  2016 & 0.029 & 0.013 - 0.045 & 0.001 & 0.000 - 0.001 \\ 
   \hline
\end{tabular}
\end{table}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/SPR3_ratiointerval.png}
\caption{Estimated spawning potential ratio (SPR) for the base-case
model. One minus SPR is plotted so that higher exploitation rates occur
on the upper portion of the y-axis. The management target is plotted as
a red horizontal line and values above this reflect harvests in excess
of the overfishing proxy based on the SPR\textsubscript{50\%} harvest
rate. The last year in the time series is 2016. \label{fig:SPR_all}}
\end{figure}

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/SPR4_phase.png}
\caption{Phase plot of estimated relative (1-SPR) vs.~relative spawning
biomass for the base case model. The relative (1-SPR) is (1-SPR) divided
by 50\% (the SPR target). Relative depletion is the annual spawning
biomass divided by the unfished spawning biomass. \label{fig:Phase_all}}
\end{figure}

\FloatBarrier

\subsection*{Ecosystem Considerations}\label{ecosystem-considerations}
\addcontentsline{toc}{subsection}{Ecosystem Considerations}

In this assessment, ecosystem considerations were\ldots{}..

\subsection*{Reference Points}\label{reference-points}
\addcontentsline{toc}{subsection}{Reference Points}

\hl{Include:} management targets and definition of overfishing,
including the harvest rate that brings the stock to equilibrium at
\(B_{40\%}\) (the \(B_{MSY}\) proxy) and the equilibrium stock size that
results from fishing at the default harvest rate (the \(F_{MSY}\)
proxy). Include a summary table that compares estimated reference points
for SSB, SPR, Exploitation Rate and Yield based on SSBproxy for MSY,
SPRproxy for MSY, and estimated MSY values

\hl{Write intro paragraph}

This stock assessment estimates that Pacific ocean perch in the Base
model are above the biomass target, but above the minimum stock size
threshold. \hl{Add sentence about spawning output trend.} The estimated
relative depletion level for \hl{Model 1} in 2017 is 75.3\%
(\textasciitilde{}95\% asymptotic interval: \(\pm\) 52.9\%-97.7\%,
corresponding to an unfished spawning output of 4939 million eggs
(\textasciitilde{}95\% asymptotic interval:
2178.91231120822-7698.32768879178 million eggs) of spawning output in
the base model (Table \ref{tab:Ref_pts_mod1}). Unfished age 3+ biomass
was estimated to be 138715 mt in the base case model. The target
spawning output based on the biomass target (\(SB_{40\%}\)) is 2623.4
million eggs, which gives a catch of 1732.5 mt. Equilibrium yield at the
proxy \(F_{MSY}\) harvest rate corresponding to \(SPR_{50\%}\) is 1749.5
mt.

\FloatBarrier

\begin{table}[ht]
\centering
\caption{Summary of reference 
                                      points and management quantities for the 
                                      base case.} 
\label{tab:Ref_pts_mod1}
\begin{tabular}{>{\raggedright}p{4.1in}>{\centering}p{.65in}>{\centering}p{1.4in}}
  \hline
\textbf{Quantity} & \textbf{Estimate} & \textbf{\~95\%  Confidence Interval} \\ 
  \hline
Unfished spawning output (million eggs) & 6558.6 &    4675 -   8442.1 \\ 
  Unfished age 3+ biomass (mt) & 138715 & 99107.7 - 178322.3 \\ 
  Unfished recruitment (R0, thousands) & 11646 &  8776.5 -  15453.6 \\ 
  Spawning output(2017 million eggs) & 4938.6 &  2178.9 -   7698.3 \\ 
  Depletion (2017) & 0.753 &   0.529 -    0.977 \\ 
  \textbf{$\text{Reference points based on } \mathbf{SB_{40\%}}$} &  &  \\ 
  Proxy spawning output ($B_{40\%}$) & 2623.4 &    1870 -   3376.8 \\ 
  SPR resulting in $B_{40\%}$ ($SPR_{B40\%}$) & 0.55 &    0.55 -     0.55 \\ 
  Exploitation rate resulting in $B_{40\%}$ & 0.028 &   0.028 -    0.029 \\ 
  Yield with $SPR_{B40\%}$ at $B_{40\%}$ (mt) & 1732.5 &    1239 -     2226 \\ 
  \textbf{\textit{Reference points based on SPR proxy for MSY}} &  &  \\ 
  Spawning output & 2186.2 &  1558.3 -     2814 \\ 
  $SPR_{proxy}$ & 0.5 &  \\ 
  Exploitation rate corresponding to $SPR_{proxy}$ & 0.033 &   0.033 -    0.034 \\ 
  Yield with $SPR_{proxy}$ at $SB_{SPR}$ (mt) & 1749.5 &  1251.6 -   2247.3 \\ 
  \textbf{\textit{Reference points based on estimated MSY values}} &  &  \\ 
  Spawning output at $MSY$ ($SB_{MSY}$) & 2286 &  1625.3 -   2946.7 \\ 
  $SPR_{MSY}$ & 0.511 &   0.509 -    0.513 \\ 
  Exploitation rate at $MSY$ & 0.032 &   0.032 -    0.033 \\ 
  $MSY$ (mt)  & 1751.3 &  1252.8 -   2249.7 \\ 
   \hline
\end{tabular}
\end{table}

\FloatBarrier

\subsection*{Management Performance}\label{management-performance}
\addcontentsline{toc}{subsection}{Management Performance}

\hl{Include: catches in comparison to OFL, ABC and OY/ACL values for the most 
recent 10 years (when available), overfishing levels, actual catch and discard. 
Include OFL(encountered), OFL(retained) and OFL(dead) if different due to discard 
and discard mortality.}

Management performance table: Table \ref{tab:mnmgt_perform}

\begin{table}[ht]
\centering
\caption{Recent trend in total catch and commercial 
                              landings (mt) relative to the management guidelines. 
                              Estimated total catch reflect the commercial landings 
                              plus the model estimated discarded biomass.} 
\label{tab:mnmgt_perform}
\scalebox{0.9}{
\begin{tabular}{>{\raggedleft}p{0.5in}>{\centering}p{1.1in}>{\centering}p{1.1in}>{\centering}p{1.1in}>{\centering}p{1.1in}>{\centering}p{1.1in}}
  \hline
Year & OFL (mt; ABC prior to 2011) & ABC (mt) & ACL (mt; OY prior to 2011) & Total landings (mt) & Estimated total catch (mt) \\ 
  \hline
\text{2007} & - & - & 150 & 133 & 157 \\ 
  \text{2008} & - & - & 150 & 92 & 133 \\ 
  \text{2009} & - & - & 189 & 94 & 190 \\ 
  \text{2010} & - & - & 200 & 97 & 181 \\ 
  \text{2011} & - & - & 180 & 60 & 61 \\ 
  \text{2012} & - & - & 183 & 57 & 58 \\ 
  \text{2013} & - & - & 150 & 55 & 57 \\ 
  \text{2014} & - & - & 153 & 54 & 55 \\ 
  \text{2015} & - & - & 158 & 58 & 59 \\ 
  \text{2016} & - & - & 164 & 65 & 65 \\ 
   \hline
\end{tabular}
}
\end{table}

\subsection*{Unresolved Problems And Major
Uncertainties}\label{unresolved-problems-and-major-uncertainties}
\addcontentsline{toc}{subsection}{Unresolved Problems And Major
Uncertainties}

TBD after STAR panel

\FloatBarrier

\subsection*{Decision Table(s) (groundfish
only)}\label{decision-tables-groundfish-only}
\addcontentsline{toc}{subsection}{Decision Table(s) (groundfish only)}

\hl{Include: projected yields (OFL, ABC and ACL), spawning biomass, and stock 
depletion levels for each year. Not required in draft assessments undergoing review.}

OFL projection table: Table \ref{tab:OFL_projection}

Decision table(s) Table \ref{tab:Decision_table_mod1}, Table
\ref{tab:Decision_table_mod2}, Table \ref{tab:Decision_table_mod3}

\begin{verbatim}
Yield curve: Figure \ref{fig:Yield_all}
\end{verbatim}

\begin{table}[ht]
\centering
\caption{Projections of potential OFL (mt) and ACL (mt) and the estimated spawning output and relative biomass.} 
\label{tab:OFL_projection}
\begin{tabular}{>{\raggedleft}p{0.5in}>{\centering}p{1.1in}>{\centering}p{1.1in}>{\centering}p{1.6in}>{\centering}p{1.1in}}
  \hline
Year & OFL & ACL & Spawning Output ( million eggs ) & Relative Biomass \\ 
  \hline
2017 & 4171 & 281 & 4939 & 0.753 \\ 
  2018 & 4402 & 281 & 5239 & 0.799 \\ 
  2019 & 4546 & 4346 & 5472 & 0.834 \\ 
  2020 & 4476 & 4279 & 5484 & 0.836 \\ 
  2021 & 4371 & 4178 & 5461 & 0.833 \\ 
  2022 & 4250 & 4063 & 5400 & 0.823 \\ 
  2023 & 4125 & 3944 & 5314 & 0.810 \\ 
  2024 & 4003 & 3827 & 5215 & 0.795 \\ 
  2025 & 3888 & 3717 & 5109 & 0.779 \\ 
  2026 & 3782 & 3615 & 4999 & 0.762 \\ 
  2027 & 3684 & 3521 & 4889 & 0.745 \\ 
  2028 & 3593 & 3435 & 4780 & 0.729 \\ 
   \hline
\end{tabular}
\end{table}\begin{table}[ht]
\centering
\caption{Summary of 10-year 
                                             projections beginning in 2019 
                                             for alternate states of nature based on 
                                             an axis of uncertainty for the base model. 
                                             Columns range over low, mid, and high
                                             states of nature, and rows range over different 
                                             assumptions of catch levels. An entry of "--" 
                                             indicates that the stock is driven to very low 
                                             abundance under the particular scenario.} 
\label{tab:Decision_table_mod1}
\scalebox{0.85}{
\begin{tabular}{l|cc|>{\centering}p{.7in}c|>{\centering}p{.7in}c|>{\centering}p{.7in}c}
   \multicolumn{3}{c}{}  &  \multicolumn{2}{c}{} 
                               & \multicolumn{2}{c}{\textbf{States of nature}} 
                               & \multicolumn{2}{c}{} \\
  \multicolumn{3}{c}{}  &  \multicolumn{2}{c}{Low M 0.05} 
                               & \multicolumn{2}{c}{Base M 0.07} 
                               &  \multicolumn{2}{c}{High M 0.09} \\
 \hline
 & Year & Catch & Spawning Output & Depletion & Spawning Output & Depletion & Spawning Output & Depletion \\ 
  \hline
 & 2019 & - & - & - & - & - & - & - \\ 
   & 2020 & - & - & - & - & - & - & - \\ 
   & 2021 & - & - & - & - & - & - & - \\ 
  40-10 Rule,  & 2022 & - & - & - & - & - & - & - \\ 
  Low M & 2023 & - & - & - & - & - & - & - \\ 
   & 2024 & - & - & - & - & - & - & - \\ 
   & 2025 & - & - & - & - & - & - & - \\ 
   & 2026 & - & - & - & - & - & - & - \\ 
   & 2027 & - & - & - & - & - & - & - \\ 
   & 2028 & - & - & - & - & - & - & - \\ 
   \hline
 & 2019 & - & - & - & - & - & - & - \\ 
   & 2020 & - & - & - & - & - & - & - \\ 
   & 2021 & - & - & - & - & - & - & - \\ 
  40-10 Rule & 2022 & - & - & - & - & - & - & - \\ 
   & 2023 & - & - & - & - & - & - & - \\ 
   & 2024 & - & - & - & - & - & - & - \\ 
   & 2025 & - & - & - & - & - & - & - \\ 
   & 2026 & - & - & - & - & - & - & - \\ 
   & 2027 & - & - & - & - & - & - & - \\ 
   & 2028 & - & - & - & - & - & - & - \\ 
   \hline
 & 2019 & - & - & - & - & - & - & - \\ 
   & 2020 & - & - & - & - & - & - & - \\ 
   & 2021 & - & - & - & - & - & - & - \\ 
  40-10 Rule, & 2022 & - & - & - & - & - & - & - \\ 
  High M & 2023 & - & - & - & - & - & - & - \\ 
   & 2024 & - & - & - & - & - & - & - \\ 
   & 2025 & - & - & - & - & - & - & - \\ 
   & 2026 & - & - & - & - & - & - & - \\ 
   & 2027 & - & - & - & - & - & - & - \\ 
   & 2028 & - & - & - & - & - & - & - \\ 
   \hline
 & 2019 & - & - & - & - & - & - & - \\ 
   & 2020 & - & - & - & - & - & - & - \\ 
   & 2021 & - & - & - & - & - & - & - \\ 
  Average & 2022 & - & - & - & - & - & - & - \\ 
  Catch & 2023 & - & - & - & - & - & - & - \\ 
   & 2024 & - & - & - & - & - & - & - \\ 
   & 2025 & - & - & - & - & - & - & - \\ 
   & 2026 & - & - & - & - & - & - & - \\ 
   & 2027 & - & - & - & - & - & - & - \\ 
   & 2028 & - & - & - & - & - & - & - \\ 
   \hline
\end{tabular}
}
\end{table}

\begin{sidewaystable}[ht]
\centering
\caption{Base model results summary.} 
\label{tab:base_summary}
\scalebox{0.6}{
\begin{tabular}{r>{\centering}p{1.1in}>{\centering}p{1.1in}>{\centering}p{1.1in}>{\centering}p{1.1in}>{\centering}p{1.1in}>{\centering}p{1.1in}>{\centering}p{1.1in}>{\centering}p{1.1in}>{\centering}p{1.1in}>{\centering}p{1.1in}}
  \hline
Quantity & 2009 & 2010 & 2011 & 2012 & 2013 & 2014 & 2015 & 2016 & 2017 & 2018 \\ 
  \hline
Landings (mt) & - & - & - & - & - & - & - & - & - & - \\ 
  Total Est. Catch (mt) & 150 & 189 & 200 & 180 & 183 & 150 & 153 & 158 & 164 & 281 \\ 
  OFL (mt) & 92 & 94 & 97 & 60 & 57 & 55 & 54 & 58 & 65 &  \\ 
  ACL (mt) & 133 & 190 & 181 &  61 &  58 &  57 &  55 &  59 &  65 &  \\ 
   \hline
(1-$SPR$)(1-$SPR_{50\%}$) & 0.09 & 0.11 & 0.11 & 0.04 & 0.04 & 0.03 & 0.03 & 0.03 & 0.03 &  \\ 
   \hline
Exploitation rate &  0 &  0 &  0 &  0 &  0 &  0 &  0 &  0 &  0 &  \\ 
  Age 3+ biomass (mt) &  73638.5 &  74422.3 &  74753.5 &  87776.7 &  94210.9 & 100641.0 & 107215.0 & 112020.0 & 118091.0 & 121939.0 \\ 
   \hline
Spawning Output & 3175 & 3313 & 3409 & 3474 & 3522 & 3563 & 3697 & 4063 & 4535 & 4939 \\ 
  ~95\% CI & 1321 - 5028 & 1385 - 5242 & 1428 - 5389 & 1458 - 5489 & 1484 - 5560 & 1508 - 5618 & 1578 - 5816 & 1758 - 6368 & 1986 - 7085 & 2179 - 7698 \\ 
   \hline
Depletion & 0.484 & 0.505 & 0.520 & 0.530 & 0.537 & 0.543 & 0.564 & 0.620 & 0.692 & 0.753 \\ 
  ~95\% CI & 0.327 - 0.642 & 0.342 - 0.668 & 0.353 - 0.687 & 0.360 - 0.699 & 0.366 - 0.708 & 0.372 - 0.715 & 0.388 - 0.739 & 0.430 - 0.809 & 0.484 - 0.899 & 0.529 - 0.977 \\ 
   \hline
Recruits & 127258 &   4856 &   7683 &  14600 &   2130 &  25607 &   4445 &  10066 &  10478 &  10763 \\ 
  ~95\% CI & 71750 - 225709 & 2030 - 11618 & 3639 - 16220 & 7244 - 29424 & 871 - 5206 & 11738 - 55865 & 1533 - 12885 & 2817 - 35967 & 2931 - 37454 & 3014 - 38432 \\ 
   \hline
\end{tabular}
}
\end{sidewaystable}

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/yield1_yield_curve.png}
\caption{Equilibrium yield curve for the base case model. Values are
based on the 2016 fishery selectivity and with steepness fixed
at\ldots{} \label{fig:Yield_all}}
\end{figure}

\FloatBarrier

\newpage

\subsection*{Research And Data Needs}\label{research-and-data-needs}
\addcontentsline{toc}{subsection}{Research And Data Needs}

\hl{Include: identify information gaps that seriously impede the stock assessment.}

We recommend the following research be conducted before the next
assessment:

\begin{enumerate}

\item List item No. 1 in the list

\item List item No. 2 in the list, etc.

\end{enumerate}

\subsection*{Rebuilding Projections}\label{rebuilding-projections}
\addcontentsline{toc}{subsection}{Rebuilding Projections}

\hl{Include: reference to the principal results from rebuilding analysis if the 
stock is overfished. This section should be included in the Final/SAFE version 
assessment document but is not required for draft assessments undergoing review. 
See Rebuilding Analysis terms of reference for detailed information on 
rebuilding analysis requirements.}

\FloatBarrier

\newpage

\renewcommand{\thefigure}{\arabic{figure}}
\renewcommand{\thetable}{\arabic{table}}

\setcounter{figure}{0} \setcounter{table}{0}

\section{Introduction}\label{introduction}

\subsection{Basic Information}\label{basic-information}

Pacific ocean perch (\emph{Sebastes alutus}) are most abundant in the
Gulf of Alaska, and have been observed off of Japan, in the Bering Sea,
and south to Baja California, although they are sparse south of Oregon
and rare in southern California. While genetic studies have found three
populations of Pacific ocean perch off of British Columbia (Seeb and
Gunderson \protect\hyperlink{ref-seeb_genetic_1988}{1988}, Withler et
al. \protect\hyperlink{ref-withler_co-existing_2001}{2001}) with,
notably, a separate stock off of Vancouver Island, no significant
genetic differences have been found in the range covered by this
assessment. Pacific ocean perch show dimorphic growth, with females
reaching a slightly large size than males. Males and females are equally
abundant on rearing grounds at age 1.5.

The Pacific ocean perch population has been modeled as a single stock
off of the US West Coast (essentially northern California to the
Canadian border, since Pacific ocean perch are seen extremely rarely in
central and southern California). Good recruitments show up in
size-composition data throughout all portions of this area, which
supports the single stock hypothesis. This assessment includes landings
and catch data for Pacific ocean perch from the states of Washington,
Oregon and California, along with records from foreign fisheries, the
at-sea hake fleet, and fishery-indepenent surveys.

Prior to 1966, the Pacific ocean perch resource off of the northern
portion of the US West Coast was harvested almost entirely by Canadian
and United States vessels. Harvest was negligible prior to 1940, reached
1,300 mt in 1950, 3,200 mt in 1961 and exceeded 7,600 mt in 1965.
Catches increased dramatically after 1965, with the introduction of
large distant-water fishing fleets from the Soviet Union and Japan. Both
nations employed large factory stern trawlers as their primary method
for harvesting Pacific ocean perch. Peak removals by all foreign nations
combined are estimated at over 15,000 mt in 1966 and remained over
12,000 mt in 1967. These numbers are based upon a re-analysis of the
foreign catch data (Rogers
\protect\hyperlink{ref-rogers_species_2003}{2003}), which focused on
deriving a more realistic species composition for catches previously
identified only as Pacific ocean perch. Catches declined rapidly
following these peak years, and Pacific ocean perch stocks were
considered to be severely depleted throughout the Oregon-Vancouver
Island region by 1969 (Gunderson
\protect\hyperlink{ref-gunderson_population_1977}{1977}, Gunderson et
al. \protect\hyperlink{ref-gunderson_status_1977}{1977}). Landed harvest
averaged 1,350 mt over the period 1977-94. Landings have continued to
decline since 1994, primarily due to more restrictive management (Table
\ref{tab:Comm_Catch} and Figure \ref{fig:Catch}).

Prior to 1977, Pacific ocean perch in the northeast Pacific were managed
by the Canadian Government in its waters and by the individual states in
waters off of the United States. With implementation of the Magnuson
Fishery Conservation and Management Act (MFCMA) in 1977, US territorial
waters were extended to 200 miles from shore, and primary responsibility
for management of the groundfish stocks off Washington, Oregon and
California shifted from the states to the Pacific Fishery Management
Council (PFMC) and the National Marine Fisheries Service (NMFS). At that
time, however, a Fishery Management Plan (FMP) for the West Coast
groundfish stocks had not yet been approved. In the interim, the state
agencies worked with the PFMC to address conservation issues. In 1981,
the PFMC adopted a management strategy to rebuild the depleted Pacific
ocean perch stocks to levels that would produce Maximum Sustainable
Yield (MSY) within 20 years. On the basis of cohort analysis (Gunderson
\protect\hyperlink{ref-gunderson_results_1978}{1978}), the PFMC set
Acceptable Biological Catch (ABC) levels at 600 mt for the US portion of
the Vancouver INPFC area and 950 mt for the Columbia INPFC area. To
implement this strategy, the states of Oregon and Washington each
established landing limits for Pacific ocean perch. Trawl trip limits of
various forms remained in effect through 2016 (Table \ref{tab:Regs}).

Age estimates for Pacific ocean perch prior to the 1980s were made via
surface ageing of otoliths, which misses the very tight annuli at the
edge of the otolith once the fish reaches near maximum size. Ages are
biased by around age 10-12, and maximum age was estimated to be in the
20s, which lead to an overestimate of the natural mortality rate and the
productivity of the stock. Using break and burn methods, Pacific ocean
perch have been aged to over 100 years, and we now know that the
underlying assumptions of the early models were overly optimistic about
productivity. Research surveys have been used to provide
fishery-independent information about the abundance, distribution, and
biological characteristics of Pacific ocean perch. A coast-wide survey
of the rockfish resource was conducted in 1977 (Gunderson and Sample
\protect\hyperlink{ref-gunderson_distribution_1980}{1980}) and was
repeated every three years through 2004 (referred to as the `Triennial
Survey'). The National Marine Fisheries Service (NMFS) coordinated a
cooperative research survey of the Pacific ocean perch stocks off
Washington and Oregon with the Washington Department of Fisheries (WDFW)
and the Oregon Department of Fish and Wildlife (ODFW) in March-May 1979
(Wilkins and Golden
\protect\hyperlink{ref-wilkins_condition_1983}{1983}). This survey was
repeated in 1985 (referred to as the Pacific ocean perch Survey). Two
slope surveys have been conducted off the West Coast in recent years,
one using the research vessel Miller Freeman, which ended in 2001
(referred to as the `AFSC Slope Survey'), and another ongoing
cooperative survey using commercial fishing vessels which began in 1998
as a DTS (Dover sole, thornyhead and sablefish) survey, was expanded to
other groundfish in 1999 (referred to as the `NWFSC Slope Survey'). In
2003, this survey was expanded spatially to include the shelf. This last
survey, conducted by the NWFSC, continues to cover depths from 30-700
fathoms (55-1280 meters) on an annual basis (referred to as the `NWFSC
Shelf-Slope Survey').

\subsection{Summary of Management
History}\label{summary-of-management-history}

The landings of Pacific ocean perch have been historically governed by
harvest guidelines and trip limits, while recently management is imposed
with total catch harvest limits in the form of overfishing limits
(OFLs), acceptable biological catches (ABCs), and annual catch limits
(ACLs). A trawl rationalization program, consisting of an individual
fishing quota (IFQ) or catch shares system was implemented in 2011 for
the limited entry trawl fleet targeting non-whiting groundfish,
including Pacific ocean perch, and the trawl fleet targeting and
delivering whiting to shore-based processors. The limited entry at-sea
trawl sectors (motherships and catch-processors) that target whiting and
process at sea are managed in a system of harvest cooperatives.

Limits onPacific ocean perch were first established in 1983 (Table
\ref{tab:mnmgt_perform_tables}). These were implemented as area
closures, trip limits, and cumulative landing limits. In 1999, Pacific
ocean perch was declared overfished with the assessment estimating the
spawning output below the management limit (25\% of virgin biomass). In
reaction to the overfished decleration, harvest limits were reduced
relative to previous years and a rebuilding plan was implemented in
2001.

\subsection{Fisheries off Canada and
Alaska}\label{fisheries-off-canada-and-alaska}

Pacific ocean perch can be found in waters off the US west coast and
northward through Alaskan waters. In contrast the Pacific ocean perch
stock off the US west coast, each assessed portion of the stock in
Canada and Alaskan waters are estimated to be above management targets.
The subset of the stock off the US west coast represents the tail of the
species distribution with little to no Pacific ocean perch being
encountered south of northern California. Pacific ocean perch are
harvested both in Canada and Alaska. The most recent updated assessments
for the Bering Sea and the Gulf of Alaska stocks determined that neither
stock are in an overfished state and recommended and acceptable
biological catch of 43,723 mt and 23,918 mt, respectively, for 2017.

In Canadian waters Pacific ocean perch has the largest single-species
quota, accounting for approximately 25\% of all rockfish landings by
weight in the bottom trawl fleet. The Canadian Pacific ocean perch stock
is broken into three seperate areas that are individually assessed. The
status of the stock within each area are above Canadian management
targets.

\section{Data}\label{data}

Data used in the Pacific ocean perch assessment are summarized in Figure
\ref{fig:data_plot}. A description of each data source is provided
below.

\subsection{Fishery-Independent Data:}\label{fishery-independent-data}

\subsubsection{Northwest Fisheries Science Center (NWFSC) shelf-slope
survey}\label{northwest-fisheries-science-center-nwfsc-shelf-slope-survey}

The NWFSC shelf-slope survey is based on a random-grid design; covering
the coastal waters from a depth of 55 m to 1,280 m (Bradburn et al.
\protect\hyperlink{ref-bradburn_2003_2011}{2011}). This design uses four
chartered industry vessels in most years, assigned to a roughly equal
number of randomly selected grid cells. The survey, which has been
conducted from late-May to early-October each year, is divided into two
2-vessel passes of the coast, which are executed from north to south.
This design therefore incorporates both vessel-to-vessel differences in
catchability as well as variance associated with selecting a relatively
small number (approximately 700) of cells from a very large population
of possible cells (greater than 11,000) distributed from the Mexican to
the Canadian border.

The data from the NWFSC shelf-slope survey was analyzed using a
spatio-temporal delta-model (Thorson et al.
\protect\hyperlink{ref-thorson_geostatistical_2015}{2015}), implemented
as an R package VAST (Thorson and Barnett
\protect\hyperlink{ref-thorson_comparing_2017}{2017}) and publicly
available online (\url{https://github.com/James-Thorson/VAST}). Spatial
and spatio-temporal variation is specifically included in both encounter
probability and positive catch rates, a logit-link for encounter
probability, and a log-link for positive catch rates. Vessel-year
effects were included for each unique combination of vessel and year in
the database, to account for the random selection of commercial vessels
used during sampling (Helser et al.
\protect\hyperlink{ref-helser_generalized_2004}{2004}, Thorson and Ward
(\protect\hyperlink{ref-thorson_accounting_2014}{2014})). Spatial
variation was approximated using 1000 knots, and use the bias-correction
algorithm (Thorson and Kristensen
\protect\hyperlink{ref-thorson_implementing_2016}{2016}) in Template
Model Builder (Kristensen et al.
\protect\hyperlink{ref-kristensen_tmb:_2016}{2016}). Further details
regarding model structure are available in the user manual
(\url{https://github.com/James-Thorson/VAST/blob/master/examples/VAST_user_manual.pdf}).

The smallest Pacific ocean perch tend to occur in the shallower depths
(\textless{} 200 m) with only larger individuals occurring at depths
deeper than 300 m. Data collected by the NWFSC Shelf-Slope survey
between depths of 55 - 549 m and north of \(42^\circ\) and south of
\(49^\circ\) were stratified to generate an index of abundance from
2003-2016. The estimated index of abundance is shown in Table
\ref{tab:Index_Summary}. The lognormal distribution with random
strata-year and vessel effects had the lowest AIC and was chosen as the
final model. The Q-Q plot does not show any departures from the assumed
distribution (Figure \ref{fig:nw_qq}). The indices for the NWFSC
shelf-slope survey show a tentative decline in the population between
2003 and 2009, with an increasing trend in biomass between the 2009 and
2016 median point estimates.

Length, age, and conditional age-at-length compositions were expanded
based upon the stratification. The number of tows with length data
ranged from 33 in 2006 to 69 in 2015 (Table \ref{tab:NWcombo_Lengths})
where ages were collected for Pacific ocean perch in nearly every tow
(Table \ref{tab:NWcombo_Ages}). The expanded length frequencies from
this survey show an increase in small fish starting in 2010 (Figure
\ref{fig:nw_Length}). The age frequencies provide clear evidence of
large year-classes moving through the population from the 1999, 2000,
and 2008 recruitment; with early indications of a large 2013 recruitment
(Figure \ref{fig:nw_Age}).

The effective sample sizes for length and marginal age composition data
for all fishery-independet surveys were calculated according to Stewart
\& Hamel (\protect\hyperlink{ref-stewart_bootstrapping_2014}{2014})
which determined that the approximate realized sample size for
shelf/slope rockfish species was 2.43*\(N_{\text{tow}}\). The effective
sample size of conditional-age-at-length data was set at the number of
fish at each length by year.

\subsubsection{Northwest Fisheries Science Center (NWFSC) slope
survey}\label{northwest-fisheries-science-center-nwfsc-slope-survey}

The NWFSC slope survey covered waters throughout the summer from 183 m
to 1280 m north of \(34^\circ 30^\prime\) S, which is near Point
Conception between 1999 and 2002. Tows conducted between the depths of
183 and 549 m were used to create an index of abundance using a bayesian
delta-GLMM and the VAST delta-GLMM models. The estimated index of
abundance is show in Table \ref{tab:Index_Summary}. Based on the
diagnostics the bayesian delta-GLMM, which does not account for spatial
effects, gamma distribution with year-vessel random effects was selected
as the final model. The Q-Q plot does not show any departures from the
assumed distribution (Figure \ref{fig:nw_slope_qq}). The trend of
abundance across the four surveys years was generally flat with high
estimated annual variance.

Length and age compositions were available for 2001 and 2002 and were
expanded based upon the survey stratification (Tables
\ref{tab:NWslope_Lengths} and \ref{tab:NWslope_Ages}. The expanded
length frequencies from this survey shows that primarily only large fish
were captured both years (Figure \ref{fig:nw_slope_Length}). The
majority of fish observed by this survey were aged at greater than 10
years (Figure \ref{fig:nw_slope_Age}).

\subsubsection{Alaska Fisheries Science Center (AFSC) slope
survey}\label{alaska-fisheries-science-center-afsc-slope-survey}

The AFSC slope survey operated during autumn (October-November) aboard
the R/V Miller Freeman. Partial survey coverage of the U.S. west coast
occurred during 1988-96 and complete coverage (north of
\(34^\circ 30^\prime\) S) during 1997, 1999, 2000, and 2001. Only the
four years of consistent and complete surveys plus 1996, which surveyed
north of \(43^\circ\) N latitude to the U.S.-Canada border, were used in
this assessment. The number of tows with length data ranged from 19 in
2000 to 48 in 1996 (Table \ref{tab:AFSC_Lengths}). Because a large
number of positive tows occurred in 1996, it was decided to include that
year, which surveyed from \(43^\circ\) N latitude to the U.S.-Canada
border. Therefore, only tows from \(43^\circ\) N latitude to the
U.S.-Canada border were used.

An index of abundance was estimated based on the data using the VAST
delta-GLMM model. The estimated index of abundance is shown in Table
\ref{tab:Index_Summary}. The lognormal distribution with random
strata-year had the lowest AIC and was chosen as the final model. The
Q-Q plot does not show any departures from the assumed distribution
(Figure \ref{fig:afsc_qq}). The trend in the indices was generally flat
over time.

Length compositions were available for each year the survey was
conducted. No age data were available from this survey. The expanded
length frequencies from this survey were generally of larger fish (
\textgreater{} 30 cm), expect for 1997 where the highest frequency of
fish were between 20 and 30 cm for both females and males (Figure
\ref{fig:afsc_Length}).

\subsubsection{Triennial Bottom Trawl
Survey}\label{triennial-bottom-trawl-survey}

The triennial survey was first conducted by the AFSC in 1977 and spanned
the time-frame from 1977-2004. The survey's design and sampling methods
are most recently described in (Weinberg et al.
\protect\hyperlink{ref-weinberg_estimation_2002}{2002}). Its basic
design was a series of equally-spaced transects from which searches for
tows in a specific depth range were initiated. The survey design has
changed slightly over the period of time. In general, all of the surveys
were conducted in the mid-summer through early fall: the 1977 survey was
conducted from early July through late September; the surveys from 1980
through 1989 ran from mid-July to late September; the 1992 survey
spanned from mid-July through early October; the 1995 survey was
conducted from early June to late August; the 1998 survey ran from early
June through early August; and the 2001 and 2004 surveys were conducted
in May-July.

Haul depths ranged from 91-457 m during the 1977 survey with no hauls
shallower than 91 m. The surveys in 1980, 1983, and 1986 covered the
West Coast south to \(36.8^\circ\) N latitude and a depth range of
55-366 meters. The surveys in 1989 and 1992 covered the same depth range
but extended the southern range to \(34.5^\circ\) N (near Point
Conception). From 1995 through 2004, the surveys covered the depth range
55-500 meters and surveyed south to \(34.5^\circ\) N. In the final year
of the triennial series (2004), the NWFSC's Fishery Resource and
Monitoring division (FRAM) conducted the survey and followed very
similar protocols as the AFSC.

Given the different depths surveyed during 1977, the data from that year
were not included in this assessment. Water hauls (Zimmermann et al.
\protect\hyperlink{ref-zimmermann_influence_2003}{2003}) and tows
located in Canadian waters were also excluded from the analysis of this
survey. The data was examined for varying distribution of length and/or
ages of fish based upon the shift in survey timing and little evidence
was found of ontogenetic shifts in Pacific ocean perch during the summer
months.Pacific ocean perch are rarely encountered south of \(40^circ\)
where the change in southern range of the survey would have no impact on
data collected regarding Pacific ocean perch. Given these factors the
Triennial survey was analyzed as a single time-series a departure from
how the previous assessment which split the time-series into and an
early (1980-1992) and a late period (1995-2004).

An index of abundance was estimated based on the data using the VAST
delta-GLMM model. The estimated index of abundance is shown in Table
\ref{tab:Index_Summary}. The lognormal distribution with random
strata-year had the lowest AIC and was chosen as the final model. The
Q-Q plot does not show any departures from the assumed distribution
(Figure \ref{fig:tri_qq}). The index shows a decline in abundance in the
early years of the time-series and abundance remaining flat for the
latter years.

Length and age compositions were expanded based upon the stratification.
The number of tows with length data ranged from 17 in 1986 to 81 in 1998
\ref{tab:TriennialLengths}. Ages were read using surface reading methods
until 1989 when the break-and-burn method replaced surface reads as the
best method to age Pacific ocean perch. Unfortunately, surface reading
of Pacific ocean perch otoliths results in significant underestimates of
age. Due to this, these otolith were excluded from analysis. The
available ages from the Triennial survey and the number of tows where
otoliths were collected are shown in Table \ref{tab:Triennial_Ages}. The
expanded length frequencies from this survey show an increase in small
fish starting in 1995 (Figure \ref{fig:Tri_Length}). The age frequencies
provide clear evidence of large year-classes moving through the
population from the 1999 and 2000 recruitment (Figure
\ref{fig:Tri_Age}).

\subsubsection{Pacific ocean perch
Survey}\label{pacific-ocean-perch-survey}

A survey targeted designed to sample Pacific ocean perch was conducted
in 1979 and again in 1985 (for a detailed description see (Ianelli et
al. \protect\hyperlink{ref-ianelli_status_1992}{1992}). An index of
abundance was estimated based on the data using the VAST delta-GLMM
model. The estimated index of abundance is shown in Table
\ref{tab:Index_Summary}. The lognormal distribution with random
strata-year had the lowest AIC and was chosen as the final model. The
Q-Q plot does not show any departures from the assumed distribution
(Figure \ref{fig:pop_qq}). The index shows a clear decline in abundance
between the two survey years.

Length and age compositions were expanded based on the stratification.
The survey had 125 and 126 Pacific ocean perch tows (Table
\ref{tab:POP_Lengths}) and ages were only available in 1985 due to
surface reads for the 1979 data (Table \ref{tab:POP_Ages}). The length
frequencies for both years are highest between the 30-45 cm range
(Figure \ref{fig:POP_Length}) with ages in 1985 having a large number of
fish age 40 and greater (Figure \ref{fig:POP_Age}).

\subsection{Fishery-Dependent Data}\label{fishery-dependent-data}

\subsubsection{Commercial Fishery
Landings}\label{commercial-fishery-landings}

\textbf{Washington}

Historical commercial fishery landings of Pacific ocean perch from
Washington for the years 1918-2016 were obtained from Theresa Tsou
(WDFW) and Phillip Weyland (WDFW). This assessment is the first Pacific
ocean perch assessment to include a state provide historical catch
reconstruction and hence, the historical catches for Washington vary
markedly from those used in the 2011 assessment. Due to Recent landings
(1981-2016) were obtained directly from Washington state rather than
from PacFIN (Pacific Fisheries Information Network (PacFIN) due to
identified missing catches not available within PacFIN for Pacific ocean
perch.

\textbf{Oregon}

Historical commercial fishery landings of Pacific ocean perch from
Oregon for the years 1892-1986 were obtained from Alison Dauble (ODFW).
A description of the methods can be found in Karnowski et al.
(\protect\hyperlink{ref-karnowski_historical_2014}{2014}). Recent
landings (1987-2016) were obtained from PacFIN retrieval dated May 2,
2017\}, Pacific States Marine Fisheries Commission, Portland, Oregon;
www.psmfc.org). The catch data in from the POP and POP2 categories
contained within PacFIN for Pacific ocean perch were used for this
assessment. Additional catches from 1987-1999 for Pacific ocean perch
under the UROCK category not yet available in PacFIN were received
directly from the state and combined with the catch data available for
that period within PacFIN.

\textbf{California}

Historical commercial fishery landings of Pacific ocean perch were
obtained directly from John Field at the SWFSC due to database issues
for the historical period for the California Cooperative Groundfish
Survey, also known as CALCOM (128.114.3.187) for the years 1916-1980. A
description of the methods can be found in (Ralston et al.
\protect\hyperlink{ref-ralston_documentation_2010}{2010}). Recent
landings (1981-2016) were obtained from PacFIN (Pacific Fisheries
Information Network (PacFIN) retrieval dated May 2, 2017, Pacific States
Marine Fisheries Commission, Portland, Oregon; www.psmfc.org).

\textbf{At-Sea Hake Fishery}

Catches of Pacific ocean perch are monitored aboard the vessel by
observers in the At-Sea hake Observer program (ASHOP) and were available
for the years of 1975-2016. Observers use a spatial sample design, based
on weight, to randomly choose a portion of the haul to sample for
species composition. For the last decade, this is typically 30-50\% of
the total weight. The total weight of the sample is determined by all
catch passing over a flow scale. All species other than hake are removed
and weighed, by species, on a motion compensated flatbed scale.
Observers record the weights of all non-hake species. Non-hake species
total weights are expanded in the database by using the proportion of
the haul sampled to the total weight of the haul. The catches of
non-hake species in unsampled hauls is determined using bycatch rates
determined from sampled hauls. Since 2001, more than 97\% of the hauls
have been observed and sampled.

\textbf{Foreign Catches}

From the 1960s through the early 1970s, foreign trawling enterprises
harvested considerable amounts of rockfish off Washington and Oregon,
and along with the domestic trawling fleet, landed large quantities of
Pacific ocean perch. Foreign catches of individual species were
estimated by Rogers (\protect\hyperlink{ref-rogers_species_2003}{2003})
and attributed to INPFC areas for the years of 1966-1976 for Pacific
ocean perch. The foreign catches were combined across areas for a
coastwide removal total.

\subsubsection{Discards}\label{discards}

Data on discards of Pacific ocean perch are available from two different
data sources. The earliest source is called the Pikitch data and comes
from a study organized by Ellen Pikitch that collected trawl discards
from 1985-1987 (Pikitch et al.
\protect\hyperlink{ref-pikitch_evaluation_1988}{1988}). The northern and
southern boundaries of the study were \(48^\circ 42^\prime\) N latitude
and \(42^\circ 60^\prime\) N. latitude respectively, which is primarily
within the Columbia INPFC area (Pikitch et al.
\protect\hyperlink{ref-pikitch_evaluation_1988}{1988} , Rogers and
Pikitch \protect\hyperlink{ref-rogers_numerical_1992}{1992}).
Participation in the study was voluntary and included vessels using
bottom, midwater, and shrimp trawl gears. Observers of normal fishing
operations on commercial vessels collected the data, estimated the total
weight of the catch by tow and recorded the weight of species retained
and discarded in the sample. Results of the Pikitch data were obtained
from John Wallace (NWFSC, personal communication) in the form of ratios
of discard weight to retained weight of Pacific ocean perch and
sex-specific length frequencies. Discard estimates are shown in Table
\ref{tab:Discard}.

The second source is from the West Coast Groundfish Observer Program
(WCGOP). This program is part of the NWFSC and has been recording
discard observations since 2003. Table \ref{tab:Discard} shows the
discard ratios (discarded/(discarded + retained)) of Pacific ocean perch
from the WCGOP. Since 2011, when the trawl rationalization program was
implemented, observer coverage rates increased to nearly 100\% for all
the limited entry trawl vessels in the program and discard rates
declined compared to pre-2011 rates. Discard rates were obtained for
both the catch-share and the non-catch share sector for Pacific ocean
perch. A single discard rate was calculated by weighting discard rates
based on the commercial landings by each sector. Coeffienct of
variations were calculated by bootstrapping vessels within ports because
the observer program randomly chooses vessels within porats to be
observed in the non-catch shares sectors. Discard length composition for
the trawl fleet varied by year, with larger fish being discarded prior
to 2011 (Figure \ref{fig:WCGOP_discard}).

\subsubsection{Historical Commercial Catch-per-unit
effort}\label{historical-commercial-catch-per-unit-effort}

Data on catch-per-unit-effort (CPUE) in mt/hr from the domestic fishery
were combined for the INPFC Vancouver and Columbia areas (Table
\ref{tab:CPUE_Summary}, from Gunderson
(\protect\hyperlink{ref-gunderson_population_1977}{1977})). Although
these data reflect catch rates for the US fleet, the highest catch rates
coincided with the beginning of removals by the foreign fleet. This
suggest that, barring unaccounted changes in fishing efficiency during
this period, the level of abundance was high at that time. A CV of 0.40
was used in this assessment to be consistent with the CV observed in the
survey data.

\subsubsection{Fishery Length And Age
Data}\label{fishery-length-and-age-data}

Biological data from commercial fisheries that caught Pacific ocean
perch were extracted from PacFIN (PFSMFC) on \hl{XXXX}. Lengths taken
during port sampling in Oregon and Washington were used to calculate
length and age compositions. There were no biological data for Pacific
ocean perch available within PacFIN. The overwhelming majority of these
data were collected from the mid-water and bottom trawl gear, but
additional biological data were collected from non-trawl gear which was
grouped together with trawl gear data. Tables \ref{tab:Comm_Lengths} and
\ref{tab:Comm_Ages} show the number of trips and fish sampled, along
with the calculated sample sizes. Length and age data were acquired at
the trip level, and then aggregated to the state level. The sample sizes
were calculated via the Stewart Method (Ian Stewart, pers. Comm.) which
for commercial fishery data is:

\begin{centering}

Input effN = $N_{\text{trips}} + 0.138 * N_{\text{fish}}$ if $N_{\text{fish}}/N_{\text{trips}}$ is $<$ 44

Input effN = $7.06 * N_{\text{trips}}$ if $N_{\text{fish}}/N_{\text{trips}}$ is $\geq$ 44

\end{centering}

\subsection{Biological Data}\label{biological-data}

\subsubsection{Natural mortality}\label{natural-mortality}

Historic Pacific ocean perch ages determined using scales and surface
reading methods of otoliths, resulted in estimates of natural mortality
(\(M\)) of between 0.10 and 0.20yr\textsuperscript{-1} with a longevity
less than 30 years(Gunderson
\protect\hyperlink{ref-gunderson_population_1977}{1977}). Based on
break-and-burn method of age determination using otoliths, the maximum
age of Pacific ocean perch was revised to be 90 years (Chilton and
Beamish \protect\hyperlink{ref-chilton_age_1982}{1982}). The updated
understanding concerning Pacific ocean perch longevity reduced the
estimate of natural mortality based on Hoenig's
(\protect\hyperlink{ref-hoenig_empirical_1983}{1983}) relationship to
0.059yr\textsuperscript{-1}. The previous assessment applied a prior
distribution on natural mortality based upon multiple life history
correlates (including Hoenig's method, Gunderson gonadosomatic index
(\protect\hyperlink{ref-gunderson_trade-off_1997}{1997}), and McCoy and
Gillooly's (\protect\hyperlink{ref-mccoy_predicting_2008}{2008})
theoretical relationship) developed separately for female and male
Pacific ocean perch.

Hamel (\protect\hyperlink{ref-hamel_method_2015}{2015}) developed a
method for combining meta-analytic approaches to relating the natural
mortality rate M to other life-history parameters such as longevity,
size, growth rate and reproductive effort, to provide a prior on \(M\).
In that same issue of ICESJMS, Then et al.
(\protect\hyperlink{ref-then_evaluating_2015}{2015}), provided an
updated data set of estimates of \(M\) and related life history
parameters across a large number of fish species, from which to develop
an \(M\) estimator for fish species in general. They concluded by
recommending \(M\) estimates be based on maximum age alone, based on an
updated Hoenig non-linear least squares (nls) estimator
M=4.899A\_max\^{}(-.916). The approach of basing M priors on maximum age
alone was one that was already being used for West Coast rockfish
assessments. However, in fitting the alternative model forms relating
\(M\) to \(A_{\text{max}}\), Then et al.
(\protect\hyperlink{ref-then_evaluating_2015}{2015}) did not
consistently apply their transformation. In particular, in real space,
one would expect substantial heteroscedasticity in both the observation
and process error associated with the observed relationship of M to
\(A_{\text{max}}\). Therefore, it would be reasonable to fit all models
under a log transformation. This was not done. Revaluating the data used
in Then et al. (\protect\hyperlink{ref-then_evaluating_2015}{2015}) by
fitting the one-parameter \(A_{\text{max}}\) model under a log-log
transformation (such that the slope is forced to be -1 in the
transformed space (Hamel
\protect\hyperlink{ref-hamel_method_2015}{2015})), the point estimate
for \(M\) is:

\begin{centering}

$M=\frac{5.4}{A_{\text{max}}}$

\end{centering}

The above is also the median of the prior. The prior is defined as a
lognormal with mean \(ln(\frac{5.4}{A_{\text{max}}})\) and SE =
0.4384343. Using a maximum age of 100 the point estimate and median of
the prior is 0.054. The maximum age was selected based on available age
data from all West Coast data sources. The oldest aged rockfish was 120
years, captured by the commercial fishery in 2007. However, age data are
subject to ageing error which could impact this estimate of longevity.
The selection of 100 years was based on the range of other ages
available with had multiple observations of fish between 90 and 102
years of age.

\subsubsection{Sex ratio, maturation, and
fecundity}\label{sex-ratio-maturation-and-fecundity}

Examining all biological data sources, the sex ratio of young fish are
within 5\% of 1:1 by either length or age (Figures \ref{fig:sexratio}
and \ref{fig:sexratio_Age}), and hence this assessment the sex ratio at
birth was assumed to be 1:1. This assessment assumed a logistic
maturity-at-length curve based on analysis of 537 fish maturity samples
collected from the NWFSC shelf-slope survey. This is revised from the
previous assessment which assumed maturity-at-age based on the work of
Hannah and Parker (Hannah and Parker
\protect\hyperlink{ref-hannah_age-modulated_2007}{2007}). Additionally,
the new maturity-at-length curve is based on the estimate of functional
maturity an approach that classifies rockfish maturity with developing
oocytes as mature or immature based on the proportion of vitellogenin in
the cytoplasm and the measured frequency of atretic cells (M. Head,
personal communication). The 50\% size-at-maturity was estimated at 32.1
cm with maturity asymptoting to one for larger fish (Figure
\ref{fig:mat}). Comparison between the maturity-at-age used in the
previous assessment and the updated functional maturity-at-length is
shown in Figure \ref{fig:mat_compare}.

The fecundity-at-age has also been updated from the previous assessment
based on new research. Dick
(\protect\hyperlink{ref-dick_meta-analysis_2017}{2017}) estimated new
fecundity relationships for select West Coast stocks where fecundity for
Pacific ocean perch was estimated equal to 0\(L\)\textsuperscript{4.98}
in millions of eggs. Spawning output at length is shown in Figure
\ref{fig:fecundity}.

\subsubsection{Length-weight
relationship}\label{length-weight-relationship}

The length-weight relationship for Pacific ocean perch was estimated
outside the model using all biological data available from fishery and
fishery-independent data sources where the female weight-at-length in
grams was estimated at 0.0000104\(L\)\textsuperscript{3.09} and males at
0.0000105\(L\)\textsuperscript{3.08} where \(L\) is length in cm
(Figures \ref{fig:Wt_len} and \ref{fig:Wt_len_pred}).

\subsubsection{Growth (length-at-age)}\label{growth-length-at-age}

The length-at-age was estimated for male and female Pacific ocean perch
using data collected from both fishery-dependent and -independent data
sources that were collected from 1981-2016. Figure \ref{fig:Len_Age}
shows the lengths and ages for all years and all data as well as
predicted von Bertalanffy fits to the data. Females grow larger than
males and sex specific growth parameters were estimated at the following
values:

\begin{centering}

Females $L_{\infty}$ = 42.32; $k$ = 0.169; $t_0$ = -1.466

Males $L_{\infty}$ = 39.03; $k$ = 0.212; $t_0$ = -1.02

\end{centering}

\subsubsection{Ageing Precision And
Bias}\label{ageing-precision-and-bias}

Uncertainty surrounding the ageing-error process for Pacific ocean perch
was incorporated by estimating ageing error by age. Age-composition data
used in the model were from break-and-burn otolith reads aged by the
Cooperative Ageing Project (CAP) in Newport, Oregon. Break-and-burn
double reads of more than 1500 otoliths were provided by the CAP lab. An
ageing error estimate was made based on these double reads using a
computational tool specifically developed for estimating ageing error
(Punt et al. \protect\hyperlink{ref-punt_quantifying_2008}{2008}), and
using release 1.0.0 of the R package nwfscAgeingError (Thorson et al.
\protect\hyperlink{ref-thorson_nwfscageingerror:_2012}{2012}) for input
and output diagnostics, publicly available at:
\url{https://github.com/nwfsc-assess/nwfscAgeingError}. A non-linear
standard error was estimated by age where there is more variability in
the estimated age of older fish was estimated (Table
\ref{tab:Age_Error}, Figure \ref{fig:Age_Error}).

\subsection{History Of Modeling Approaches Used For This
Stock}\label{history-of-modeling-approaches-used-for-this-stock}

\subsubsection{Previous Assessments}\label{previous-assessments}

The status of Pacific ocean perch off British Columbia, Washington, and
Oregon have been periodically assessed since the intensive exploitation
that occured in the 1960s. Concerns regarding Pacific ocean perch status
off the coast the US west coast were raised in the late 1970s (Gunderson
\protect\hyperlink{ref-gunderson_results_1978}{1978}, Gunderson
(\protect\hyperlink{ref-gunderson_updated_1981}{1981})) and in 1981 the
PFMC adopted a 20-year plan to rebuild the stock.

The 1992 assessment determined that Pacific ocean perch remained at low
levels relative to the population size in 1960 (Ianelli et al.
\protect\hyperlink{ref-ianelli_status_1992}{1992}) and recommended
additional harvest restrictions to allow for stock rebuilding. The 1998
assessment (Ianelli and Zimmermann
\protect\hyperlink{ref-ianelli_status_1998}{1998}) estimated that the
stock was 13\% of the unfished level, leading the National Marine
Fishery Service (NMFS) to declare the stock overfished in 1999. The
formal rebuilding plan was implemented in 2001. The rebuilding plan
reduced the SPR harvest rate used to determine catches to 0.864,
relative to the PFMC rockfish default harvest (SPR = 0.50). The last
full assessment of Pacific ocean perch was conducted in 2011 (Hamel and
Ono \protect\hyperlink{ref-hamel_stock_2011}{2011}) which concluded that
the stock was still well below the target biomass of \(0.40SB_{0}\)
estimating the relative stock status at 19.1\%.

\subsubsection{Previous Assessment
Recommendations}\label{previous-assessment-recommendations}

Recommendation: Considering trans-boundary stock effects should be
pursued. In particular the consequences of having spawning contributions
from external stock components should be evaluated relative to the
steepness estimates obtained in the present assessment (see more
complete discussion of this recommendation under the Unresolved Problems
and Major Uncertainties section, above).

\emph{STAT response: The STAT team agrees that this should be an ongoing
area of research and collaboration between the US and Canada. This
assessment presents a sensitivity where the inclusion of Canadian data
are included within the model.}

Recommendation:The benefits of adopting the complex model used this year
should be evaluated relative to simpler assumptions and models. While
the transition from the simpler old model to Stock Synthesis was shown
to be similar for the historical period, the depletion estimates in the
most recent years were different enough to warrant further
investigation.

\emph{STAT response: This assessment was performed in Stock Synthesis,
an integrated model, which can be modified to either simple or complex
structural forms based upon the available data and the processes being
modeled. There were not addtional explorations of alternative modeling
platforms.}

Recommendation:Discard estimates from observer programs should be
presented, reviewed (similar to the catch reconstructions), and be made
available to the assessment process.

\emph{STAT response: This assessment uses discard rates and discard
lengths collected by the WCGOP from 2003-2015.}

Recommendation:The ability to allow different ``plus groups'' for
specific data types should be evaluated (and implemented in Stock
Synthesis). For example, this would provide the ability to use the
biased surface-aged data in an appropriate way.

\emph{STAT response: Additional research needs to completed which
evaluates the amount of bias and imprecision in surface-read ages.
Evaluating avaiable surface-read ages within the PacFIN database fish of
lengths between 23-44 cm can be aged at 10 years old. This large range
of lengths at the same age indicates considerable bias in ages for fish
surface-read younger aged fish.}

Recommendation:Historical catch reconstruction estimates should be
formally reviewed prior to being used in assessments and should be
coordinated so that interactions between stocks are appropriately
treated. The relative reliability of the catch estimates over time could
provide an axis of uncertainty in future assessments.

\emph{STAT response: California and Oregon have ungone extensive work to
create historical catch reconstructions. This is the first assessment
for Pacific ocean perch which includes a Washington historical catch
reconstruction. The data used in this assessment represent Washington
state's current best estimate for historical catches. Both California
and Washington are conducting research to estimate uncertainty surround
historical catches which could be used to propegate uncertainty within
the assessment.}

\section{Assessment}\label{assessment}

\subsection{General Model Specifications and
Assumptions}\label{general-model-specifications-and-assumptions}

Stock Synthesis \hl{v3.30.03.03} was used to estimate the parameters in
the model. R4SS, revision 1.26.0, along with R version 3.3.2 were used
to investigate and plot model fits. A summary of the data sources used
in the model (details discussed above) is shown in Figure
\ref{fig:data_plot}.

Stock Synthesis has many options when setting up a model and the
assessment model for Pacific ocean perch was set up in the following
manner.

\subsubsection{Changes between the 2011 assessment model and current
model}\label{changes-between-the-2011-assessment-model-and-current-model}

The current model for Pacific ocean perch has many made many similar
assumptions to the 2011 assessment but differs in some key ways. This
assessment disaggrated the fleets into a trawl/other gear, at-sea hake,
historical foreign fleet, and research fleets. The previous assessment
implemented a single fleet where removal from all sources were
aggregated together. The seperating of fleets applied in this assessment
allowed for differing assumptions regarding current and historical
discarding practices. Although there are no compositional data available
from the foreign fleet, it is assumed that very little discarding to no
discarding of fish occured. Additionally, the at-sea hake fishery
removals are represent both discarded and retained fish and hence an
additional discard rate would not be appropriate. Similar logic was
applied in regard to survey and research removals.

The historical landing used in the model differs from those used in
2011. The assessment includes the first state provided historical
reconstruction landings for Washington state. The historical
reconstruction provided Pacific ocean perch landing within Washington
state starting in 1916 and have significantly larger removals in the
1940s relative to those used in 2011. Given the increase in historical
removals prior to 1940, the 2011 model starting year, the starting year
for modeling the stock was revised to 1918, the first year Pacific ocean
perch landings exceeded 1 mt, for this assessment. Explorations were
conducted relative to the model starting year and no differences were
found between the 1918 start year compared to starting the model in
1892, the first record of Pacific ocean perch landings between
California, Oregon, and Washington catch data.

Selectivity in this model is assumed to be length-based and is modeled
using double-normal for all fleets, expect the Pacific ocean perch
survey which retained the previous assessment assumption of logistic
selectivity. The previous assessment mirrored selectivity amont the
Pacific ocean perch and both slope surveys (AFSC and NWFSC). This
assessment allow for survey specific estimated double-normal
selectivity.

All fishery-independent indices have been reevaluated for this
assessment using a spatial-temporal delta generalized linear mixed model
(VAST delta-GLMM) which is updated from 2011 which used a bayesian
delta-GLMM which did not incorporate spatial effects. An additional
update to the treatment of survey data was the decision to use the
Triennial survey as a single time series ranging from 1980-2004. The
previous assessment opted to split this survey into early and a late
index of abundance based upon the change in southern sampling and a
shift in survey timing. Northern California is considered to be the
southern end of Pacific ocean perch West Coast distribution with rare
encounters in central or southern California waters. The biological data
from the Triennial survey showed no discernable ontogenetic shifts in
Pacific ocean perch during the early or late period of summer samples.
Based upon these investigations, the Triennial survey was retained as a
single index of abundance.

Maturity and fecundity were updated for this assessment based upon new
research. Fecundity for Pacific ocean perch used in this assessment was
base on reevaluation of the fecundity of West Coast rockfish by Dick et
al. (\protect\hyperlink{ref-dick_meta-analysis_2017}{2017}) updating the
previous fecundity estimates used in the 2011 assessment (Dick
\protect\hyperlink{ref-dick_modeling_2009}{2009}). Maturity in this
assessment was based on examination of 537 fish samples which were used
to estimate functional maturity, an approach that classifies rockfish
maturity with developing oocytes as mature or immature based on the
proportion of vitellogenin in the cytoplasm and the measured frequency
of atretic cells (M. Head, personal communication). The updated maturity
curve was based on maturity-at-length where the previous estimates used
in 2011 were based on maturity-at-age.

In this assessment, the beta prior developed from a meta-analysis of
West Coast groundfish was updated to the 2017 value (J. Thorson personal
communication) in preliminary models, with steepness fixed in the final
base model. Additionally, the prior for natural mortality was updated
base on analysis conducted by Owen Hamel (personal communication), where
female natural mortality was fixed at the prior median with males
estimated as an offset from the female value.

\subsubsection{Summary of Fleets and
Areas}\label{summary-of-fleets-and-areas}

Pacific ocean perch are most frequently observed in Oregon and
Washington waters, however, they are observed along the entire US West
Coast in survey and fishery observations. Multiple fisheries encounter
Pacific ocean perch. Trawl, fixed gear, and the at-sea (mid-water) hake
fisheries account for the majority of the Pacific ocean perch landings
both historically and currently.

The majoirty of removals of Pacific ocean perch were observed by eht
bottom trawl fishery with fixed gear accounting for a small fraction of
the catches avaiable within PacFIN. Trawl and fixed gears were combined
into a coast-wide fleet. For the period from 1918 to the early 1990s,
prior to the introduction of trip limits for rockfish, limited
discarding of Pacific ocean perch was assumed. Observations of Pacific
ocean perch in the Pikitch et al. (1988) data (1986-1987) allowed for a
formal analysis of discard rates which were applied to the historical
period of the fishery. Foreign trawl catches (1966-1976) was modeled as
a single fleet. The at-sea fishery operates as a mid-water fishery
targeting Pacific whiting but encounters Pacific ocean perch as a
bycatch species. This fleet was also modeled as a single fleet.

\subsubsection{Other Specifications}\label{other-specifications}

The specifications of the assessment are listed in Table
\ref{tab:Model_setup}. The model is a two-sex, age-structured model
starting in 1918 with an accumulated age group at 60 years. Growth was
estimated and natural mortality was fixed at the median of the prior.
The lengths in the population were tracked by 1 cm intervals and the
length data were binned into 1 cm intervals. A curvilinear ageing
imprecision relationship was estimated and used to model ageing error.
Fecundity-at-length was defined fixed at the values from Dick et al.
(\protect\hyperlink{ref-dick_meta-analysis_2017}{2017}) for Pacific
ocean perch and spawning output was defined in millions of eggs.

The Triennial survey was kept as a single series. Assessment of other
groundfish have split this survey into an early and a late series, based
mostly on the shift to deeper depths and the timing of the survey, by
estimating different catchability parameters and selectivity parameters
for each period. Age data were available for the commercial and at-sea
hake fishery, as well as the Triennial, the Pacific ocean perch, the
NWFSC slope, and the NWFSC shelf-slope survies. The ages from the NWFSC
shelf-slope survey and were entered into the model as conditional
age-at-length. Length-frequencies were calculated for the Triennial,
Pacific ocean perch, AFSC slope, NWFSC slope, and the NWFSC shelf-slope
surveys within each stratum, and then combined across strata using the
biomass in each stratum as the weighting factor. This reduced the
influence of a few fish observed in a large area.

The specification of when to estimate recruitment deviations is an
assumption that likely affects model uncertainty. It was decided to
estimate recruitment deviations from 1900-2014 to appropriately quantify
uncertainty. The earliest length-composition data occur in 1966 and the
earliest age data were in 1981. The most informed years for estimating
recruitment deviations were from about the mid-1970s to about 2011. The
period from 1900-1974 was fit using an early series with little or no
bias adjustment, the main period of recruitment deviates occurred from
1975-2014 with an upward and downward ramping of bias adjustment, and
2015 onward was fit using forecast recruitment deviates with little bias
adjustment. Methot and Taylor
(\protect\hyperlink{ref-methot_adjusting_2011}{2011}) summarize the
reasoning behind varying levels of bias adjustment based on the
information available to estimate the deviates. Recruitment deviation
was assumed to be 0.70.

The recommended selectivity type in Stock Synthesis is the double normal
and was used in this assessment for the all fleets, except the Pacific
ocean perch survey which was assumed logistic based on the length
composition data. Changes in retention curves were estimated for the
commercial fishery.

Time blocks for the bottom trawl, midwater trawl, and hook-and-line
fishery are provided in Table \ref{tab:Model_setup}. Fishery selectivity
retention has changed over the modeled period due to management changes.
The time block on the retention curves for the trawl fishery were set
from 1918-1991, 1992-2001, 2002-2007, 2008, 2009-2010, 2011-2016 based
on available discarding data and changes in trip limits that likely
resulted in changes to discarding patterns of Pacific ocean perch. No
discarding was assumed in the at-sea hake and the foreign fisheries.

The following distributions were assumed for data fitting. Survey
indices were lognormal, total discards were lognormal.

\subsubsection{Modeling Software}\label{modeling-software}

The STAT team used Stock Synthesis version \hl{3.30.03.03} by
Dr.~Richard Methot at the NWFSC (Methot and Wetzel
\protect\hyperlink{ref-methot_stock_2013}{2013}). This most recent
version was used, since it included improvements and corrections to
older versions.

\subsubsection{Priors}\label{priors}

A prior distribution was developed for the natural mortality parameter
from an analysis of a maximum age of 100 years. The analysis was
performed by Owen Hamel (pers comm, NWFSC, NOAA) and used data from Then
et al. (\protect\hyperlink{ref-then_evaluating_2015}{2015}) to provide a
lognormal distribution for natural mortality. The median of the
lognormal prior is 0.054 and has a standard error of 0.4384343.

The prior for steepness (\(h\)) assumes a beta distribution with
parameters based on an update of the Dorn rockfish prior (commonly used
in past West Coast rockfish assessments) conducted by J. Thorson (pers.
comm, NWFSC, NOAA) which was reviewed and endorsed by the SSC in 2017.
The prior is a beta distribution with \(\mu\)=0.72 and \(\sigma\)=0.15.
However, fixing steepness within the model resulted in unrealistic
relative biomass levels (\(>\) 1), it was also decided to fix steepness
at 0.50. The previous assessment estimated and fixed steepness equal to
0.40. The current data does not contain information regarding steepness
and 0.50 was selected as an intermediate value between the prior and the
previous assessment value. The steepness value of 0.50 was contained
within the estimated uncertainty envelope from the assessment model when
either the prior value of 0.72 or 0.40 values were assumed.

\subsubsection{Data Weighting}\label{data-weighting}

The base case was weighted such that the various data sources were
mostly consistent with each other in terms of the relationship between
input and effective sample sizes. Length and age-at-length compositions
from the NWFSC shelf-slope survey were fit along with length and
marginal age compositions from the fishery fleets. Length data started
with a sample size determined from the equation listed in Section
\ref{fishery-length-and-age-data} and
\ref{northwest-fisheries-science-center-nwfsc-shelf-slope-survey}.
Age-at-length data assumed that each age was a random sample within the
length bin and started with a sample size equal to the number of fish in
that length bin . One extra variability parameter that was added to the
input variance was estimated for the Triennial and the NWFSC shelf-slope
survey indices. Vessels present in the WCGOP data were bootstrapped to
provide uncertainty of the total discards (Table \ref{tab:Discard}).

The base case assessment model was weighted based on the ``Francis
method'', which was based on equation TA1.8 in Francis
(\protect\hyperlink{ref-francis_data_2011}{2011}). This formulation
looks at the mean length or age and the variance of the mean to
determine if across years, the variability is explained by the model. If
the variability around the mean does not encompass the model
predictions, then that data source should be down-weighted. This method
does account for correlation in the data (i.e., the multinomial
distribution) as opposed to the McAllister and Ianelli
(\protect\hyperlink{ref-mcallister_bayesian_1997}{1997}) method of
looking at the difference between individual observations and
predictions.

\subsubsection{Estimated And Fixed
Parameters}\label{estimated-and-fixed-parameters}

There were 164 estimated parameters in the base case model. These
included one parameter for \(R_0\), 8 parameters for growth, 2
parameters for extra variability on the Triennial and NWFSC shelf-slope
surveys indices, 24 parameters for selectivity, retention, and time
blocking of the fleets and the surveys, 117 recruitment deviations, and
12 forecast recruitment deviations (Table \ref{tab:model_params}).

Fixed parameters in the model were as follows. Steepness was fixed at
0.50. A sensitivity analysis and a likelihood profile were done for
steepness. Natural mortality was fixed at 0.054 for females and males,
which is the median of the prior. The standard deviation of recruitment
deviates was fixed at 0.70. Maturity at age was fixed as described in
Section \ref{sex-ratio-maturation-and-fecundity}. Length-weight
parameters were fixed at estimates using all length-weight observations
(Figure \ref{fig:Wt_len_pred}).

Dome-shaped selectivity was explored for both the fishery and the
surveys. Older Pacific ocean perch are often found in deeper waters and
may move into areas that limit their availability to fishing gear,
especially trawl gear. Domed shape selectivity was assumed for the
fishery fleet and the Triennial survey. The final base model assumed
asymptotic selectivity for the at-sea hake fishery, and all other
surveys.

\subsection{Model Selection and
Evaluation}\label{model-selection-and-evaluation}

The base case assessment model for Pacific ocean perch was developed to
balance parsimony and realism, and the goal was to estimate a biomass
trajectory for the population of Pacific ocean perch on the west coast
of the United States. The model contains many assumptions to achieve
parsimony and uses many different sources of data to estimate reality. A
series of investigative model runs were done to achieve the final base
case model.

\subsubsection{Key Assumptions and Structural
Choices}\label{key-assumptions-and-structural-choices}

The key assumptions in the model were that the assessed population is a
single stock with biological parameters characterizing the entire coast,
maturity at age has remained constant over the period modeled,
weight-at-length has remained constant over the period modeled, the
standard deviation in recruitment deviation is 0.70, and steepness is
0.50. These are simplifying assumptions that unfortunately cannot be
verified or disproven. Sensitivity analyses were conducted for most of
these assumptions to determine their effect on the results.

Structurally, the model assumed that the catches from each fleet were
representative of the coastwide population, instead of specific areas,
and fishing mortality prior to 1918 was negligible. It also assumed that
discards were low prior to 1992 and after 2010.

\subsubsection{Alternate Models
Considered}\label{alternate-models-considered}

The exploration of models began by bridging from the 2011 assessment to
SS version 3.24U, which produced no discernable difference. The updated
catch series with discards added per the 2011 assessment produced
insignificant differences in the relative scale of the population
although the updated historical removals resulted in an increase in the
estimate of unfishe biomass (Figure \ref{fig:XX}). Updating the survey
indices produced small differences in the relative scale of the
population. Adding age and length data each resulted in an less of a
population decline from the 1970s to pre-2000, resulting in an increase
in the estimated final stock status as of 2017. However, the addition of
new data resulted in an early pattern within recruitment, indicating
that the assumptions within the previous model may not represent the
best fit to the current data.

This assessment estimated discards in the model, so time was spent
investigating time blocks for changes in selectivity and retention to
match the limited discard data as best as possible. Using major changes
in management and observed changes in landings, a set of blocks for
retention was found for the bottom trawl fleets. In the spirit of
parsimony, we used as few blocks as possible, allowed blocks only for
time periods with data, and added new blocks when we felt they were
justified by changes in management and they improved the fit to the
data.

Natural mortality was also investigated and a new prior was developed
assuming a maximum age of 100 years for females and males. The previous
assessment estimated male natural mortality as an offset from female
natural mortality which was fixed at the median of the 2011 prior. This
assessment attempted to estimate natural mortality for both sexes using
the 2017 updated prior, but there was little to no information on
natural mortality within the data and hence opted to fix the value for
females. Upon additional exploration, the model estimated very little
difference in male natural mortality relative to females (\textless{}
0.002) and in the interest of selecting the model that fit the data with
the fewest parameters required, males were fixed equal to the female
natural mortality.

\subsubsection{Convergence}\label{convergence}

Proper convergence was determined by starting the minimization process
from dispersed values of the maximum likelihood estimates to determine
if the model found a better minimum. This was repeated 100 times and a
better minimum was not found (Table \ref{tab:jitter}). The model did not
experience convergence issues when provided reasonable starting values.
Through the jittering done as explained above and likelihood profiles,
we are confident that the base case as presented represents the best fit
to the data given the assumptions made. There were no difficulties in
inverting the Hessian to obtain estimates of variability, although much
of the early model investigation was done without attempting to estimate
a Hessian.

\subsection{Response To The Current STAR Panel
Requests}\label{response-to-the-current-star-panel-requests}

\begin{description}[style=unboxed]

\item[Request No. 1: Add after STAR panel.] \hfill \\

    \textbf{Rationale:} Add after STAR panel.  

    \textbf{STAT Response:} Add after STAR panel.

\item[Request No. 2: Add after STAR panel.] \hfill \\

    \textbf{Rationale:} Add after STAR panel.

    \textbf{STAT Response:} Add after STAR panel.

\item[Request No. 3: Add after STAR panel.] \hfill \\

    \textbf{Rationale:} Add after STAR panel.
  
    \textbf{STAT Response:} Add after STAR panel.

\item[Request No. 4: Example of a request that may have a list:] \hfill \\
\begin{itemize}
\item \textbf{Item No. 1}
\item \textbf{Item No. 2}
\item \textbf{Item No. 3, etc.}
\end{itemize}

    \textbf{Rationale:} Add after STAR panel.

    \textbf{STAT Response:} Continue requests as needed.


\end{description}

\subsection{Base Model Results}\label{base-model-results}

The base model parameter estimates along with approximate asymptotic
standard errors are shown in Table \ref{tab:model_params} and the
likelihood components are shown in Table \ref{tab:like}. Estimates of
key derived parameters and approximate 95\% asymptotic confidence
intervals are shown in Table \ref{tab:Ref_pts}.

\subsubsection{Uncertainty and Sensitivity
Analyses}\label{uncertainty-and-sensitivity-analyses}

Table \ref{tab:Sensitivity_model1}

\subsubsection{Retrospective Analysis}\label{retrospective-analysis}

\subsubsection{Likelihood Profiles}\label{likelihood-profiles}

\subsubsection{Reference Points}\label{reference-points-1}

Intro sentence or two\ldots{}.(Table \ref{tab:Timeseries_mod1}).

Equilibrium yield at the proxy \(F_{MSY}\) harvest rate corresponding to
\(SPR_{50\%}\) is 1749.5 mt. Table \ref{tab:Ref_pts_mod1} shows the full
suite of estimated reference points for the northern area model and
Figure \ref{fig:Yield_all} shows the equilibrium yield curve.

\section{Harvest Projections and Decision
Tables}\label{harvest-projections-and-decision-tables}

Table \ref{tab:mnmgt_perform}

\textbf{Model 1 Projections and Decision Table (groundfish only)} (Table
\ref{tab:Forecast_mod1}

Table \ref{tab:Decision_table_mod1}

\textbf{Model 2 Projections and Decision Table (groundfish only)}

\textbf{Model 3 Projections and Decision Table (groundfish only)}

\section{Regional Management
Considerations}\label{regional-management-considerations}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  For stocks where current practice is to allocate harvests by
  management area, a recommended method of allocating harvests based on
  the distribution of biomass should be provided. The MT advisor should
  be consulted on the appropriate management areas for each stock.
\item
  Discuss whether a regional management approach makes sense for the
  species from a biological perspective.
\item
  If there are insufficient data to analyze a regional management
  approach, what are the research and data needs to answer this
  question?
\end{enumerate}

\section{Research Needs}\label{research-needs}

\begin{enumerate}

\item Research need No. 1

\item Research need No. 2

\item Research need No. 3

\item etc.

\end{enumerate}

\section{Acknowledgments}\label{acknowledgments}

Teresa Tsou (WDFW), Philip Wyland (WDFW), Ali Whitman (ODFW), Patrick
Mirrick (ODFW), Patrick McDonald (CAPS), Vanessa Tuttle (ASHOP), Beth
Horness (NWFSC), Kayleigh Sommers (NWFSC), Jason Jannot (NWFSC)

\newpage

\FloatBarrier

\section{Tables}\label{tables}

\begin{table}[ht]
\centering
\caption{Landings for each state (all gears combined), the At-Sea Hake fishery, the Foreign fleet, and                                             research.} 
\label{tab:Comm_Catch}
\begin{tabular}{>{\centering}p{.5in}>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{1in}>{\centering}p{.75in}>{\centering}p{.75in}}
  \hline
Year & California & Oregon & Washington & At-Sea Hake & Foreign & Research \\ 
  \hline
1892 & 0.0 & 0.1 & 0.0 & 0.0 &  0 & 0.0 \\ 
  1893 & 0.0 & 0.1 & 0.0 & 0.0 &  0 & 0.0 \\ 
  1894 & 0.0 & 0.1 & 0.0 & 0.0 &  0 & 0.0 \\ 
  1895 & 0.0 & 0.0 & 0.0 & 0.0 &  0 & 0.0 \\ 
  1896 & 0.0 & 0.0 & 0.0 & 0.0 &  0 & 0.0 \\ 
  1897 & 0.0 & 0.0 & 0.0 & 0.0 &  0 & 0.0 \\ 
  1898 & 0.0 & 0.0 & 0.0 & 0.0 &  0 & 0.0 \\ 
  1899 & 0.0 & 0.0 & 0.0 & 0.0 &  0 & 0.0 \\ 
  1900 & 0.0 & 0.0 & 0.0 & 0.0 &  0 & 0.0 \\ 
  1901 & 0.0 & 0.0 & 0.0 & 0.0 &  0 & 0.0 \\ 
  1902 & 0.0 & 0.0 & 0.0 & 0.0 &  0 & 0.0 \\ 
  1903 & 0.0 & 0.0 & 0.0 & 0.0 &  0 & 0.0 \\ 
  1904 & 0.0 & 0.0 & 0.0 & 0.0 &  0 & 0.0 \\ 
  1905 & 0.0 & 0.0 & 0.0 & 0.0 &  0 & 0.0 \\ 
  1906 & 0.0 & 0.0 & 0.0 & 0.0 &  0 & 0.0 \\ 
  1907 & 0.0 & 0.0 & 0.0 & 0.0 &  0 & 0.0 \\ 
  1908 & 0.0 & 0.0 & 0.1 & 0.0 &  0 & 0.0 \\ 
  1909 & 0.0 & 0.0 & 0.1 & 0.0 &  0 & 0.0 \\ 
  1910 & 0.0 & 0.0 & 0.1 & 0.0 &  0 & 0.0 \\ 
  1911 & 0.0 & 0.0 & 0.1 & 0.0 &  0 & 0.0 \\ 
  1912 & 0.0 & 0.0 & 0.0 & 0.0 &  0 & 0.0 \\ 
  1913 & 0.0 & 0.0 & 0.0 & 0.0 &  0 & 0.0 \\ 
  1914 & 0.0 & 0.0 & 0.0 & 0.0 &  0 & 0.0 \\ 
  1915 & 0.0 & 0.0 & 0.0 & 0.0 &  0 & 0.0 \\ 
  1916 & 0.0 & 0.0 & 0.4 & 0.0 &  0 & 0.0 \\ 
  1917 & 0.1 & 0.0 & 0.8 & 0.0 &  0 & 0.0 \\ 
  1918 & 0.1 & 0.0 & 1.1 & 0.0 &  0 & 0.0 \\ 
  1919 & 0.0 & 0.0 & 0.4 & 0.0 &  0 & 0.0 \\ 
  1920 & 0.0 & 0.0 & 0.3 & 0.0 &  0 & 0.0 \\ 
  1921 & 0.0 & 0.0 & 0.3 & 0.0 &  0 & 0.0 \\ 
  1922 & 0.0 & 0.0 & 0.1 & 0.0 &  0 & 0.0 \\ 
  1923 & 0.0 & 0.0 & 0.2 & 0.0 &  0 & 0.0 \\ 
  1924 & 0.1 & 0.0 & 0.5 & 0.0 &  0 & 0.0 \\ 
  1925 & 0.1 & 0.0 & 0.6 & 0.0 &  0 & 0.0 \\ 
  1926 & 0.1 & 0.0 & 1.0 & 0.0 &  0 & 0.0 \\ 
  1927 & 0.1 & 0.0 & 1.4 & 0.0 &  0 & 0.0 \\ 
  1928 & 0.1 & 0.1 & 1.2 & 0.0 &  0 & 0.0 \\ 
  1929 & 0.3 & 0.1 & 0.7 & 0.0 &  0 & 0.0 \\ 
  1930 & 0.2 & 0.1 & 0.9 & 0.0 &  0 & 0.0 \\ 
  1931 & 0.4 & 0.1 & 0.4 & 0.0 &  0 & 0.0 \\ 
   \hline
\end{tabular}
\end{table}

\begin{table}[ht]
\centering
\begin{tabular}{>{\centering}p{.5in}>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{1in}>{\centering}p{.75in}>{\centering}p{.75in}}
  \hline
Year & California & Oregon & Washington & At-Sea Hake & Foreign & Research \\ 
  \hline
1932 & 0.3 & 0.1 & 0.4 & 0.0 &  0 & 0.0 \\ 
  1933 & 0.6 & 0.1 & 0.5 & 0.0 &  0 & 0.0 \\ 
  1934 & 0.4 & 0.0 & 2.3 & 0.0 &  0 & 0.0 \\ 
  1935 & 0.4 & 0.1 & 7.7 & 0.0 &  0 & 0.0 \\ 
  1936 & 0.2 & 0.2 & 1.6 & 0.0 &  0 & 0.0 \\ 
  1937 & 0.5 & 0.4 & 2.0 & 0.0 &  0 & 0.0 \\ 
  1938 & 0.6 & 0.1 & 5.1 & 0.0 &  0 & 0.0 \\ 
  1939 & 0.9 & 0.4 & 8.7 & 0.0 &  0 & 0.0 \\ 
  1940 & 0.9 & 9.1 & 12.2 & 0.0 &  0 & 0.0 \\ 
  1941 & 1.3 & 14.0 & 13.6 & 0.0 &  0 & 0.0 \\ 
  1942 & 0.4 & 26.6 & 18.6 & 0.0 &  0 & 0.0 \\ 
  1943 & 1.0 & 94.3 & 453.6 & 0.0 &  0 & 0.0 \\ 
  1944 & 2.8 & 164.5 & 739.3 & 0.0 &  0 & 0.0 \\ 
  1945 & 6.7 & 247.1 & 1887.1 & 0.0 &  0 & 0.0 \\ 
  1946 & 7.3 & 193.2 & 845.9 & 0.0 &  0 & 0.0 \\ 
  1947 & 2.6 & 167.2 & 385.3 & 0.0 &  0 & 0.0 \\ 
  1948 & 3.9 & 177.8 & 491.1 & 0.0 &  0 & 0.0 \\ 
  1949 & 2.0 & 472.9 & 409.5 & 0.0 &  0 & 0.0 \\ 
  1950 & 1.5 & 690.1 & 675.7 & 0.0 &  0 & 0.0 \\ 
  1951 & 4.3 & 840.1 & 735.1 & 0.0 &  0 & 0.0 \\ 
  1952 & 2.9 & 2030.5 & 305.6 & 0.0 &  0 & 0.0 \\ 
  1953 & 145.6 & 1223.5 & 361.6 & 0.0 &  0 & 0.0 \\ 
  1954 & 123.2 & 1837.5 & 538.8 & 0.0 &  0 & 0.0 \\ 
  1955 & 48.8 & 1346.4 & 555.6 & 0.0 &  0 & 0.0 \\ 
  1956 & 3.8 & 2563.8 & 548.2 & 0.0 &  0 & 0.0 \\ 
  1957 & 1.6 & 2128.1 & 538.5 & 0.0 &  0 & 0.0 \\ 
  1958 & 2.9 & 1564.9 & 530.4 & 0.0 &  0 & 0.0 \\ 
  1959 & 1.5 & 892.6 & 337.0 & 0.0 &  0 & 0.0 \\ 
  1960 & 19.6 & 1358.8 & 928.1 & 0.0 &  0 & 0.0 \\ 
  1961 & 1.1 & 2061.9 & 1179.8 & 0.0 &  0 & 0.0 \\ 
  1962 & 0.6 & 2584.9 & 1725.2 & 0.0 &  0 & 0.0 \\ 
  1963 & 32.5 & 3693.9 & 2006.0 & 0.0 &  0 & 0.0 \\ 
  1964 & 46.1 & 4261.6 & 1770.7 & 0.0 &  0 & 0.0 \\ 
  1965 & 34.9 & 5627.8 & 1972.1 & 0.0 &  0 & 0.0 \\ 
  1966 & 5.2 & 1591.2 & 1725.5 & 0.0 & 15561 & 0.0 \\ 
  1967 & 17.8 & 354.7 & 1861.0 & 0.0 & 12357 & 0.0 \\ 
  1968 & 21.9 & 466.4 & 2501.2 & 0.0 & 6639 & 0.0 \\ 
  1969 & 8.4 & 422.3 & 1236.0 & 0.0 & 469 & 0.0 \\ 
  1970 & 8.7 & 507.4 & 1293.3 & 0.0 & 441 & 0.0 \\ 
  1971 & 12.2 & 290.4 & 673.6 & 0.0 & 902 & 0.0 \\ 
  1972 & 11.4 & 105.3 & 796.5 & 0.0 & 950 & 0.0 \\ 
  1973 & 11.9 & 121.2 & 713.1 & 0.0 & 1773 & 0.0 \\ 
  1974 & 15.7 & 136.7 & 641.8 & 0.0 & 1457 & 0.0 \\ 
  1975 & 11.4 & 181.3 & 413.9 & 62.3 & 496 & 0.0 \\ 
  1976 & 17.1 & 663.7 & 521.1 & 31.9 & 239 & 0.0 \\ 
   \hline
\end{tabular}
\end{table}

\begin{table}[ht]
\centering
\begin{tabular}{>{\centering}p{.5in}>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{1in}>{\centering}p{.75in}>{\centering}p{.75in}}
  \hline
Year & California & Oregon & Washington & At-Sea Hake & Foreign & Research \\ 
  \hline
1977 & 16.7 & 457.1 & 752.0 & 3.8 &  0 & 11.9 \\ 
  1978 & 42.5 & 498.7 & 1391.5 & 15.4 &  0 & 0.0 \\ 
  1979 & 136.7 & 735.9 & 581.4 & 15.1 &  0 & 34.5 \\ 
  1980 & 19.2 & 948.6 & 666.2 & 47.0 &  0 & 4.6 \\ 
  1981 & 10.8 & 929.7 & 390.3 & 15.4 &  0 & 0.0 \\ 
  1982 & 145.9 & 584.0 & 273.0 & 28.3 &  0 & 0.0 \\ 
  1983 & 102.0 & 1032.7 & 437.7 & 10.9 &  0 & 4.4 \\ 
  1984 & 47.6 & 750.4 & 815.7 & 2.3 &  0 & 0.9 \\ 
  1985 & 70.9 & 789.5 & 503.2 & 11.4 &  0 & 13.6 \\ 
  1986 & 52.8 & 676.5 & 588.9 & 19.8 &  0 & 1.4 \\ 
  1987 & 120.9 & 550.0 & 399.4 & 5.4 &  0 & 0.0 \\ 
  1988 & 75.4 & 749.8 & 509.8 & 4.5 &  0 & 0.5 \\ 
  1989 & 29.5 & 927.8 & 466.2 & 4.3 &  0 & 4.2 \\ 
  1990 & 18.3 & 567.8 & 427.2 & 80.9 &  0 & 0.0 \\ 
  1991 & 8.4 & 853.2 & 530.1 & 46.1 &  0 & 0.0 \\ 
  1992 & 15.3 & 623.4 & 435.2 & 373.3 &  0 & 4.9 \\ 
  1993 & 11.0 & 797.8 & 464.7 & 0.9 &  0 & 0.2 \\ 
  1994 & 6.7 & 626.4 & 352.0 & 83.8 &  0 & 0.0 \\ 
  1995 & 9.2 & 515.0 & 289.8 & 46.6 &  0 & 2.8 \\ 
  1996 & 18.4 & 531.1 & 236.7 & 6.3 &  0 & 1.2 \\ 
  1997 & 15.8 & 439.1 & 184.9 & 6.4 &  0 & 0.1 \\ 
  1998 & 21.6 & 436.7 & 172.4 & 22.3 &  0 & 3.8 \\ 
  1999 & 19.8 & 326.8 & 145.8 & 16.5 &  0 & 1.4 \\ 
  2000 & 6.8 & 95.1 & 33.0 & 10.1 &  0 & 0.6 \\ 
  2001 & 0.5 & 193.4 & 51.8 & 21.0 &  0 & 2.8 \\ 
  2002 & 0.8 & 107.0 & 39.5 & 3.9 &  0 & 0.3 \\ 
  2003 & 0.2 & 94.6 & 30.2 & 6.3 &  0 & 3.6 \\ 
  2004 & 2.1 & 97.7 & 22.3 & 1.1 &  0 & 2.5 \\ 
  2005 & 0.1 & 51.2 & 10.4 & 1.7 &  0 & 1.8 \\ 
  2006 & 0.2 & 52.2 & 15.8 & 3.1 &  0 & 1.2 \\ 
  2007 & 0.2 & 83.7 & 45.1 & 4.0 &  0 & 0.6 \\ 
  2008 & 0.4 & 58.6 & 16.6 & 15.9 &  0 & 0.8 \\ 
  2009 & 0.9 & 58.7 & 33.2 & 1.6 &  0 & 2.7 \\ 
  2010 & 0.1 & 58.0 & 22.3 & 16.9 &  0 & 1.7 \\ 
  2011 & 0.1 & 30.3 & 19.7 & 9.2 &  0 & 1.9 \\ 
  2012 & 0.2 & 30.4 & 21.8 & 4.5 &  0 & 1.6 \\ 
  2013 & 0.1 & 34.9 & 14.8 & 5.4 &  0 & 1.7 \\ 
  2014 & 0.2 & 33.9 & 15.8 & 3.9 &  0 & 0.6 \\ 
  2015 & 0.1 & 38.1 & 11.4 & 8.7 &  0 & 1.6 \\ 
  2016 & 0.2 & 40.8 & 13.1 & 10.3 &  0 & 3.1 \\ 
  2017 & 0.0 & 13.0 & 0.0 & 0.0 &  0 & 0.0 \\ 
   \hline
\end{tabular}
\end{table}

\begin{table}[ht]
\centering
\caption{West Coast history of regulations.} 
\label{tab:Regs}
\begingroup\fontsize{9pt}{10pt}\selectfont
\begin{tabular}{>{\centering}p{.60in}>{\centering}p{1.0in}>{\raggedright}p{4.20in}}
  \hline
Date & Area & Regulation \\ 
  \hline
11/10/1983 &  Columbia  &  Closed Columbia area to Pacific ocean perch fishing until the end of the year, as 950 mt OY for this species has been reached;  \\ 
  11/10/1983 &  Vancouver  &  retained 5,000-pound trip limit or 10\% of total trip weight on landings of Pacific ocean perch in the Vancouver area.  \\ 
  1/1/1984 &  ALL  &  Continued 5,000-pound trip limit or 10\% of total trip weight on Pacific ocean perch as specified in FMP. Fishery to close when area OYs are reached (see action effective November 10, 1983 above).  \\ 
  8/1/1984 &  Vancouver Columbia  &  Reduced trip limit for Pacific ocean perch in the Vancouver and Columbia areas to 20\% by weight of all fish on board, not to exceed 5,000 pounds per vessel per trip. \\ 
  8/16/1984 &  Columbia  &  Commercial fishing for Pacific ocean perch in the Columbia area closed for remainder of the year. \\ 
  1/10/1985 &  Vancouver Columbia  &  Established Vancouver and Columbia areas Pacific ocean perch trip limit of 20\% by weight of all fish on board (no 5,000-pound limit as specified in last half of 1984). \\ 
  4/28/1985 &  Vancouver Columbia  &  Reduced the Vancouver and Columbia areas Pacific ocean perch trip limit to 5,000 pounds or 20\% by weight of all fish on board, whichever is less.  \\ 
  4/28/1985 &  ALL  &  Landings of Pacific ocean perch less than 1,000 pounds will be unrestricted. The fishery for this species will close when the OY in each area is reached. \\ 
  6/10/1985 &  ALL  &   Landings of Pacific ocean perch up to 1,000 pounds per trip will be unrestricted regardless of the percentage of these fish on board.  \\ 
  1/1/1986 &  Cape Blanco North  &  Established the Pacific ocean perch trip limit north of Cape Blanco (4250) at 20\% (by weight) of all fish on board or 10,000 pounds whichever is less;  \\ 
  1/1/1986 &  ALL  &  landings of Pacific ocean perch unrestricted if less than 1,000 pounds regardless of percentage on board; Vancouver area OY = 600 mt; Columbia area OY =950 mt.  \\ 
  12/1/1986 &  Vancouver  &  OY quota for Pacific ocean perch reached in the Vancouver area; fishery closed until January 1, 1987.  \\ 
  1/1/1987 &  ALL  &  Established coastwide Pacific ocean perch limit at 20\% of all legal fish on board or 5,000 pounds whichever is less (in round weight); landings of Pacific ocean perch unrestricted if less than 1,000 pounds regardless of percentage on board; Vancouver area OY =500 mt; Columbia area OY = 800 mt.  \\ 
  1/1/1988 &  ALL  &  Established the coastwide Pacific ocean perch trip limit at 20\% (by weight) of all fish on board or 5,000 pounds, whichever is less; landings of Pacific ocean perch unrestricted if less than 1,000 pounds regardless of percentage on board;  \\ 
  1/1/1989 &  ALL  &  Established the coastwide Pacific ocean perch trip limit at 20\% (by weight) of all fish on board or 5,000 pounds whichever is less;  \\ 
  1/1/1989 &  ALL  &  landings of Pacific ocean perch unrestricted if less than 1,000 pounds regardless of percentage on board (Vancouver area OY =500 mt; Columbia area OY =800 mt).  \\ 
  7/26/1989 &  ALL  &  Reduced the coastwide trip limit for Pacific ocean perch to 2,000 pounds or 20\% of all fish on board, whichever is less, with no trip frequency restriction.  \\ 
  12/13/1989 &  Columbia  &   Closed the Pacific ocean perch fishery in the Columbia area because 1,040 mt OY reached.  \\ 
  1/1/1990 &  ALL  &  Established the coastwide Pacific ocean perch trip limit at 20\% (by weight) of all fish on board or 3,000 pounds whichever is less; landings of Pacific ocean perch be unrestricted if less than 1,000 pounds regardless of percentage on board.  (Vancouver area OY = 500 mt; Columbia area OY = 1,040 mt). \\ 
  1/1/1991 &  ALL  &  Established the coastwide Pacific ocean perch trip limit at 20\% (by weight) of all groundfish on board or 3,000 pounds whichever is less; landings of Pacific ocean perch be unrestricted if less than 1,000 pounds regardless of percentage on board (harvest guideline for combined Vancouver and Columbia areas = 1,000 mt). \\ 
  1/1/1992 &  ALL  &  For Pacific ocean perch, established the coastwide trip limit at 20\% (by weight) of all groundfish on board or 3,000 pounds whichever is less; landings of Pacific ocean perch be unrestricted if less than 1,000 pounds regardless of percentage on board (harvest guideline for combined Vancouver and Columbia areas = 1,550 mt). \\ 
   \hline
\end{tabular}
\endgroup
\end{table}\begin{table}[ht]
\centering
\begingroup\fontsize{9pt}{10pt}\selectfont
\begin{tabular}{>{\centering}p{.75in}>{\centering}p{.75in}>{\raggedright}p{4.25in}}
  \hline
Date & Area & Regulation \\ 
  \hline
1/1/1993 &  Cape Mendocino Coos Bay  &  For Pacific ocean perch, continued the coastwide trip limit at 20\% (by weight) of all groundfish on board or 3,000 pounds whichever is less; landings of Pacific ocean perch unrestricted if less than 1,000 pounds regardless of percentage on board (harvest guideline for combined Vancouver and Columbia areas = 1,550 mt). \\ 
  1/1/1994 &  ALL  &  Pacific Ocean Perch trip limit of 3,000 pounds or 20\% of all fish on board, whichever is less, in landings of Pacific ocean perch above 1,000 pounds. \\ 
  1/1/1995 &  ALL  &  For Pacific Ocean Perch, established a cumulative trip limit of 6,000 pounds per month \\ 
  1/1/1996 &  ALL  &  Pacific Ocean Perch cumulative trip limit of 10,000 pounds per two-month period. \\ 
  7/1/1996 &  4030 North  &  Reduced the cumulative 2-month limit for Pacific ocean perch to 8,000 pounds, and established the cumulative 2-month limit for Dover sole north of Cape Mendocino at 38,000 pounds \\ 
  1/1/1997 &  ALL  &  Pacific Ocean Perch  limited entry fishery cumulative trip limit of 8,000 pounds per two-month period \\ 
  1/1/1998 &  ALL  &  Pacific Ocean Perch:  limited entry fishery Cumulative trip limit of 8,000 pounds per two-month period. \\ 
  7/1/1998 &  ALL  &  Open Access Rockfish: removed overall rockfish monthly limit and replaced it with limits for component rockfish species: for Sebastes complex, monthly cumulative limit is 33,000 pounds, for widow rockfish, monthly cumulative trip limit is 3,000 pounds, for Pacific Ocean Perch, monthly cumulative trip limit is 4,000 pounds. \\ 
  1/1/1999 &  ALL  &  for the limited entry fishery  A new three phase cumulative limit period system is introduced for 1999.  Phase 1 is a single cumulative limit period that is 3 months long, from January 1 - March 31.  Phase 2 has 3 separate 2 month cumulative limit periods of April 1 -  May 31, June 1 -  July 31, and August 1 - September 30.  Phase 3 has 3 separate 1 month cumulative limit periods of October 1-31, November 1-30, and December 1-31.  For all species except Pacific ocean perch and Bocaccio, there will be no monthly limit within the cumulative landings limit periods.  An option to apply cumulative trip limits lagged by 2 weeks (from the 16th to the 15th) was made available to limited entry trawl vessels when their permits were renewed for 1999.  Vessels that are authorized to operate in this "B" platoon may take and retain, but may not land, groundfish during January 1-15, 1999. \\ 
  1/1/1999 &  ALL  &  for the limited entry fishery Pacific Ocean Perch: cumulative limit, Phase 1: 4,000 pounds per month; Phase 2: 4,000 pounds per month; Phase 3: 4,000 pounds per month. \\ 
  1/1/1999 &  ALL  &  for open access gear: Pacific Ocean Perch: coastwide, 100 pounds per month. \\ 
  1/1/2000 &  ALL  &  Limited entry trawl, Pacific Ocean Perch, 500 lbs per month \\ 
  1/1/2000 &  ALL  &  Pacific Ocean Perch, Open Access gear except exempted trawl, 100 lbs per month \\ 
  1/1/2000 &  ALL  &  Pacific Ocean Perch, limited entry fixed gear, 500 lbs per month \\ 
  5/1/2000 &  ALL  &  Limited entry trawl, Pacific Ocean Perch, 2500 lbs per 2 months \\ 
  5/1/2000 &  ALL  &  Pacific Ocean Perch, limited entry fixed gear, 2500 lbs per month \\ 
  11/1/2000 &  ALL  &  Limited entry trawl, Pacific Ocean Perch, 500 lbs per month \\ 
  11/1/2000 &  ALL  &  Pacific Ocean Perch, limited entry fixed gear, 500 lbs per month \\ 
  1/1/2001 &  3600 North  &  Pacific Ocean Perch, open access, 100 lbs per month \\ 
  1/1/2001 &  4010 North  &  Pacific Ocean Perch, limited entry trawl, 1500 lbs per mont \\ 
  1/1/2001 &  ALL  &  Pacific Ocean Perch, limited entry fixed gear,  1500 lbs per month \\ 
  5/1/2001 &  4010 North  &  Pacific Ocean Perch, limited entry trawl,  2500 lbs per month \\ 
  5/1/2001 &  ALL  &  Pacific Ocean Perch, limited entry fixed gear,  2500 lbs per month \\ 
  10/1/2001 &  4010 North  &  Pacific Ocean Perch, limited entry trawl, 1500 lbs per month \\ 
  11/1/2001 &  ALL  &  Pacific Ocean Perch, limited entry fixed gear,  1500 lbs per month \\ 
  1/1/2002 &  4010 North  &  Pacific Ocean Perch, open access, 100 lbs per month \\ 
  1/1/2002 &  4010 North  &  Pacific Ocean Perch, limited entry fixed gear, 2000 lbs per month \\ 
  1/1/2002 &  4010 North  &  Pacific Ocean Perch, limited entry trawl, 2000 lbs per month \\ 
  4/1/2002 &  4010 North  &  Pacific Ocean Perch, limited entry fixed gear, 4000 lbs per month \\ 
  5/1/2002 &  4010 North  &  Pacific Ocean Perch, limited entry trawl, 4000 lbs per month \\ 
  11/1/2002 &  4010 North  &  Pacific Ocean Perch, limited entry fixed gear, 2000 lbs per month \\ 
  11/1/2002 &  4010 North  &  Pacific Ocean Perch, limited entry trawl, 2000 lbs per month \\ 
  1/1/2003 &  3800 South  &  minor slope rockfish south including pacific ocean perch, open access gear, 10000 lbs per 2 months \\ 
   \hline
\end{tabular}
\endgroup
\end{table}\begin{table}[ht]
\centering
\begingroup\fontsize{9pt}{10pt}\selectfont
\begin{tabular}{>{\centering}p{.75in}>{\centering}p{.75in}>{\raggedright}p{4.25in}}
  \hline
Date & Area & Regulation \\ 
  \hline
1/1/2003 &  3800 South  &  Minor slope rockfish south including Pacific ocean perch, limited entry fixed gear, 30000 lbs per 2 months \\ 
  1/1/2003 &  3800 South  &  Minor slope rockfish south including Pacific ocean perch , limited entry trawl, 30000 lbs per 2 months \\ 
  1/1/2003 &  3800 4010  &  minor slope rockfish south including pacific ocean perch, open access gear, per trip no more than 25\% (by weight) of sablefish landed \\ 
  1/1/2003 &  3800 4010  &  Minor slope rockfish south including Pacific ocean perch, limited entry fixed gear, 1800 lbs per 2 months \\ 
  1/1/2003 &  3800 4010  &  Minor slope rockfish south including Pacific ocean perch , limited entry trawl, 1800 lbs per 2 months \\ 
  1/1/2003 &  4010 North  &  pacific ocean perch, open access gears, 100 lbs per month \\ 
  1/1/2003 &  4010 North  &  pacific ocean perch, limited entry fixed gear, 1800 lbs per 2 months \\ 
  1/1/2003 &  4010 North  &  Pacific Ocean Perch, Limited entry trawl gear, 3000 lbs per 2 months \\ 
  3/1/2003 &  3800 4010  &  Minor slope rockfish south including Pacific ocean perch, limited entry fixed gear, no more than 25\% of the weight of sablefish landed per trip \\ 
  11/1/2003 &  3800 4010  &  Minor slope rockfish south including Pacific ocean perch, limited entry fixed gear, 1800 lbs per 2 months \\ 
  1/1/2004 &  3800 South  &  Minor slope rockfish south including Pacific ocean perch, open access gear, 10000 lbs per 2 months \\ 
  1/1/2004 &  3800 South  &  minor slope rockfish south inclding pacific ocean perch, limited entry fixed gear,  40000 lbs per 2 months \\ 
  1/1/2004 &  3800 South  &  minor slope rockfish south including pacific ocean perch, limited entry trawl, 40000 lbs per 2 months \\ 
  1/1/2004 &  3800 4010  &  Minor slope rockfish south including Pacific ocean perch, open access gear, per trip no more than 25\% of the weight of sablefish landed \\ 
  1/1/2004 &  3800 4010  &  minor slope rockfish south including pacific ocean perch, limited entry fixed gear, 7000 lbs per 2 months \\ 
  1/1/2004 &  3800 4010  &  minor slope rockfish south including pacific ocean perch, limited entry trawl, 7000 lbs per 2 months \\ 
  1/1/2004 &  4010 North  &  pacific ocean perch, open access gear, 100 lbs per month \\ 
  1/1/2004 &  4010 North  &  pacific ocean perch, limited entry fixed gear, 1800 lbs per 2 months \\ 
  1/1/2004 &  4010 North  &  pacific ocean perch, limited entry trawl, 3000 lbs per 2 months \\ 
  5/1/2004 &  3800 South  &  minor slope rockfish south inclding pacific ocean perch, limited entry fixed gear, 50000 lbs per 2 months \\ 
  5/1/2004 &  3800 South  &  minor slope rockfish south including pacific ocean perch, limited entry trawl, 50000 lbs per 2 months \\ 
  5/1/2004 &  3800 4010  &  minor slope rockfish south including pacific ocean perch, limited entry fixed gear,  50000 lbs per 2 months \\ 
  5/1/2004 &  3800 4010  &  minor slope rockfish south including pacific ocean perch, limited entry trawl, 50000 lbs per 2 months \\ 
  11/1/2004 &  3800 South  &  minor slope rockfish south inclding pacific ocean perch, limited entry fixed gear, 50000 lbs per 2 months \\ 
  11/1/2004 &  3800 South  &  minor slope rockfish south including pacific ocean perch, limited entry trawl, 50000 lbs per 2 months \\ 
  11/1/2004 &  3800 4010  &  minor slope rockfish south including pacific ocean perch, limited entry fixed gear, 10000 lbs per 2 months \\ 
  11/1/2004 &  3800 4010  &  minor slope rockfish south including pacific ocean perch, limited entry trawl, 10000 lbs per 2 months \\ 
  1/1/2005 &  3800 South  &  minor slope rockfish south including darkblotched and pacific ocean perch, open access gear, 10000 lbs per 2 months \\ 
  1/1/2005 &  3800 South  &  minor slope rockfish south including darkblotched rockfish and pacific ocean perch, limited entry trawl, closed \\ 
  1/1/2005 &  3800 4010  &  minor slope rockfish south including darkblotched and pacific ocean perch, open access gear, per trip no more than 25\% of weight of sablefish onboard \\ 
  1/1/2005 &  3800 4010  &  minor slope rockfish south including darkblotched rockfish and pacific ocean perch, limited entry trawl, 4000 lbs per 2 months \\ 
  1/1/2005 &  4010 North  &  pacific ocean perch, open access gears, 100 lbs per month \\ 
  1/1/2005 &  4010 North  &  pacific ocean perch, limited entry trawl gear, 3000 lbs per 2 months \\ 
  1/1/2005 &  4010 North  &  pacific ocean perch, limited entry fixed gear, 1800 lbs per 2 months \\ 
  1/1/2005 &  4010 South  &  minor slope rockfish south including darkblotched and pacific ocean perch, limited entry fixed gear, 40000 lbs per 2 months \\ 
  5/1/2005 &  3800 4010  &  minor slope rockfish south including darkblotched rockfish and pacific ocean perch, limited entry trawl, 8000 lbs per 2 months \\ 
   \hline
\end{tabular}
\endgroup
\end{table}\begin{table}[ht]
\centering
\begingroup\fontsize{9pt}{10pt}\selectfont
\begin{tabular}{>{\centering}p{.75in}>{\centering}p{.75in}>{\raggedright}p{4.25in}}
  \hline
Date & Area & Regulation \\ 
  \hline
1/1/2008 &  3800 4010  &  minor slope rockfish south including pacific ocean perch and darkblotched rockfish, limited entry trawl, 15000 lbs per 2 months \\ 
  1/1/2008 &  4010 North  &  pacific ocean perch, limited entry trawl, 1500 lbs per 2 months \\ 
  1/1/2009 &  4010 North  &  pacific ocean perch, limited entry fixed gear, 1800 lbs per 2 months \\ 
  1/1/2009 &  4010 South  &  minor slope rockfish south including pacific ocean perch and darkblotched, limited entry fixed gear, 40000 lbs per 2 months \\ 
  1/1/2009 &  3800 South  &  minor slope rockfish south including pacific ocean perch and darkblotched rockfish, open access gear, 10000 lbs per 2 months \\ 
  1/1/2009 &  3800 4010  &  minor slope rockfish south including pacific ocean perch and darkblotched rockfish, open access gear,  per trip no more than 25\% (by weight) of sablefish landed \\ 
  1/1/2009 &  4010 North  &  pacific ocean perch, open access gears, 100 lbs per month \\ 
  1/1/2009 &  3800 South  &  minor slope rockfish southincluding pacific ocean perch and darkblotched rockfish, limited entry trawl, 55000 lbs per 2 months \\ 
  1/1/2009 &  3800 4010  &  minor slope rockfish south including pacific ocean perch and darkblotched rockfish, limited entry trawl, 15000 lbs per 2 months \\ 
  1/1/2009 &  4010 North  &  pacific ocean perch, limited entry trawl, 1500 lbs per 2 months \\ 
  7/1/2009 &  3800 4010  &  minor slope rockfish south including pacific ocean perch and darkblotched rockfish, limited entry trawl, 10000 lbs per 2 months \\ 
  11/1/2009 &  3800 4010  &  minor slope rockfish south including pacific ocean perch and darkblotched rockfish, limited entry trawl, 15000 lbs per 2 months \\ 
  1/1/2010 &  4010 North  &  pacific ocean perch, limited entry fixed gear, 1800 lbs per 2 months \\ 
  1/1/2010 &  4010 South  &  minor slope rockfish south including pacific ocean perch and darkblotched,limited  entry fixed gear, 40000 lbs per 2 months \\ 
  1/1/2010 &  3800 South  &  minor slope rockfish south including pacific ocean perch and darkblotched rockfish, open access gear, 10000 lbs per 2 months \\ 
  1/1/2010 &  3800 4010  &  minor slope rockfish south including pacific ocean perch and darkblotched rockfish, open access gear,  per trip no more than 25\% (by weight) of sablefish landed \\ 
  1/1/2010 &  4010 North  &  pacific ocean perch, open access gears, 100 lbs per month \\ 
  1/1/2010 &  3800 South  &  minor slope rockfish south including pacific ocean perch and darkblotched rockfish, limited entry trawl, 55000 lbs per 2 months \\ 
  1/1/2010 &  3800 4010  &  minor slope rockfish south including pacific ocean perch and darkblotched rockfish, limited entry trawl, 15000 lbs per 2 months \\ 
  1/1/2010 &  4010 North  &  pacific ocean perch, limited entry trawl, 1500 lbs per 2 months \\ 
  1/1/2011 &  4010 North  &  pacific ocean perch, limited entry fixed gear, 1800 lbs per 2 months \\ 
  1/1/2011 &  4010 South  &  minor slope rockfish south including pacific ocean perch and darkblotched, limited entry fixed gear, 40000 lbs per 2 months \\ 
  1/1/2011 &  3800 South  &  minor slope rockfish south including pacific ocean perch and darkblotched rockfish, open access gear, 10000 lbs per 2 months \\ 
  1/1/2011 &  3800 4010  &  minor slope rockfish south including pacific ocean perch and darkblotched rockfish, open access gear,  per trip no more than 25\% (by weight) of sablefish landed \\ 
  1/1/2011 &  4010 North  &  pacific ocean perch, open access gears, 100 lbs per month \\ 
  1/1/2011 &  ALL  &  Pacific Ocean Perch managed in part by IFQ \\ 
  1/1/2012 &  4010 North  &  pacific ocean perch, limited entry fixed gear, 1800 lbs per 2 months \\ 
  1/1/2012 &  4010 South  &  minor slope rockfish southincluding pacific ocean perch and darkblotched, limited entry fixed gear, 40000 lbs per 2 months \\ 
  1/1/2012 &  3800 South  &  minor slope rockfish south including pacific ocean perch and darkblotched rockfish, open access gear, 10000 lbs per 2 months \\ 
  1/1/2012 &  3800 4010  &  minor slope rockfish south including pacific ocean perch and darkblotched rockfish, open access gear,  per trip no more than 25\% (by weight) of sablefish landed \\ 
  1/1/2012 &  4010 North  &  pacific ocean perch, open access gears, 100 lbs per month \\ 
  1/1/2013 &  4010 North  &  pacific ocean perch, open access gears, 100 lbs per month \\ 
  1/1/2013 &  4010 North  &  pacific ocean perch, limited entry fixed gear, 1800 lbs per 2 months \\ 
  1/1/2013 &  4010 South  &  minor slope rockfish south including pacific ocean perch and darkblotched, limited entry fixed gear, 40000 lbs per 2 months no more than 1375 lbs may be blackgill \\ 
  1/1/2013 &  4010 South  &  minor slope rockfish south including pacific ocean perch and darkblotched rockfish, open access gear,  10000 lbs per 2 months no more than 475 lbs of which may be blackgill rockfish \\ 
  1/1/2014 &  4010 North  &  non-trawl, limited entry, pacific ocean perch, 1800 lbs per 2 months \\ 
  1/1/2014 &  4010 South  &  non-trawl, limited entry, minor slope rockfish and darkblotched rockfish and pacific ocean perch, 40000 lbs per 2 months of which no more than 1375 lbs may be blackgill rockfish \\ 
   \hline
\end{tabular}
\endgroup
\end{table}\begin{table}[ht]
\centering
\begingroup\fontsize{9pt}{10pt}\selectfont
\begin{tabular}{>{\centering}p{.75in}>{\centering}p{.75in}>{\raggedright}p{4.25in}}
  \hline
Date & Area & Regulation \\ 
  \hline
1/1/2014 &  4010 North  &  non-trawl, open access, pacific ocean perch, 100 lbs per month \\ 
  1/1/2014 &  4010 South  &  non-trawl, open access, minor slope rockfish including darkblotched rockfishand pacific ocean perch, 10000 lbs per 2 months of which no more than 475 lbs may be blackgill rockfish \\ 
  1/1/2015 &  4010 North  &  non-trawl, limited entry, pacific ocean perch, 1800 lbs per 2 months \\ 
  1/1/2015 &  4010 South  &  non-trawl, limited entry, minor slope rockfish and darkblotched rockfish and pacific ocean perch, 40000 lbs per 2 months of which no more than 1375 lbs may be blackgill rockfish \\ 
  1/1/2015 &  4010 North  &  non-trawl, open access, pacific ocean perch, 100 lbs per month \\ 
  1/1/2015 &  4010 South  &  non-trawl, open access, minor slope rockfish including darkblotched rockfishand pacific ocean perch, 10000 lbs per 2 months of which no more than 475 lbs may be blackgill rockfish \\ 
  7/1/2015 &  4010 South  &  non-trawl, limited entry, minor slope rockfish and darkblotched rockfish and pacific ocean perch, 40000 lbs per 2 months of which no more than 1600 lbs may be blackgill rockfish \\ 
  7/1/2015 &  4010 South  &  non-trawl, open access, minor slope rockfish including darkblotched rockfishand pacific ocean perch, 10000 lbs per 2 months of which no more than 550 lbs may be blackgill rockfish \\ 
  1/1/2016 &  4010 North  &  non-trawl, limited entry, pacific ocean perch, 1800 lbs per 2 months \\ 
  1/1/2016 &  4010 North  &  non-trawl, open access, pacific ocean perch, 100 lbs per month \\ 
  1/1/2016 &  4010 South  &  non-trawl, open access, minor slope rockfish including darkblotched rockfishand pacific ocean perch, 10000 lbs per 2 months of which no more than 475 lbs may be blackgill rockfish \\ 
  7/1/2016 &  4010 South  &  non-trawl, open access, minor slope rockfish including darkblotched rockfishand pacific ocean perch, 10000 lbs per 2 months of which no more than 550 lbs may be blackgill rockfish \\ 
   \hline
\end{tabular}
\endgroup
\end{table}

\begin{table}[ht]
\centering
\caption{Recent trend in estimated total catch relative to management guidelines.} 
\label{tab:mnmgt_perform_tables}
\begin{tabular}{>{\raggedleft}p{0.5in}>{\centering}p{1.0in}>{\centering}p{1.0in}>{\centering}p{1.0in}>{\centering}p{1.1in}>{\centering}p{1.1in}}
  \hline
Year & OFL (mt; ABC prior to 2011) & ABC (mt) & ACL (mt; OY prior to 2011) & Total landings (mt) & Estimated total catch (mt) \\ 
  \hline
\text{2007} & - & - & 150 & 133 & 157 \\ 
  \text{2008} & - & - & 150 & 92 & 133 \\ 
  \text{2009} & - & - & 189 & 94 & 190 \\ 
  \text{2010} & - & - & 200 & 97 & 181 \\ 
  \text{2011} & - & - & 180 & 60 & 61 \\ 
  \text{2012} & - & - & 183 & 57 & 58 \\ 
  \text{2013} & - & - & 150 & 55 & 57 \\ 
  \text{2014} & - & - & 153 & 54 & 55 \\ 
  \text{2015} & - & - & 158 & 58 & 59 \\ 
  \text{2016} & - & - & 164 & 65 & 65 \\ 
   \hline
\end{tabular}
\end{table}

\begin{table}[ht]
\centering
\caption{Summary of the fishery-independant biomass/abundance
                                         time-series used in the stock
                                         assessment.  The standard error includes the input annual standard error and model estimated added variance.} 
\label{tab:Index_Summary}
\begin{tabular}{>{\centering}p{.4in}>{\centering}p{.5in}>{\centering}p{.3in}>{\centering}p{.5in}>{\centering}p{.3in}>{\centering}p{.5in}>{\centering}p{.3in}>{\centering}p{.5in}>{\centering}p{.3in}>{\centering}p{.5in}>{\centering}p{.3in}}
  \hline
  & \multicolumn{2}{c}{POP} & \multicolumn{2}{c}{Triennial} & \multicolumn{2}{c}{AFSC Slope} & \multicolumn{2}{c}{NWFSC Slope} & \multicolumn{2}{c}{NWFSC Shelf-Slope} \\
 Year & Obs & SE & Obs & SE & Obs & SE & Obs & SE & Obs & SE\\
 \hline
1979 & 56461 & 0.27 & - & - & - & - & - & - & - & - \\ 
  1980 & - & - & 10384 & 0.65 & - & - & - & - & - & - \\ 
  1983 & - & - & 8974 & 0.60 & - & - & - & - & - & - \\ 
  1985 & 34645 & 0.29 & - & - & - & - & - & - & - & - \\ 
  1986 & - & - & 2977 & 0.66 & - & - & - & - & - & - \\ 
  1989 & - & - & 4873 & 0.66 & - & - & - & - & - & - \\ 
  1992 & - & - & 3207 & 0.64 & - & - & - & - & - & - \\ 
  1995 & - & - & 2724 & 0.63 & - & - & - & - & - & - \\ 
  1996 & - & - & - & - & 7621 & 0.51 & - & - & - & - \\ 
  1997 & - & - & - & - & 3807 & 0.51 & - & - & - & - \\ 
  1998 & - & - & 4163 & 0.64 & - & - & - & - & - & - \\ 
  1999 & - & - & - & - & 4694 & 0.50 & 3643 & 0.63 & - & - \\ 
  2000 & - & - & - & - & 4243 & 0.53 & 4120 & 0.58 & - & - \\ 
  2001 & - & - & 1494 & 0.64 & 4187 & 0.49 & 2325 & 0.59 & - & - \\ 
  2002 & - & - & - & - & - & - & 1903 & 0.60 & - & - \\ 
  2003 & - & - & - & - & - & - & - & - & 9646 & 0.37 \\ 
  2004 & - & - & 2922 & 0.68 & - & - & - & - & 5284 & 0.40 \\ 
  2005 & - & - & - & - & - & - & - & - & 7528 & 0.40 \\ 
  2006 & - & - & - & - & - & - & - & - & 6010 & 0.42 \\ 
  2007 & - & - & - & - & - & - & - & - & 6268 & 0.37 \\ 
  2008 & - & - & - & - & - & - & - & - & 3867 & 0.40 \\ 
  2009 & - & - & - & - & - & - & - & - & 2745 & 0.37 \\ 
  2010 & - & - & - & - & - & - & - & - & 5404 & 0.35 \\ 
  2011 & - & - & - & - & - & - & - & - & 7533 & 0.35 \\ 
  2012 & - & - & - & - & - & - & - & - & 9289 & 0.36 \\ 
  2013 & - & - & - & - & - & - & - & - & 8093 & 0.35 \\ 
  2014 & - & - & - & - & - & - & - & - & 4914 & 0.35 \\ 
  2015 & - & - & - & - & - & - & - & - & 5752 & 0.32 \\ 
  2016 & - & - & - & - & - & - & - & - & 11770 & 0.37 \\ 
   \hline
\end{tabular}
\end{table}

\begin{table}[ht]
\centering
\caption{Summary of NWFSC shelf-slope survey length samples used in the stock assessment.} 
\label{tab:NWcombo_Lengths}
\begin{tabular}{>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{1in}}
  \hline
Year & Tows & Fish & Sample Size \\ 
  \hline
2003 & 46 & 80 & 111 \\ 
  2004 & 34 & 56 & 82 \\ 
  2005 & 38 & 81 & 92 \\ 
  2006 & 33 & 73 & 80 \\ 
  2007 & 50 & 74 & 121 \\ 
  2008 & 39 & 75 & 94 \\ 
  2009 & 46 & 61 & 111 \\ 
  2010 & 53 & 73 & 128 \\ 
  2011 & 53 & 72 & 128 \\ 
  2012 & 50 & 79 & 121 \\ 
  2013 & 45 & 76 & 109 \\ 
  2014 & 52 & 77 & 126 \\ 
  2015 & 69 & 67 & 167 \\ 
  2016 & 50 & 58 & 121 \\ 
   \hline
\end{tabular}
\end{table}

\begin{table}[ht]
\centering
\caption{Summary of NWFSC shelf-slope survey age samples used in the stock assessment.} 
\label{tab:NWcombo_Ages}
\begin{tabular}{>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{1in}}
  \hline
Year & Tows & Fish & Sample Size \\ 
  \hline
2003 & 45 & 265 & 109 \\ 
  2004 & 34 & 149 & 82 \\ 
  2005 & 38 & 192 & 92 \\ 
  2006 & 33 & 170 & 80 \\ 
  2007 & 50 & 228 & 121 \\ 
  2008 & 39 & 218 & 94 \\ 
  2009 & 45 & 190 & 109 \\ 
  2010 & 53 & 292 & 128 \\ 
  2011 & 53 & 258 & 128 \\ 
  2012 & 49 & 217 & 119 \\ 
  2013 & 44 & 308 & 106 \\ 
  2014 & 52 & 195 & 126 \\ 
  2015 & 68 & 182 & 165 \\ 
  2016 & 44 & 281 & 106 \\ 
   \hline
\end{tabular}
\end{table}

\begin{table}[ht]
\centering
\caption{Summary of NWFSC slope survey length samples used in the stock assessment.} 
\label{tab:NWslope_Lengths}
\begin{tabular}{>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{1in}}
  \hline
Year & Tows & Fish & Sample Size \\ 
  \hline
2001 & 18 & 27 & 43 \\ 
  2002 & 24 & 54 & 58 \\ 
   \hline
\end{tabular}
\end{table}

\begin{table}[ht]
\centering
\caption{Summary of NWFSC slope survey age samples used in the stock assessment.} 
\label{tab:NWslope_Ages}
\begin{tabular}{>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{1in}}
  \hline
Year & Tows & Fish & Sample Size \\ 
  \hline
2001 & 17 & 125 & 41 \\ 
  2002 & 24 & 216 & 58 \\ 
   \hline
\end{tabular}
\end{table}

\begin{table}[ht]
\centering
\caption{Summary of AFSC slope survey length samples used in the stock assessment.} 
\label{tab:AFSC_Lengths}
\begin{tabular}{>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{1in}}
  \hline
Year & Tows & Fish & Sample Size \\ 
  \hline
1996 & 48 & 1396 & 116 \\ 
  1997 & 21 & 347 & 51 \\ 
  1999 & 21 & 562 & 51 \\ 
  2000 & 19 & 353 & 46 \\ 
  2001 & 23 & 390 & 55 \\ 
   \hline
\end{tabular}
\end{table}

\begin{table}[ht]
\centering
\caption{Summary of Triennial survey length samples used in the stock assessment.} 
\label{tab:TriennialLengths}
\begin{tabular}{>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{1in}}
  \hline
Year & Tows & Fish & Sample Size \\ 
  \hline
1980 & 18 & 1315 & 43 \\ 
  1983 & 40 & 2820 & 97 \\ 
  1986 & 17 & 877 & 41 \\ 
  1989 & 42 & 1851 & 102 \\ 
  1992 & 33 & 1182 & 80 \\ 
  1995 & 71 & 1136 & 172 \\ 
  1998 & 81 & 1482 & 196 \\ 
  2001 & 74 & 669 & 179 \\ 
  2004 & 63 & 1240 & 153 \\ 
   \hline
\end{tabular}
\end{table}

\begin{table}[ht]
\centering
\caption{Summary of Triennial survey age samples used in the stock assessment.} 
\label{tab:Triennial_Ages}
\begin{tabular}{>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{1in}}
  \hline
Year & Tows & Fish & Sample Size \\ 
  \hline
1989 & 15 & 577 & 36 \\ 
  1992 & 10 & 373 & 24 \\ 
  1995 & 12 & 275 & 29 \\ 
  1998 & 28 & 352 & 68 \\ 
  2001 & 43 & 342 & 104 \\ 
  2004 & 57 & 416 & 138 \\ 
   \hline
\end{tabular}
\end{table}

\begin{table}[ht]
\centering
\caption{Summary of Pacific ocean perch survey length samples used in the stock assessment.} 
\label{tab:POP_Lengths}
\begin{tabular}{>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{1in}}
  \hline
Year & Tows & Fish & Sample Size \\ 
  \hline
1979 & 125 & 2375 & 303 \\ 
  1985 & 126 & 2558 & 306 \\ 
   \hline
\end{tabular}
\end{table}

\begin{table}[ht]
\centering
\caption{Summary of Pacific ocean perch survey age samples used in the stock assessment.} 
\label{tab:POP_Ages}
\begin{tabular}{>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{1in}}
  \hline
Year & Tows & Fish & Sample Size \\ 
  \hline
1985 & 29 & 1635 & 70 \\ 
   \hline
\end{tabular}
\end{table}

\begin{table}[ht]
\centering
\caption{Summary of discard rates used in the model by each data source.} 
\label{tab:Discard}
\begin{tabular}{>{\centering}p{.75in}>{\centering}p{1.1in}>{\centering}p{.75in}>{\centering}p{1.1in}}
  \hline
Year & Source & Discard & Standard Error \\ 
  \hline
1985 & Pikitch & 0.027 & 0.068 \\ 
  1986 & Pikitch & 0.024 & 0.063 \\ 
  1987 & Pikitch & 0.039 & 0.083 \\ 
  1992 & Management Restrictions & 0.100 & 0.300 \\ 
  2002 & WCGOP & 0.150 & 0.164 \\ 
  2003 & WCGOP & 0.183 & 0.268 \\ 
  2004 & WCGOP & 0.203 & 0.206 \\ 
  2005 & WCGOP & 0.175 & 0.346 \\ 
  2006 & WCGOP & 0.148 & 0.243 \\ 
  2007 & WCGOP & 0.171 & 0.261 \\ 
  2008 & WCGOP & 0.362 & 0.172 \\ 
  2009 & WCGOP & 0.504 & 0.153 \\ 
  2010 & WCGOP & 0.487 & 0.195 \\ 
  2011 & WCGOP & 0.015 & 0.053 \\ 
  2012 & WCGOP & 0.028 & 0.054 \\ 
  2013 & WCGOP & 0.027 & 0.054 \\ 
  2014 & WCGOP & 0.035 & 0.050 \\ 
  2015 & WCGOP & 0.010 & 0.053 \\ 
   \hline
\end{tabular}
\end{table}

\begin{table}[ht]
\centering
\caption{Summary of the commercial catch-per-unit effort
                                         time-series used in the stock
                                         assessment.} 
\label{tab:CPUE_Summary}
\begin{tabular}{>{\centering}p{.5in}>{\centering}p{.7in}>{\centering}p{.7in}}
  \hline
Year & Obs & SE \\ 
  \hline
1956 & 0.40 & 0.40 \\ 
  1957 & 0.30 & 0.40 \\ 
  1958 & 0.32 & 0.40 \\ 
  1959 & 0.29 & 0.40 \\ 
  1960 & 0.28 & 0.40 \\ 
  1961 & 0.31 & 0.40 \\ 
  1962 & 0.29 & 0.40 \\ 
  1963 & 0.34 & 0.40 \\ 
  1964 & 0.35 & 0.40 \\ 
  1965 & 0.55 & 0.40 \\ 
  1966 & 0.47 & 0.40 \\ 
  1967 & 0.30 & 0.40 \\ 
  1968 & 0.17 & 0.40 \\ 
  1969 & 0.18 & 0.40 \\ 
  1970 & 0.17 & 0.40 \\ 
  1971 & 0.20 & 0.40 \\ 
  1972 & 0.20 & 0.40 \\ 
  1973 & 0.11 & 0.40 \\ 
   \hline
\end{tabular}
\end{table}

\begin{table}[ht]
\centering
\caption{Summary of commercial fishery length samples used in the stock assessment.} 
\label{tab:Comm_Lengths}
\begin{tabular}{>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{1in}}
  \hline
Year & Trips & Fish & Sample Size \\ 
  \hline
1966 & 1 & 238 & 7 \\ 
  1967 & 5 & 1020 & 35 \\ 
  1968 & 3 & 912 & 21 \\ 
  1969 & 4 & 1213 & 28 \\ 
  1970 & 13 & 1830 & 92 \\ 
  1971 & 22 & 4698 & 155 \\ 
  1972 & 23 & 4561 & 162 \\ 
  1973 & 17 & 4134 & 120 \\ 
  1974 & 20 & 4806 & 141 \\ 
  1975 & 19 & 3637 & 134 \\ 
  1976 & 21 & 3677 & 148 \\ 
  1977 & 32 & 4846 & 226 \\ 
  1978 & 52 & 7715 & 367 \\ 
  1979 & 34 & 3414 & 240 \\ 
  1980 & 55 & 5425 & 388 \\ 
  1981 & 40 & 3921 & 282 \\ 
  1982 & 48 & 4824 & 339 \\ 
  1983 & 39 & 3944 & 275 \\ 
  1984 & 31 & 3102 & 219 \\ 
  1985 & 45 & 4508 & 318 \\ 
  1986 & 40 & 4002 & 282 \\ 
  1987 & 43 & 3053 & 304 \\ 
  1988 & 9 & 601 & 64 \\ 
  1989 & 16 & 798 & 113 \\ 
  1990 & 12 & 599 & 85 \\ 
  1991 & 8 & 216 & 38 \\ 
  1994 & 43 & 2608 & 304 \\ 
  1995 & 49 & 3161 & 346 \\ 
  1996 & 64 & 3085 & 452 \\ 
  1997 & 76 & 3570 & 537 \\ 
  1998 & 56 & 3450 & 395 \\ 
  1999 & 58 & 2812 & 409 \\ 
  2000 & 49 & 2004 & 326 \\ 
  2001 & 59 & 1696 & 293 \\ 
  2002 & 50 & 1666 & 280 \\ 
   \hline
\end{tabular}
\end{table}

\begin{table}[ht]
\centering
\begin{tabular}{>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{1in}}
  \hline
Year & Trips & Fish & Sample Size \\ 
  \hline
2003 & 67 & 1661 & 296 \\ 
  2004 & 53 & 1202 & 219 \\ 
  2005 & 51 & 1277 & 227 \\ 
  2006 & 59 & 1486 & 264 \\ 
  2007 & 81 & 2248 & 391 \\ 
  2008 & 101 & 3058 & 523 \\ 
  2009 & 107 & 3207 & 550 \\ 
  2010 & 134 & 2872 & 530 \\ 
  2011 & 100 & 1943 & 368 \\ 
  2012 & 97 & 1873 & 355 \\ 
  2013 & 117 & 2167 & 416 \\ 
  2014 & 140 & 2850 & 533 \\ 
  2015 & 110 & 2504 & 456 \\ 
  2016 & 131 & 2158 & 429 \\ 
   \hline
\end{tabular}
\end{table}

\FloatBarrier

\begin{table}[ht]
\centering
\caption{Summary of commercial fishery age samples used in the stock assessment.} 
\label{tab:Comm_Ages}
\begin{tabular}{>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{1in}}
  \hline
Year & Trips & Fish & Sample Size \\ 
  \hline
1981 & 20 & 1901 & 141 \\ 
  1982 & 40 & 2776 & 282 \\ 
  1983 & 33 & 3317 & 233 \\ 
  1984 & 27 & 2625 & 191 \\ 
  1985 & 21 & 2096 & 148 \\ 
  1986 & 17 & 1693 & 120 \\ 
  1987 & 24 & 1193 & 169 \\ 
  1988 & 4 & 199 & 28 \\ 
  1994 & 8 & 238 & 41 \\ 
  1999 & 18 & 863 & 127 \\ 
  2000 & 14 & 677 & 99 \\ 
  2001 & 40 & 1349 & 226 \\ 
  2002 & 38 & 1414 & 233 \\ 
  2003 & 40 & 1309 & 221 \\ 
  2004 & 30 & 854 & 148 \\ 
  2005 & 37 & 1018 & 177 \\ 
  2006 & 49 & 1258 & 223 \\ 
  2007 & 63 & 1825 & 315 \\ 
  2008 & 44 & 1129 & 200 \\ 
  2009 & 75 & 1548 & 289 \\ 
  2010 & 54 & 1264 & 228 \\ 
  2011 & 85 & 1230 & 255 \\ 
  2012 & 7 & 331 & 49 \\ 
  2013 & 10 & 265 & 47 \\ 
  2014 & 91 & 587 & 172 \\ 
  2015 & 78 & 513 & 149 \\ 
  2016 & 21 & 254 & 56 \\ 
   \hline
\end{tabular}
\end{table}

\FloatBarrier

\begin{table}[ht]
\centering
\caption{Summary of At-Sea hake fishery length samples used in the stock assessment.} 
\label{tab:ASHOP_Lengths}
\begin{tabular}{>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{1in}}
  \hline
Year & Trips & Fish & Sample Size \\ 
  \hline
2003 & 153 & 805 & 263 \\ 
  2004 & 128 & 329 & 172 \\ 
  2005 & 221 & 734 & 321 \\ 
  2006 & 210 & 751 & 312 \\ 
  2007 & 319 & 1119 & 470 \\ 
  2008 & 26 & 2491 & 162 \\ 
  2009 & 12 & 366 & 63 \\ 
  2010 & 22 & 1794 & 155 \\ 
  2011 & 36 & 1748 & 226 \\ 
  2012 & 26 & 881 & 148 \\ 
  2013 & 26 & 834 & 140 \\ 
  2014 & 31 & 532 & 103 \\ 
  2015 & 23 & 925 & 150 \\ 
  2016 & 35 & 1947 & 240 \\ 
   \hline
\end{tabular}
\end{table}

\begin{table}[ht]
\centering
\caption{Summary of At-sea hake fishery age samples used in the stock assessment.} 
\label{tab:ASHOP_Ages}
\begin{tabular}{>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{.75in}>{\centering}p{1in}}
  \hline
Year & Trips & Fish & Sample Size \\ 
  \hline
2003 & 142 & 378 & 194 \\ 
  2006 & 198 & 410 & 255 \\ 
  2007 & 297 & 620 & 383 \\ 
  2014 & 22 & 101 & 36 \\ 
   \hline
\end{tabular}
\end{table}

\FloatBarrier

\begin{table}[ht]
\centering
\caption{Estimated ageing error from the CAPS lab used in the assessment model} 
\label{tab:Age_Error}
\begin{tabular}{>{\centering}p{1.2in}>{\centering}p{1.2in}>{\centering}p{1.2in}>{\centering}p{1.2in}}
  \hline
True Age (yr) & SD of Observed Age (yr) & True Age (yr) & SD of Observed Age (yr) \\ 
  \hline
0.5 & 0.156 & 31.5 & 2.772 \\ 
  1.5 & 0.156 & 32.5 & 2.854 \\ 
  2.5 & 0.249 & 33.5 & 2.935 \\ 
  3.5 & 0.341 & 34.5 & 3.016 \\ 
  4.5 & 0.433 & 35.5 & 3.097 \\ 
  5.5 & 0.524 & 36.5 & 3.177 \\ 
  6.5 & 0.615 & 37.5 & 3.257 \\ 
  7.5 & 0.706 & 38.5 & 3.337 \\ 
  8.5 & 0.796 & 39.5 & 3.416 \\ 
  9.5 & 0.886 & 40.5 & 3.495 \\ 
  10.5 & 0.976 & 41.5 & 3.574 \\ 
  11.5 & 1.065 & 42.5 & 3.652 \\ 
  12.5 & 1.154 & 43.5 & 3.73 \\ 
  13.5 & 1.242 & 44.5 & 3.808 \\ 
  14.5 & 1.33 & 45.5 & 3.885 \\ 
  15.5 & 1.418 & 46.5 & 3.962 \\ 
  16.5 & 1.505 & 47.5 & 4.039 \\ 
  17.5 & 1.592 & 48.5 & 4.115 \\ 
  18.5 & 1.679 & 49.5 & 4.191 \\ 
  19.5 & 1.765 & 50.5 & 4.267 \\ 
  20.5 & 1.851 & 51.5 & 4.342 \\ 
  21.5 & 1.937 & 52.5 & 4.417 \\ 
  22.5 & 2.022 & 53.5 & 4.492 \\ 
  23.5 & 2.107 & 54.5 & 4.566 \\ 
  24.5 & 2.191 & 55.5 & 4.641 \\ 
  25.5 & 2.275 & 56.5 & 4.714 \\ 
  26.5 & 2.359 & 57.5 & 4.788 \\ 
  27.5 & 2.442 & 58.5 & 4.861 \\ 
  28.5 & 2.525 & 59.5 & 4.934 \\ 
  29.5 & 2.608 & 60.5 & 5.007 \\ 
  30.5 & 2.69 &   &   \\ 
   \hline
\end{tabular}
\end{table}

\FloatBarrier

\begin{table}[ht]
\centering
\caption{Specifications of the base model for `r spp`.} 
\label{tab:Model_setup}
\scalebox{0.9}{
\begin{tabular}{>{\raggedright}p{3in}>{\centering}p{2in}}
  \hline
Model Specification & Base Model \\ 
  \hline
Starting year & 1918 \\ 
   &  \\ 
  \underline{Population characteristics} &  \\ 
  Maximum age & 60 \\ 
  Gender & 2 \\ 
  Population lengths & 5-50 cm by 1 cm bins \\ 
  Summary biomass (mt) & Age 3+ \\ 
   &  \\ 
  \underline{Data characteristics} &  \\ 
  Data lengths & 11-47 cm by 1 cm bins \\ 
  Data ages & 1-40 \\ 
  Minimun age for growth calculations & 3 \\ 
  Maximum age for growth calculations & 20 \\ 
  First mature age & 0 \\ 
  Starting year of estimated recruitment & 1940 \\ 
   &  \\ 
  \underline{Fishery characteristics} &  \\ 
  Fishery timing & mid-year \\ 
  Fishing mortality method & discrete \\ 
  Maximum F & 0.9 \\ 
  Catchability & Analytical estimate \\ 
  Fishery selectivity & Double Normal \\ 
  At-Sea Hake selectivity & Double Normal \\ 
  POP survey selectivity & Logistic \\ 
  Triennial survey & Double Normal \\ 
  AFSC slope survey & Double Normal \\ 
  NWFSC slope survey & Double Normal \\ 
  NWFSC shelf/slope survey & Double Normal \\ 
   &  \\ 
  \underline{Fishery time blocks} &  \\ 
  Fishery selectivity & none \\ 
  Fishery retention & 1918-1991, 1992-2001, 2002-2007, 2008, 2009-2010, 2011-2016 \\ 
   \hline
\end{tabular}
}
\end{table}

\FloatBarrier

\begin{table}[ht]
\centering
\caption{Results from 100 jitters from the base model.} 
\label{tab:jitter}
\begin{tabular}{>{\raggedright}p{2in}>{\centering}p{1in}}
  \hline
Status & Base.Model \\ 
  \hline
Returned to base case & - \\ 
  Found local minimum & - \\ 
  Found better solution & - \\ 
  Error in likelihood & - \\ 
  Total & 100 \\ 
   \hline
\end{tabular}
\end{table}

\FloatBarrier

\begin{landscape}
\begin{longtable}{lrcccll}
\caption{List of parameters used in
                                          the base model, including estimated 
                                          values and standard deviations (SD), 
                                          bounds (minimum and maximum), 
                                          estimation phase (negative values indicate
                                          not estimated), status (indicates if 
                                          parameters are near bounds, and prior type
                                          information (mean, SD).} \\ 
  \hline
Parameter & Value & Phase & Bounds & Status & SD & Prior (Exp.Val, SD)  \\ 
  \hline 
\endhead 
\hline 
\multicolumn{3}{l}{\footnotesize Continued on next page} 
\endfoot 
\endlastfoot 
 \hline
NatM\_p\_1\_Fem\_GP\_1 & 0.05 & -5 & (0.02, 0.1) &  &  & Log\_Norm (-2.92, 0.44) \\ 
  L\_at\_Amin\_Fem\_GP\_1 & 20.82 & 3 & (15, 25) & OK & 0.15 & None \\ 
  L\_at\_Amax\_Fem\_GP\_1 & 41.51 & 2 & (35, 45) & OK & 0.16 & None \\ 
  VonBert\_K\_Fem\_GP\_1 & 0.17 & 3 & (0.1, 0.4) & OK & 0.01 & None \\ 
  CV\_young\_Fem\_GP\_1 & 1.33 & 5 & (0.03, 5) & OK & 0.07 & None \\ 
  CV\_old\_Fem\_GP\_1 & 2.58 & 5 & (0.03, 5) & OK & 0.12 & None \\ 
  Wtlen\_1\_Fem & 0.00 & -99 & (0, 3) &  &  & None \\ 
  Wtlen\_2\_Fem & 3.09 & -99 & (2, 4) &  &  & None \\ 
  Mat50\%\_Fem & 32.10 & -99 & (20, 40) &  &  & None \\ 
  Mat\_slope\_Fem & -1.00 & -99 & (-2, 4) &  &  & None \\ 
  Eggs\_scalar\_Fem & 0.00 & -99 & (0, 6) &  &  & None \\ 
  Eggs\_exp\_len\_Fem & 4.98 & -99 & (-3, 5) &  &  & None \\ 
  NatM\_p\_1\_Mal\_GP\_1 & 0.05 & -5 & (0, 0.3) &  &  & Normal (0.05, 0.1) \\ 
  L\_at\_Amin\_Mal\_GP\_1 & 20.82 & -2 & (6, 68) &  &  & None \\ 
  L\_at\_Amax\_Mal\_GP\_1 & 38.80 & 2 & (13, 122) & OK & 0.00 & None \\ 
  VonBert\_K\_Mal\_GP\_1 & 0.20 & 3 & (0.04, 1.09) & OK & 0.04 & None \\ 
  CV\_young\_Mal\_GP\_1 & 1.33 & -5 & (0, 742.07) &  &  & None \\ 
  CV\_old\_Mal\_GP\_1 & 2.32 & 5 & (0, 742.07) & OK & 0.07 & None \\ 
  Wtlen\_1\_Mal & 0.00 & -99 & (0, 3) &  &  & None \\ 
  Wtlen\_2\_Mal & 3.08 & -99 & (2, 4) &  &  & None \\ 
  CohortGrowDev & 1.00 & -99 & (0, 2) &  &  & None \\ 
  FracFemale\_GP\_1 & 0.50 & -99 & (0.01, 0.99) &  &  & None \\ 
  SR\_LN(R0) & 9.36 & 1 & (5, 20) & OK & 0.15 & None \\ 
  SR\_BH\_steep & 0.50 & -2 & (0.2, 1) &  &  & Full\_Beta (0.72, 0.15) \\ 
  SR\_sigmaR & 0.70 & -6 & (0.5, 1.2) &  &  & None \\ 
  SR\_regime & 0.00 & -99 & (-5, 5) &  &  & None \\ 
  SR\_autocorr & 0.00 & -99 & (0, 2) &  &  & None \\ 
  Early\_InitAge\_18 & 0.01 & 3 & (-6, 6) & act & 0.70 & dev (NA, NA) \\ 
  Early\_InitAge\_17 & 0.01 & 3 & (-6, 6) & act & 0.70 & dev (NA, NA) \\ 
  Early\_InitAge\_16 & 0.01 & 3 & (-6, 6) & act & 0.70 & dev (NA, NA) \\ 
  Early\_InitAge\_15 & 0.01 & 3 & (-6, 6) & act & 0.70 & dev (NA, NA) \\ 
  Early\_InitAge\_14 & 0.01 & 3 & (-6, 6) & act & 0.70 & dev (NA, NA) \\ 
  Early\_InitAge\_13 & 0.01 & 3 & (-6, 6) & act & 0.70 & dev (NA, NA) \\ 
  Early\_InitAge\_12 & 0.01 & 3 & (-6, 6) & act & 0.70 & dev (NA, NA) \\ 
  Early\_InitAge\_11 & 0.01 & 3 & (-6, 6) & act & 0.70 & dev (NA, NA) \\ 
  Early\_InitAge\_10 & 0.01 & 3 & (-6, 6) & act & 0.70 & dev (NA, NA) \\ 
  Early\_InitAge\_9 & 0.01 & 3 & (-6, 6) & act & 0.70 & dev (NA, NA) \\ 
  Early\_InitAge\_8 & 0.01 & 3 & (-6, 6) & act & 0.70 & dev (NA, NA) \\ 
  Early\_InitAge\_7 & 0.01 & 3 & (-6, 6) & act & 0.70 & dev (NA, NA) \\ 
  Early\_InitAge\_6 & 0.01 & 3 & (-6, 6) & act & 0.70 & dev (NA, NA) \\ 
  Early\_InitAge\_5 & 0.01 & 3 & (-6, 6) & act & 0.70 & dev (NA, NA) \\ 
  Early\_InitAge\_4 & 0.01 & 3 & (-6, 6) & act & 0.70 & dev (NA, NA) \\ 
  Early\_InitAge\_3 & 0.01 & 3 & (-6, 6) & act & 0.70 & dev (NA, NA) \\ 
  Early\_InitAge\_2 & 0.01 & 3 & (-6, 6) & act & 0.70 & dev (NA, NA) \\ 
  Early\_InitAge\_1 & 0.01 & 3 & (-6, 6) & act & 0.70 & dev (NA, NA) \\ 
  LnQ\_base\_Fishery(1) & -12.37 & -1 & (-15, 15) &  &  & None \\ 
  LnQ\_base\_POP(4) & -0.11 & -1 & (-15, 15) &  &  & None \\ 
  LnQ\_base\_Triennial(5) & -1.84 & -1 & (-15, 15) &  &  & None \\ 
  Q\_extraSD\_Triennial(5) & 0.39 & 2 & (0, 0.5) & OK & 0.15 & None \\ 
  LnQ\_base\_AFSCSlope(6) & -2.47 & -1 & (-15, 15) &  &  & None \\ 
  LnQ\_base\_NWFSCSlope(7) & -2.82 & -1 & (-15, 15) &  &  & None \\ 
  LnQ\_base\_NWFSCcombo(8) & -2.61 & -1 & (-15, 15) &  &  & None \\ 
  Q\_extraSD\_NWFSCcombo(8) & 0.03 & 2 & (0, 0.5) & OK & 0.07 & None \\ 
  SizeSel\_P1\_Fishery(1) & 37.97 & 1 & (20, 45) & OK & 0.18 & None \\ 
  SizeSel\_P2\_Fishery(1) & -5.00 & -2 & (-6, 4) &  &  & None \\ 
  SizeSel\_P3\_Fishery(1) & 3.71 & 3 & (-1, 9) & OK & 0.13 & None \\ 
  SizeSel\_P4\_Fishery(1) & -1.65 & -3 & (-9, 9) &  &  & None \\ 
  SizeSel\_P5\_Fishery(1) & -3.50 & -4 & (-5, 9) &  &  & None \\ 
  SizeSel\_P6\_Fishery(1) & 0.59 & 2 & (-5, 9) & OK & 0.33 & None \\ 
  Retain\_P1\_Fishery(1) & 28.29 & 1 & (15, 45) & OK & 0.34 & None \\ 
  Retain\_P2\_Fishery(1) & 1.07 & 1 & (0.1, 10) & OK & 0.13 & None \\ 
  Retain\_P3\_Fishery(1) & 6.81 & 1 & (-10, 10) & OK & 1.20 & None \\ 
  Retain\_P4\_Fishery(1) & 0.00 & -3 & (0, 0) &  &  & None \\ 
  SizeSel\_P1\_ASHOP(2) & 49.50 & 1 & (20, 49.5) & HI & 0.15 & None \\ 
  SizeSel\_P2\_ASHOP(2) & -5.00 & -2 & (-6, 4) &  &  & None \\ 
  SizeSel\_P3\_ASHOP(2) & 5.02 & 3 & (-1, 9) & OK & 0.20 & None \\ 
  SizeSel\_P4\_ASHOP(2) & 1.00 & -3 & (-1, 9) &  &  & None \\ 
  SizeSel\_P5\_ASHOP(2) & -4.35 & -4 & (-9, 9) &  &  & None \\ 
  SizeSel\_P6\_ASHOP(2) & 999.00 & -2 & (-5, 999) &  &  & None \\ 
  SizeSel\_P1\_POP(4) & 24.60 & 1 & (20, 70) & OK & 2.40 & None \\ 
  SizeSel\_P2\_POP(4) & 11.55 & 3 & (0.001, 50) & OK & 4.31 & None \\ 
  SizeSel\_P1\_Triennial(5) & 27.65 & 1 & (20, 45) & OK & 5.03 & None \\ 
  SizeSel\_P2\_Triennial(5) & -5.00 & -2 & (-6, 4) &  &  & None \\ 
  SizeSel\_P3\_Triennial(5) & 5.50 & -3 & (-1, 9) &  &  & None \\ 
  SizeSel\_P4\_Triennial(5) & 3.26 & 3 & (-1, 9) & OK & 2.34 & None \\ 
  SizeSel\_P5\_Triennial(5) & -5.00 & -4 & (-5, 9) &  &  & None \\ 
  SizeSel\_P6\_Triennial(5) & -0.72 & 2 & (-5, 9) & OK & 0.63 & None \\ 
  SizeSel\_P1\_AFSCSlope(6) & 21.83 & 1 & (20, 45) & OK & 6.89 & None \\ 
  SizeSel\_P2\_AFSCSlope(6) & -5.00 & -2 & (-6, 4) &  &  & None \\ 
  SizeSel\_P3\_AFSCSlope(6) & 1.33 & 3 & (-1, 9) & OK & 6.56 & None \\ 
  SizeSel\_P4\_AFSCSlope(6) & 1.00 & -3 & (-1, 9) &  &  & None \\ 
  SizeSel\_P5\_AFSCSlope(6) & -9.00 & -4 & (-9, 9) &  &  & None \\ 
  SizeSel\_P6\_AFSCSlope(6) & 999.00 & -2 & (-5, 999) &  &  & None \\ 
  SizeSel\_P1\_NWFSCSlope(7) & 36.08 & 1 & (20, 45) & OK & 2.30 & None \\ 
  SizeSel\_P2\_NWFSCSlope(7) & -5.00 & -2 & (-6, 4) &  &  & None \\ 
  SizeSel\_P3\_NWFSCSlope(7) & 1.82 & 3 & (-1, 9) & OK & 1.84 & None \\ 
  SizeSel\_P4\_NWFSCSlope(7) & 1.00 & -3 & (-1, 9) &  &  & None \\ 
  SizeSel\_P5\_NWFSCSlope(7) & -9.00 & -4 & (-9, 9) &  &  & None \\ 
  SizeSel\_P6\_NWFSCSlope(7) & 999.00 & -2 & (-5, 999) &  &  & None \\ 
  SizeSel\_P1\_NWFSCcombo(8) & 21.25 & 1 & (18, 49.5) & OK & 5.70 & None \\ 
  SizeSel\_P2\_NWFSCcombo(8) & -5.00 & -2 & (-6, 4) &  &  & None \\ 
  SizeSel\_P3\_NWFSCcombo(8) & 2.86 & 3 & (-1, 9) & OK & 3.06 & None \\ 
  SizeSel\_P4\_NWFSCcombo(8) & 1.00 & -3 & (-1, 9) &  &  & None \\ 
  SizeSel\_P5\_NWFSCcombo(8) & -9.00 & -4 & (-9, 9) &  &  & None \\ 
  SizeSel\_P6\_NWFSCcombo(8) & 999.00 & -2 & (-5, 999) &  &  & None \\ 
  Retain\_P3\_Fishery(1)\_BLK1repl\_1918 & 3.99 & 4 & (-10, 10) & OK & 0.10 & None \\ 
  Retain\_P3\_Fishery(1)\_BLK1repl\_1992 & 2.31 & 4 & (-10, 10) & OK & 0.37 & None \\ 
  Retain\_P3\_Fishery(1)\_BLK1repl\_2002 & 1.72 & 4 & (-10, 10) & OK & 0.12 & None \\ 
  Retain\_P3\_Fishery(1)\_BLK1repl\_2008 & 0.61 & 4 & (-10, 10) & OK & 0.28 & None \\ 
  Retain\_P3\_Fishery(1)\_BLK1repl\_2009 & -0.02 & 4 & (-10, 10) & OK & 0.24 & None \\ 
   \hline
\hline
\label{tab:model_params}
\end{longtable}
\end{landscape}

\newpage

\begin{table}[ht]
\centering
\caption{Likelihood components from the base model} 
\label{tab:like}
\begin{tabular}{>{\raggedright}p{2in}>{\centering}p{1.0in}}
  \hline
Likelihood Component & Value \\ 
  \hline
Total & 1456.43 \\ 
  Survey & -25.97 \\ 
  Discard & -34.33 \\ 
  Length-frequency data & 133.49 \\ 
  Age-frequency data & 1370.56 \\ 
  Recruitment & 11.67 \\ 
  Forecast Recruitment & 0 \\ 
  Parameter Priors & 1 \\ 
   \hline
\end{tabular}
\end{table}

\FloatBarrier

\begin{table}[ht]
\centering
\caption{Summary of reference 
                                        points and management quantities for the 
                                        base case.} 
\label{tab:Ref_pts}
\begin{tabular}{>{\raggedright}p{4.1in}>{\centering}p{.65in}>{\centering}p{1.4in}}
  \hline
\textbf{Quantity} & \textbf{Estimate} & \textbf{\~95\%  Confidence Interval} \\ 
  \hline
Unfished spawning output (million eggs) & 6558.6 &    4675 -   8442.1 \\ 
  Unfished age 3+ biomass (mt) & 138715 & 99107.7 - 178322.3 \\ 
  Unfished recruitment (R0, thousands) & 11646 &  8776.5 -  15453.6 \\ 
  Spawning output(2017 million eggs) & 4938.6 &  2178.9 -   7698.3 \\ 
  Depletion (2017) & 0.753 &   0.529 -    0.977 \\ 
  \textbf{$\text{Reference points based on } \mathbf{SB_{40\%}}$} &  &  \\ 
  Proxy spawning output ($B_{40\%}$) & 2623.4 &    1870 -   3376.8 \\ 
  SPR resulting in $B_{40\%}$ ($SPR_{B40\%}$) & 0.55 &    0.55 -     0.55 \\ 
  Exploitation rate resulting in $B_{40\%}$ & 0.028 &   0.028 -    0.029 \\ 
  Yield with $SPR_{B40\%}$ at $B_{40\%}$ (mt) & 1732.5 &    1239 -     2226 \\ 
  \textbf{\textit{Reference points based on SPR proxy for MSY}} &  &  \\ 
  Spawning output & 2186.2 &  1558.3 -     2814 \\ 
  $SPR_{proxy}$ & 0.5 &  \\ 
  Exploitation rate corresponding to $SPR_{proxy}$ & 0.033 &   0.033 -    0.034 \\ 
  Yield with $SPR_{proxy}$ at $SB_{SPR}$ (mt) & 1749.5 &  1251.6 -   2247.3 \\ 
  \textbf{\textit{Reference points based on estimated MSY values}} &  &  \\ 
  Spawning output at $MSY$ ($SB_{MSY}$) & 2286 &  1625.3 -   2946.7 \\ 
  $SPR_{MSY}$ & 0.511 &   0.509 -    0.513 \\ 
  Exploitation rate at $MSY$ & 0.032 &   0.032 -    0.033 \\ 
  $MSY$ (mt)  & 1751.3 &  1252.8 -   2249.7 \\ 
   \hline
\end{tabular}
\end{table}

\newpage

\begin{sidewaystable}[ht]
\centering
\caption{Sensitivity of the base model} 
\label{tab:Sensitivity_model1}
\scalebox{0.9}{
\begin{tabular}{l>{\centering}p{.6in}>{\centering}p{.6in}>{\centering}p{.6in}>{\centering}p{.6in}>{\centering}p{.6in}>{\centering}p{.6in}>{\centering}p{.6in}>{\centering}p{.6in}>{\centering}p{.6in}}
  \hline
Label & Base & Harmonic weights & h fixed at prior & Estimate M & Split Triennial & Old Maturity & Old Fecundity & Canadian Data & State Data \\ 
  \hline
Total Likelihood & 1710.07 & 3577.28 & 1711.64 & 1710.07 & 1708.10 & 1711.22 & 1710.23 & 1895.79 & 1868.28 \\ 
  Survey Likelihood & -26.79 & -27.64 & -26.10 & -26.79 & -28.99 & -26.75 & -26.64 & -26.73 & -27.74 \\ 
  Discard Likelihood & -33.87 & -16.74 & -34.03 & -33.88 & -33.91 & -33.92 & -33.89 & -31.88 & -33.89 \\ 
  Length Likelihood & 261.73 & 1502.82 & 263.24 & 261.78 & 261.29 & 262.72 & 261.80 & 396.20 & 346.97 \\ 
  Age Likelihood & 1493.88 & 2094.09 & 1493.50 & 1493.87 & 1494.36 & 1493.83 & 1493.84 & 1538.57 & 1565.31 \\ 
  Recruitment Likelihood & 14.13 & 23.75 & 14.91 & 14.10 & 14.34 & 14.33 & 14.12 & 18.63 & 16.75 \\ 
  Forecast Recruitment Likelihood & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 \\ 
  Parameter Priors Likelihood & 1.00 & 1.00 & 0.13 & 1.00 & 1.00 & 1.00 & 1.00 & 1.00 & 0.88 \\ 
  Parameter Deviation Likelihood & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 \\ 
  log(R0) & 9.32 & 9.17 & 9.38 & 9.35 & 9.36 & 9.32 & 9.33 & 9.19 & 9.20 \\ 
  SB Virgin & 6271.59 & 5536.41 & 6581.18 & 6336.66 & 6476.77 & 6104.39 & 15512600.00 & 5396.25 & 5525.96 \\ 
  SB 2017 & 4710.12 & 3599.86 & 6619.56 & 4886.55 & 5074.80 & 4715.28 & 15243900.00 & 2953.81 & 3649.91 \\ 
  Depletion 2017 & 0.75 & 0.65 & 1.01 & 0.77 & 0.78 & 0.77 & 0.98 & 0.55 & 0.66 \\ 
  Total Yield & 1682.99 & 1453.65 & 2371.62 & 1720.74 & 1744.77 & 1670.84 & 1861.28 & 1475.89 & 1485.95 \\ 
  Steepness & 0.50 & 0.50 & 0.72 & 0.50 & 0.50 & 0.50 & 0.50 & 0.50 & 0.50 \\ 
  Natural Mortality - Female & 0.05 & 0.05 & 0.05 & 0.05 & 0.05 & 0.05 & 0.05 & 0.05 & 0.05 \\ 
  Length at Amin - Female & 20.83 & 20.92 & 20.84 & 20.83 & 20.83 & 20.83 & 20.83 & 20.70 & 20.83 \\ 
  Length at Amax - Female & 41.45 & 41.66 & 41.41 & 41.45 & 41.41 & 41.40 & 41.45 & 41.27 & 41.44 \\ 
  Von Bert. k - Female & 0.17 & 0.17 & 0.17 & 0.17 & 0.17 & 0.17 & 0.17 & 0.17 & 0.17 \\ 
  SD young - Female & 1.31 & 1.37 & 1.32 & 1.31 & 1.32 & 1.32 & 1.31 & 1.30 & 1.31 \\ 
  SD old - Female & 2.69 & 2.83 & 2.69 & 2.69 & 2.69 & 2.69 & 2.69 & 2.82 & 2.69 \\ 
  Natural Mortality - Male & 0.05 & 0.05 & 0.05 & 0.05 & 0.05 & 0.05 & 0.05 & 0.05 & 0.05 \\ 
  Length at Amin - Male & 20.83 & 20.92 & 20.84 & 20.83 & 20.83 & 20.83 & 20.83 & 20.70 & 20.83 \\ 
  Length at Amax - Male & 38.77 & 38.82 & 38.78 & 38.77 & 38.78 & 38.77 & 38.77 & 38.55 & 38.84 \\ 
  Von Bert. k - Male & 0.20 & 0.20 & 0.20 & 0.20 & 0.20 & 0.20 & 0.20 & 0.20 & 0.19 \\ 
  SD young - Male & 1.31 & 1.37 & 1.32 & 1.31 & 1.32 & 1.32 & 1.31 & 1.30 & 1.31 \\ 
  SD old - Male & 2.43 & 2.70 & 2.38 & 2.43 & 2.38 & 2.38 & 2.43 & 2.37 & 2.45 \\ 
   \hline
\end{tabular}
}
\end{sidewaystable}

\FloatBarrier 

\newpage

\begin{longtable}{c>{\centering}p{.5in}>{\centering}p{.65in}>{\centering}p{.6in}>{\centering}p{.6in}>{\centering}p{.5in}>{\centering}p{.60in}>{\centering}p{.45in}c}
\caption{Time-series of population estimates from the base model.} \\ 
  \hline
Year & Total biomass (mt) & Spawning output (million eggs) & Summary biomass 3+ & Relative biomass & Age-0 recruits & Estimated total catch (mt) & 1-SPR & Exp. rate \\ 
  \hline \endhead  \hline
1918 & 139238 & 6575 & 138506 & 1.00 & 11808 & 0 & 0 & 0 \\ 
  1919 & 139284 & 6577 & 138551 & 1.00 & 11814 & 1 & 0 & 0 \\ 
  1920 & 139331 & 6579 & 138598 & 1.00 & 11820 & 0 & 0 & 0 \\ 
  1921 & 139380 & 6581 & 138646 & 1.00 & 11826 & 0 & 0 & 0 \\ 
  1922 & 139430 & 6584 & 138696 & 1.00 & 11833 & 0 & 0 & 0 \\ 
  1923 & 139481 & 6586 & 138746 & 1.00 & 11840 & 0 & 0 & 0 \\ 
  1924 & 139533 & 6588 & 138798 & 1.00 & 11846 & 0 & 0 & 0 \\ 
  1925 & 139586 & 6590 & 138851 & 1.00 & 11853 & 1 & 0 & 0 \\ 
  1926 & 139640 & 6593 & 138905 & 1.00 & 11860 & 1 & 0 & 0 \\ 
  1927 & 139695 & 6595 & 138959 & 1.00 & 11866 & 1 & 0 & 0 \\ 
  1928 & 139751 & 6597 & 139014 & 1.00 & 11872 & 1 & 0 & 0 \\ 
  1929 & 139807 & 6600 & 139070 & 1.00 & 11879 & 1 & 0 & 0 \\ 
  1930 & 139865 & 6603 & 139128 & 1.00 & 11885 & 1 & 0 & 0 \\ 
  1931 & 139924 & 6605 & 139187 & 1.00 & 11890 & 1 & 0 & 0 \\ 
  1932 & 139985 & 6608 & 139246 & 1.01 & 11896 & 1 & 0 & 0 \\ 
  1933 & 140046 & 6611 & 139307 & 1.01 & 11902 & 1 & 0 & 0 \\ 
  1934 & 140107 & 6613 & 139368 & 1.01 & 11909 & 1 & 0 & 0 \\ 
  1935 & 140168 & 6616 & 139428 & 1.01 & 11919 & 3 & 0 & 0 \\ 
  1936 & 140223 & 6618 & 139484 & 1.01 & 11932 & 8 & 0 & 0 \\ 
  1937 & 140287 & 6621 & 139546 & 1.01 & 11951 & 2 & 0 & 0 \\ 
  1938 & 140350 & 6624 & 139609 & 1.01 & 11979 & 3 & 0 & 0 \\ 
  1939 & 140413 & 6627 & 139670 & 1.01 & 12017 & 6 & 0 & 0 \\ 
  1940 & 140474 & 6629 & 139729 & 1.01 & 12305 & 10 & 0.005 & 0 \\ 
  1941 & 140531 & 6631 & 139780 & 1.01 & 12368 & 23 & 0.005 & 0 \\ 
  1942 & 140596 & 6633 & 139831 & 1.01 & 12442 & 30 & 0.01 & 0 \\ 
  1943 & 140669 & 6634 & 139900 & 1.01 & 12522 & 47 & 0.09 & 0 \\ 
  1944 & 140255 & 6610 & 139481 & 1.01 & 12595 & 563 & 0.145 & 0.004 \\ 
  1945 & 139518 & 6570 & 138740 & 1.00 & 12666 & 929 & 0.295 & 0.007 \\ 
  1946 & 137578 & 6469 & 136795 & 0.98 & 12720 & 2194 & 0.165 & 0.016 \\ 
  1947 & 136850 & 6425 & 136062 & 0.98 & 12838 & 1072 & 0.095 & 0.008 \\ 
  1948 & 136692 & 6408 & 135900 & 0.97 & 13040 & 569 & 0.115 & 0.004 \\ 
  1949 & 136470 & 6388 & 135669 & 0.97 & 13343 & 690 & 0.145 & 0.005 \\ 
  1950 & 136096 & 6360 & 135280 & 0.97 & 13773 & 907 & 0.21 & 0.007 \\ 
  1951 & 135309 & 6312 & 134472 & 0.96 & 14304 & 1402 & 0.24 & 0.01 \\ 
  1952 & 134414 & 6256 & 133549 & 0.95 & 14831 & 1620 & 0.325 & 0.012 \\ 
  1953 & 132879 & 6166 & 131982 & 0.94 & 15076 & 2399 & 0.265 & 0.018 \\ 
  1954 & 132142 & 6109 & 131218 & 0.93 & 14847 & 1775 & 0.35 & 0.014 \\ 
  1955 & 130784 & 6019 & 129854 & 0.92 & 14050 & 2564 & 0.295 & 0.02 \\ 
  1956 & 130151 & 5962 & 129246 & 0.91 & 12836 & 2002 & 0.41 & 0.015 \\ 
  1957 & 128424 & 5854 & 127575 & 0.89 & 11604 & 3198 & 0.375 & 0.025 \\ 
  1958 & 127207 & 5777 & 126433 & 0.88 & 10608 & 2739 & 0.315 & 0.022 \\ 
  1959 & 126534 & 5738 & 125831 & 0.87 & 9996 & 2154 & 0.21 & 0.017 \\ 
  1960 & 126627 & 5750 & 125978 & 0.87 & 9899 & 1264 & 0.34 & 0.01 \\ 
  1961 & 125434 & 5716 & 124814 & 0.87 & 10346 & 2367 & 0.43 & 0.019 \\ 
  1962 & 123112 & 5638 & 122489 & 0.86 & 10816 & 3327 & 0.515 & 0.027 \\ 
  1963 & 119571 & 5504 & 118924 & 0.84 & 10055 & 4420 & 0.605 & 0.037 \\ 
  1964 & 114512 & 5291 & 113857 & 0.80 & 8518 & 5876 & 0.635 & 0.052 \\ 
  1965 & 109078 & 5051 & 108482 & 0.77 & 7493 & 6231 & 0.715 & 0.057 \\ 
  1966 & 102014 & 4725 & 101504 & 0.72 & 6979 & 7827 & 0.905 & 0.077 \\ 
  1967 & 83811 & 3856 & 83358 & 0.59 & 6557 & 18968 & 0.9 & 0.228 \\ 
  1968 & 70155 & 3192 & 69730 & 0.49 & 6872 & 14650 & 0.865 & 0.21 \\ 
  1969 & 61613 & 2774 & 61196 & 0.42 & 9434 & 9712 & 0.52 & 0.159 \\ 
  1970 & 60716 & 2728 & 60237 & 0.41 & 14096 & 2183 & 0.54 & 0.036 \\ 
  1971 & 59797 & 2681 & 59153 & 0.41 & 7170 & 2301 & 0.485 & 0.039 \\ 
  1972 & 59466 & 2652 & 58710 & 0.40 & 5097 & 1905 & 0.485 & 0.032 \\ 
  1973 & 59297 & 2620 & 58886 & 0.40 & 4992 & 1888 & 0.585 & 0.032 \\ 
  1974 & 58255 & 2548 & 57941 & 0.39 & 5020 & 2643 & 0.55 & 0.046 \\ 
  1975 & 57460 & 2495 & 57146 & 0.38 & 6274 & 2275 & 0.37 & 0.04 \\ 
  1976 & 57625 & 2505 & 57296 & 0.38 & 4973 & 1183 & 0.43 & 0.021 \\ 
  1977 & 57325 & 2516 & 56953 & 0.38 & 6531 & 1507 & 0.38 & 0.026 \\ 
  1978 & 57144 & 2543 & 56815 & 0.39 & 4827 & 1262 & 0.505 & 0.022 \\ 
  1979 & 56108 & 2524 & 55729 & 0.38 & 5548 & 1998 & 0.43 & 0.036 \\ 
  1980 & 55463 & 2510 & 55152 & 0.38 & 5419 & 1506 & 0.47 & 0.027 \\ 
  1981 & 54525 & 2476 & 54182 & 0.38 & 5721 & 1723 & 0.41 & 0.032 \\ 
  1982 & 53892 & 2453 & 53544 & 0.37 & 8587 & 1381 & 0.345 & 0.026 \\ 
  1983 & 53582 & 2443 & 53178 & 0.37 & 9702 & 1057 & 0.465 & 0.02 \\ 
  1984 & 52783 & 2403 & 52239 & 0.37 & 7109 & 1624 & 0.475 & 0.031 \\ 
  1985 & 52132 & 2358 & 51572 & 0.36 & 7371 & 1658 & 0.435 & 0.032 \\ 
  1986 & 51869 & 2323 & 51427 & 0.35 & 5923 & 1411 & 0.435 & 0.027 \\ 
  1987 & 51717 & 2289 & 51280 & 0.35 & 7095 & 1375 & 0.38 & 0.027 \\ 
  1988 & 51898 & 2271 & 51505 & 0.35 & 9443 & 1107 & 0.44 & 0.021 \\ 
  1989 & 51849 & 2251 & 51368 & 0.34 & 10414 & 1379 & 0.46 & 0.027 \\ 
  1990 & 51847 & 2239 & 51237 & 0.34 & 13831 & 1469 & 0.385 & 0.029 \\ 
  1991 & 52411 & 2250 & 51727 & 0.34 & 6495 & 1124 & 0.455 & 0.022 \\ 
  1992 & 52832 & 2246 & 52101 & 0.34 & 3506 & 1478 & 0.475 & 0.028 \\ 
  1993 & 53301 & 2232 & 52947 & 0.34 & 3522 & 1567 & 0.44 & 0.03 \\ 
  1994 & 53739 & 2230 & 53505 & 0.34 & 10256 & 1418 & 0.39 & 0.026 \\ 
  1995 & 54250 & 2248 & 53924 & 0.34 & 9028 & 1181 & 0.33 & 0.022 \\ 
  1996 & 54913 & 2293 & 54309 & 0.35 & 3937 & 952 & 0.305 & 0.018 \\ 
  1997 & 55674 & 2357 & 55197 & 0.36 & 3860 & 879 & 0.255 & 0.016 \\ 
  1998 & 56446 & 2425 & 56205 & 0.37 & 3222 & 716 & 0.25 & 0.013 \\ 
  1999 & 56980 & 2474 & 56709 & 0.38 & 20289 & 721 & 0.205 & 0.013 \\ 
  2000 & 57644 & 2514 & 57138 & 0.38 & 30894 & 562 & 0.065 & 0.01 \\ 
  2001 & 59050 & 2572 & 57672 & 0.39 & 8763 & 160 & 0.11 & 0.003 \\ 
  2002 & 61164 & 2629 & 59617 & 0.40 & 5261 & 293 & 0.07 & 0.005 \\ 
  2003 & 63945 & 2682 & 63464 & 0.41 & 2742 & 179 & 0.06 & 0.003 \\ 
  2004 & 66532 & 2722 & 66236 & 0.41 & 6934 & 155 & 0.055 & 0.002 \\ 
  2005 & 68891 & 2763 & 68661 & 0.42 & 3436 & 147 & 0.03 & 0.002 \\ 
  2006 & 70975 & 2852 & 70601 & 0.43 & 3940 & 76 & 0.03 & 0.001 \\ 
  2007 & 72705 & 3006 & 72484 & 0.46 & 3885 & 85 & 0.05 & 0.001 \\ 
  2008 & 74189 & 3175 & 73639 & 0.48 & 127258 & 157 & 0.045 & 0.002 \\ 
  2009 & 76377 & 3313 & 74422 & 0.50 & 4856 & 133 & 0.055 & 0.002 \\ 
  2010 & 80661 & 3409 & 74754 & 0.52 & 7683 & 190 & 0.055 & 0.003 \\ 
  2011 & 88142 & 3474 & 87777 & 0.53 & 14600 & 181 & 0.02 & 0.002 \\ 
  2012 & 94770 & 3522 & 94211 & 0.54 & 2130 & 61 & 0.02 & 0.001 \\ 
  2013 & 101402 & 3563 & 100641 & 0.54 & 25607 & 58 & 0.015 & 0.001 \\ 
  2014 & 107678 & 3697 & 107215 & 0.56 & 4445 & 57 & 0.015 & 0.001 \\ 
  2015 & 113278 & 4063 & 112020 & 0.62 & 10066 & 55 & 0.015 & 0 \\ 
  2016 & 118460 & 4535 & 118091 & 0.69 & 10478 & 59 & 0.015 & 0.001 \\ 
  2017 & 122572 & 4939 & 121939 & 0.75 & 10763 & 65 & 0.055 & 0.001 \\ 
  2018 & 125781 & 5239 & 125125 & 0.80 & 10956 & - & - & - \\ 
  2019 & 128314 & 5472 & 127642 & 0.83 & 11095 & - & - & - \\ 
  2020 & 126242 & 5484 & 125560 & 0.83 & 11102 & - & - & - \\ 
  2021 & 123800 & 5461 & 123112 & 0.83 & 11089 & - & - & - \\ 
  2022 & 121154 & 5400 & 120465 & 0.82 & 11053 & - & - & - \\ 
  2023 & 118417 & 5314 & 117730 & 0.81 & 11002 & - & - & - \\ 
  2024 & 115674 & 5215 & 114989 & 0.79 & 10941 & - & - & - \\ 
  2025 & 112978 & 5109 & 112296 & 0.78 & 10875 & - & - & - \\ 
  2026 & 110365 & 4999 & 109688 & 0.76 & 10804 & - & - & - \\ 
  2027 & 107856 & 4889 & 107183 & 0.74 & 10730 & - & - & - \\ 
  2028 & 105461 & 4780 & 104792 & 0.73 & 10655 & - & - & - \\ 
   \hline
\hline
\label{tab:Timeseries_mod1}
\end{longtable}

\FloatBarrier

\newpage

\begin{table}[ht]
\centering
\caption{Projection of potential
                                         OFL, spawning biomass, and depletion for the
                                         base case model.} 
\label{tab:Forecast_mod1}
\begin{tabular}{c>{\centering}p{1in}>{\centering}p{1in}>{\centering}p{1in}>{\centering}p{1in}>{\centering}p{1in}}
  \hline
Year & OFL (mt) & ACL (mt) & Age 3+ biomass (mt) & Spawning Output & Depletion \\ 
  \hline
2017 & 4171 & 281 & 121939 & 4939 & 0.75 \\ 
  2018 & 4402 & 281 & 125125 & 5239 & 0.80 \\ 
  2019 & 4546 & 4346 & 127642 & 5472 & 0.83 \\ 
  2020 & 4476 & 4279 & 125560 & 5484 & 0.84 \\ 
  2021 & 4371 & 4178 & 123112 & 5461 & 0.83 \\ 
  2022 & 4250 & 4063 & 120465 & 5400 & 0.82 \\ 
  2023 & 4125 & 3944 & 117730 & 5314 & 0.81 \\ 
  2024 & 4003 & 3827 & 114989 & 5215 & 0.80 \\ 
  2025 & 3888 & 3717 & 112296 & 5109 & 0.78 \\ 
  2026 & 3782 & 3615 & 109688 & 4999 & 0.76 \\ 
  2027 & 3684 & 3521 & 107183 & 4889 & 0.75 \\ 
  2028 & 3593 & 3435 & 104792 & 4780 & 0.73 \\ 
   \hline
\end{tabular}
\end{table}

\FloatBarrier

\clearpage

\section{Figures}\label{figures}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/catch2 landings stacked.png}
\caption{Total catches Pacific ocean perch through 2016.
\label{fig:Catch}}
\end{figure}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/data_plot.png}
\caption{Summary of data sources used in the Base model.
\label{fig:data_plot}}
\end{figure}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{Figures/Q-Q_plot_combo.jpg}
\caption{Q-Q plots for the VAST lognormal distribution for the NWFSC
shelf-slope survey. \label{fig:nw_qq}}
\end{figure}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/comp_lendat_bubflt8mkt0.png}
\caption{NWFSC shelf-slope survey length frequency distributions for
Pacific ocean perch. \label{fig:nw_Length}}
\end{figure}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/comp_gstagedat_bubflt8mkt0.png}
\caption{NWFSC shelf-slope survey age frequency distributions for
Pacific ocean perch. \label{fig:nw_Age}}
\end{figure}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{Figures/Q-Q_plot_nw_slope_gammaECE.jpg}
\caption{Q-Q plots for the VAST lognormal distribution for the NWFSC
slope survey. \label{fig:nw_slope_qq}}
\end{figure}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/comp_lendat_bubflt7mkt0.png}
\caption{NWFSC slope survey length frequency distributions for Pacific
ocean perch. \label{fig:nw_slope_Length}}
\end{figure}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/comp_agedat_bubflt7mkt0.png}
\caption{NWFSC slope survey age frequency distributions for Pacific
ocean perch. \label{fig:nw_slope_Age}}
\end{figure}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{Figures/Q-Q_plot_afsc.jpg}
\caption{Q-Q plots for the VAST lognormal distribution for the AFSC
slope survey. \label{fig:afsc_qq}}
\end{figure}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/comp_lendat_bubflt6mkt0.png}
\caption{AFSC slope survey length frequency distributions for Pacific
ocean perch. \label{fig:afsc_Length}}
\end{figure}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{Figures/Q-Q_plot_triennial.jpg}
\caption{Q-Q plots for the VAST lognormal distribution for the Triennial
survey. \label{fig:tri_qq}}
\end{figure}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/comp_lendat_bubflt5mkt0.png}
\caption{Triennial survey length frequency distributions for Pacific
ocean perch. \label{fig:Tri_Length}}
\end{figure}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/comp_agedat_bubflt5mkt0.png}
\caption{Triennial survey age frequency distributions for Pacific ocean
perch. \label{fig:Tri_Age}}
\end{figure}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{Figures/Q-Q_plot_pop.jpg}
\caption{Q-Q plots for the VAST lognormal distribution for the Pacific
ocean perch survey. \label{fig:pop_qq}}
\end{figure}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/comp_lendat_bubflt4mkt0.png}
\caption{Pacific ocean perch survey length frequency distributions for
Pacific ocean perch. \label{fig:POP_Length}}
\end{figure}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/comp_agedat_bubflt4mkt0.png}
\caption{Pacific ocean perch survey age frequency distributions for
Pacific ocean perch. \label{fig:POP_Age}}
\end{figure}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/comp_lendat_bubflt1mkt1.png}
\caption{Discard length frequency distributions from WCGOP for Pacific
ocean perch. \label{fig:WCGOP_discard}}
\end{figure}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/comp_lendat_bubflt1mkt2_page2.png}
\caption{Commercial fishery length frequency distributions for Pacific
ocean perch. \label{fig:Comm_Length}}
\end{figure}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/comp_agedat_bubflt1mkt2.png}
\caption{Commercial fishery age frequency distributions for Pacific
ocean perch. \label{fig:Comm_Age}}
\end{figure}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/comp_lendat_bubflt2mkt0.png}
\caption{At-Sea hake fishery length frequency distributions for Pacific
ocean perch. \label{fig:ASHOP_Length}}
\end{figure}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/comp_agedat_bubflt2mkt0.png}
\caption{At-Sea hake fishery age frequency distributions for Pacific
ocean perch. \label{fig:ASHOP_Age}}
\end{figure}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{Figures/allSexRatios.png}
\caption{The estimated sex ratio of Pacific ocean perch at length from
all biological data sources. \label{fig:sexratio}}
\end{figure}

\begin{figure}
\centering
\includegraphics{Figures/allSexRatiosAge.png}
\caption{The estimated sex ratio of Pacific ocean perch at age from all
biological data sources. \label{fig:sexratio_Age}}
\end{figure}

\begin{figure}
\centering
\includegraphics{Figures/Functional_Maturity.png}
\caption{The estimated functional maturity Pacific ocean perch at
length. \label{fig:mat}}
\end{figure}

\begin{figure}
\centering
\includegraphics{Figures/Maturity_Comparison.png}
\caption{Comparison between estimated maturity-at-length used in this
assessment and maturity-at-age applied in the 2011 assessment of Pacific
ocean perch. \label{fig:mat_compare}}
\end{figure}

\begin{figure}
\centering
\includegraphics{r4ss/plots_mod1/bio9_fecundity_len.png}
\caption{Fecundity at length of Pacific ocean perch in the Base model.
\label{fig:fecundity}}
\end{figure}

\FloatBarrier 

\begin{figure}
\centering
\includegraphics{Figures/weightAtLengthBySource.png}
\caption{Weight-at-length for Pacific ocean perch from all data sources.
\label{fig:Wt_len}}
\end{figure}

\FloatBarrier 

\begin{figure}
\centering
\includegraphics{Figures/weightAtLengthPred.png}
\caption{Estimated weight-at-length for Pacific ocean perch from all
data sources. \label{fig:Wt_len_pred}}
\end{figure}

\FloatBarrier 

\begin{figure}
\centering
\includegraphics{Figures/LengthAgeAll.png}
\caption{Estimated length-at-age for Pacific ocean perch from all data
sources. \label{fig:Len_Age}}
\end{figure}

\FloatBarrier 

\begin{figure}
\centering
\includegraphics{Figures/Ageing_Error.png}
\caption{The estimated ageing error used in this assessment compared to
the ageing error assumed in the previous assessment for Pacific ocean
perch. \label{fig:Age_Error}}
\end{figure}

\FloatBarrier 

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_flt1mkt1.png}
\caption{Length comps, discard, Fishery
\label{fig:mod1_1_comp_lenfit_flt1mkt1}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_residsflt1mkt1.png}
\caption{Pearson residuals, discard, Fishery (max=3.7)\\
Closed bubbles are positive residuals (observed \textgreater{} expected)
and open bubbles are negative residuals (observed \textless{} expected).
\label{fig:mod1_2_comp_lenfit_residsflt1mkt1}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_sampsize_flt1mkt1.png}
\caption{N\_EffN comparison, Length comps, discard, Fishery
\label{fig:mod1_3_comp_lenfit_sampsize_flt1mkt1}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_data_weighting_TA1.8_Fishery.png}
\caption{Francis data weighting method TA1.8: Fishery Suggested sample
size adjustment (with 95\% interval) for len data from Fishery: 0.9912
(0.6564\_1.8145) For more info, see Francis, R.I.C.C. (2011). Data
weighting in statistical fisheries stock assessment models. Can. J.
Fish. Aquat. Sci. 68: 1124\_1138.
\label{fig:mod1_4_comp_lenfit_data_weighting_TA1.8_Fishery}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_flt1mkt2_page1.png}
\caption{Length comps, retained, Fishery (plot 1 of 2)
\label{fig:mod1_5_comp_lenfit_flt1mkt2_page1}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_flt1mkt2_page2.png}
\caption{Length comps, retained, Fishery (plot 1 of 2) (plot 2 of 2)
\label{fig:mod1_6_comp_lenfit_flt1mkt2_page2}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_residsflt1mkt2_page2.png}
\caption{Pearson residuals, retained, Fishery (max=3.25) (plot 2 of 2)\\
Closed bubbles are positive residuals (observed \textgreater{} expected)
and open bubbles are negative residuals (observed \textless{} expected).
\label{fig:mod1_7_comp_lenfit_residsflt1mkt2_page2}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_sampsize_flt1mkt2.png}
\caption{N\_EffN comparison, Length comps, retained, Fishery
\label{fig:mod1_8_comp_lenfit_sampsize_flt1mkt2}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_data_weighting_TA1.8_Fishery.png}
\caption{Francis data weighting method TA1.8: Fishery Suggested sample
size adjustment (with 95\% interval) for len data from Fishery: 0.9912
(0.648\_1.8415) For more info, see Francis, R.I.C.C. (2011). Data
weighting in statistical fisheries stock assessment models. Can. J.
Fish. Aquat. Sci. 68: 1124\_1138.
\label{fig:mod1_9_comp_lenfit_data_weighting_TA1.8_Fishery}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_flt2mkt0.png}
\caption{Length comps, whole catch, ASHOP
\label{fig:mod1_10_comp_lenfit_flt2mkt0}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_residsflt2mkt0.png}
\caption{Pearson residuals, whole catch, ASHOP (max=2.16)\\
Closed bubbles are positive residuals (observed \textgreater{} expected)
and open bubbles are negative residuals (observed \textless{} expected).
\label{fig:mod1_11_comp_lenfit_residsflt2mkt0}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_sampsize_flt2mkt0.png}
\caption{N\_EffN comparison, Length comps, whole catch, ASHOP
\label{fig:mod1_12_comp_lenfit_sampsize_flt2mkt0}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_data_weighting_TA1.8_ASHOP.png}
\caption{Francis data weighting method TA1.8: ASHOP Suggested sample
size adjustment (with 95\% interval) for len data from ASHOP: 1.0145
(0.5321\_4.5796) For more info, see Francis, R.I.C.C. (2011). Data
weighting in statistical fisheries stock assessment models. Can. J.
Fish. Aquat. Sci. 68: 1124\_1138.
\label{fig:mod1_13_comp_lenfit_data_weighting_TA1.8_ASHOP}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_flt4mkt0.png}
\caption{Length comps, whole catch, POP
\label{fig:mod1_14_comp_lenfit_flt4mkt0}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_residsflt4mkt0.png}
\caption{Pearson residuals, whole catch, POP (max=1.71)\\
Closed bubbles are positive residuals (observed \textgreater{} expected)
and open bubbles are negative residuals (observed \textless{} expected).
\label{fig:mod1_15_comp_lenfit_residsflt4mkt0}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_sampsize_flt4mkt0.png}
\caption{N\_EffN comparison, Length comps, whole catch, POP
\label{fig:mod1_16_comp_lenfit_sampsize_flt4mkt0}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_data_weighting_TA1.8_POP.png}
\caption{Francis data weighting method TA1.8: POP Suggested sample size
adjustment (with 95\% interval) for len data from POP: 7.1361
(7.1361\_Inf) For more info, see Francis, R.I.C.C. (2011). Data
weighting in statistical fisheries stock assessment models. Can. J.
Fish. Aquat. Sci. 68: 1124\_1138.
\label{fig:mod1_17_comp_lenfit_data_weighting_TA1.8_POP}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_flt5mkt0.png}
\caption{Length comps, whole catch, Triennial
\label{fig:mod1_18_comp_lenfit_flt5mkt0}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_residsflt5mkt0.png}
\caption{Pearson residuals, whole catch, Triennial (max=3.95)\\
Closed bubbles are positive residuals (observed \textgreater{} expected)
and open bubbles are negative residuals (observed \textless{} expected).
\label{fig:mod1_19_comp_lenfit_residsflt5mkt0}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_sampsize_flt5mkt0.png}
\caption{N\_EffN comparison, Length comps, whole catch, Triennial
\label{fig:mod1_20_comp_lenfit_sampsize_flt5mkt0}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_data_weighting_TA1.8_Triennial.png}
\caption{Francis data weighting method TA1.8: Triennial Suggested sample
size adjustment (with 95\% interval) for len data from Triennial: 1.0167
(0.5447\_5.8308) For more info, see Francis, R.I.C.C. (2011). Data
weighting in statistical fisheries stock assessment models. Can. J.
Fish. Aquat. Sci. 68: 1124\_1138.
\label{fig:mod1_21_comp_lenfit_data_weighting_TA1.8_Triennial}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_flt6mkt0.png}
\caption{Length comps, whole catch, AFSCSlope
\label{fig:mod1_22_comp_lenfit_flt6mkt0}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_residsflt6mkt0.png}
\caption{Pearson residuals, whole catch, AFSCSlope (max=2.86)\\
Closed bubbles are positive residuals (observed \textgreater{} expected)
and open bubbles are negative residuals (observed \textless{} expected).
\label{fig:mod1_23_comp_lenfit_residsflt6mkt0}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_sampsize_flt6mkt0.png}
\caption{N\_EffN comparison, Length comps, whole catch, AFSCSlope
\label{fig:mod1_24_comp_lenfit_sampsize_flt6mkt0}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_data_weighting_TA1.8_AFSCSlope.png}
\caption{Francis data weighting method TA1.8: AFSCSlope Suggested sample
size adjustment (with 95\% interval) for len data from AFSCSlope: 1.0029
(0.5859\_22.5669) For more info, see Francis, R.I.C.C. (2011). Data
weighting in statistical fisheries stock assessment models. Can. J.
Fish. Aquat. Sci. 68: 1124\_1138.
\label{fig:mod1_25_comp_lenfit_data_weighting_TA1.8_AFSCSlope}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_flt7mkt0.png}
\caption{Length comps, whole catch, NWFSCSlope
\label{fig:mod1_26_comp_lenfit_flt7mkt0}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_residsflt7mkt0.png}
\caption{Pearson residuals, whole catch, NWFSCSlope (max=3.44)\\
Closed bubbles are positive residuals (observed \textgreater{} expected)
and open bubbles are negative residuals (observed \textless{} expected).
\label{fig:mod1_27_comp_lenfit_residsflt7mkt0}}
\end{figure}

\begin{figure}
\centering
\includegraphics{./r4ss/plots_mod1/comp_lenfit_sampsize_flt7mkt0.png}
\caption{N\_EffN comparison, Length comps, whole catch, NWFSCSlope
\label{fig:mod1_28_comp_lenfit_sampsize_flt7mkt0}}
\end{figure}

\FloatBarrier

\FloatBarrier

\FloatBarrier

\FloatBarrier

\FloatBarrier

\begin{figure}
\centering
\includegraphics{Figures/compare1_spawnbio.png}
\caption{Retrospective pattern for spawning output.
\label{fig:retro_sb}}
\end{figure}

\FloatBarrier

\begin{figure}
\centering
\includegraphics{Figures/compare9_recdevs.png}
\caption{Retrospective pattern for estimated recruitment deviations.
\label{fig:retro_recdev}}
\end{figure}

\FloatBarrier

\FloatBarrier

\FloatBarrier

\newpage

\color{black}

\section*{References}\label{references}
\addcontentsline{toc}{section}{References}

\renewcommand{\thepage}{}

\hypertarget{refs}{}
\hypertarget{ref-bradburn_2003_2011}{}
Bradburn, M., Keller, A., and Horness, B. 2011. The 2003 to 2008 US West
Coast bottom trawl surveys of groundfish resources off Washington,
Oregon, and California: Estimates of distribution, abundance, length,
and age composition. US Department of Commerce, National Oceanic;
Atmospheric Administration, National Marine Fisheries Service.

\hypertarget{ref-chilton_age_1982}{}
Chilton, D.E., and Beamish, R.J. 1982. Age determination methods for
fishes studied by the Groundfish Program at the Pacific Biological
Station. {[}Ottawa:{]} Minister of Supply; Services Canada.

\hypertarget{ref-dick_meta-analysis_2017}{}
Dick, E., Beyer, S., Mangel, M., and Ralston, S. 2017. A meta-analysis
of fecundity in rockfishes (genus \emph{Sebastes}). Fisheries Research
\textbf{187}: 73--85. doi:
\href{https://doi.org/10.1016/j.fishres.2016.11.009}{10.1016/j.fishres.2016.11.009}.

\hypertarget{ref-dick_modeling_2009}{}
Dick, E.J. 2009. Modeling the Reproductive Potential of Rockfishes
(\emph{Sebastes} Spp.). ProQuest. Available from
\url{http://books.google.com/books?hl=en\&lr=\&id=0d6-3rhfynkC\&oi=fnd\&pg=PR7\&dq=\%22Synthesis+of+findings+regarding+the+reproductive\%22+\%22C:+Linear+interpolation+algorithms\%22+\%22for+yellowtail+rockfish+(S.+flavidus)\%22+\%22greater+than+zero,+based+on+the+2-level+relative+fecundity\%22+\%22A:+Methods+for+data+recovery+from+published\%22+\&ots=NR0UylgymD\&sig=58IaN_a3pJeYTPYVmJ1NYMABmvE}
{[}accessed 27 February 2017{]}.

\hypertarget{ref-francis_data_2011}{}
Francis, R.C., and Hilborn, R. 2011. Data weighting in statistical
fisheries stock assessment models. Canadian Journal of Fisheries and
Aquatic Sciences \textbf{68}(6): 1124--1138. doi:
\href{https://doi.org/10.1139/f2011-025}{10.1139/f2011-025}.

\hypertarget{ref-gunderson_population_1977}{}
Gunderson, D.R. 1977. Population biology of Pacific ocean perch,
\emph{Sebastes alutus}, stocks in the WashingtonQueen Charlotte Sound
region and their response to fishing. Fishery Bulletin \textbf{75}:
369--403. Available from
\url{http://fishbull.noaa.gov/75-2/gunderson.pdf} {[}accessed 27
February 2017{]}.

\hypertarget{ref-gunderson_results_1978}{}
Gunderson, D.R. 1978. Results of cohort analysis for Pacific ocean perch
stocks off British Columbia, Washington, and Oregon and an evaluation of
alternative rebuilding strategies for these stocks. Pacific Fishery
Management Council, 7700 Ambassador Place NE, Suite 200, Portland, OR
97220.

\hypertarget{ref-gunderson_updated_1981}{}
Gunderson, D.R. 1981. An updated cohort analysis for Pacific ocean perch
stocks off Washington and Oregon. Unpublished report, Pacific Fishery
Management Council, 7700 Ambassador Place NE, Suite 200, Portland, OR
97220.

\hypertarget{ref-gunderson_trade-off_1997}{}
Gunderson, D.R. 1997. Trade-off between reproductive effort and adult
survival in oviparous and viviparous fishes. Canadian Journal of
Fisheries and Aquatic Sciences \textbf{54}(5): 990--998. Available from
\url{http://www.nrcresearchpress.com/doi/abs/10.1139/f97-019}
{[}accessed 27 February 2017{]}.

\hypertarget{ref-gunderson_distribution_1980}{}
Gunderson, D.R., and Sample, T.M. 1980. Distribution and abundance of
rockfish off Washington, Oregon and California during 1977. Northwest;
Alaska Fisheries Center, National Marine Fisheries Service. Available
from \url{http://spo.nmfs.noaa.gov/mfr423-4/mfr423-42.pdf} {[}accessed
28 February 2017{]}.

\hypertarget{ref-gunderson_status_1977}{}
Gunderson, D.R., Westrheim, S., Demory, R., and Fraidenburg, M. 1977.
The status of Pacific ocean perch (\emph{Sebastes alutus}) stocks off
British Columbia, Washington, and Oregon in 1974.

\hypertarget{ref-hamel_method_2015}{}
Hamel, O.S. 2015. A method for calculating a meta-analytical prior for
the natural mortality rate using multiple life history correlates. ICES
Journal of Marine Science: Journal du Conseil \textbf{72}(1): 62--69.
doi:
\href{https://doi.org/10.1093/icesjms/fsu131}{10.1093/icesjms/fsu131}.

\hypertarget{ref-hamel_stock_2011}{}
Hamel, O.S., and Ono, K. 2011. Stock Assessment of Pacific Ocean Perch
in Waters off of the U.S. West Coast in 2011. Pacific Fishery Management
Council, 7700 Ambassador Place NE, Suite 200, Portland, OR 97220.

\hypertarget{ref-hannah_age-modulated_2007}{}
Hannah, R., and Parker, S. 2007. Age-modulated variation in reproductive
development of female Pacific Ocean perch (\emph{Sebastes alutus}) in
waters off Oregon. Alaska Sea Grant, University of Alaska Fairbanks. pp.
1--20. doi:
\href{https://doi.org/10.4027/bamnpr.2007.01}{10.4027/bamnpr.2007.01}.

\hypertarget{ref-helser_generalized_2004}{}
Helser, T., Punt, A.E., and Methot, R.D. 2004. A generalized linear
mixed model analysis of a multi-vessel fishery resouce survey.
\textbf{70}: 251--264.

\hypertarget{ref-hoenig_empirical_1983}{}
Hoenig, J.M. 1983. Empirical use of longevity data to estimate mortality
rates. Fishery Bulletin \textbf{82}: 898--903. Available from
\url{http://fishbull.noaa.gov/81-4/hoenig.pdf} {[}accessed 28 February
2017{]}.

\hypertarget{ref-ianelli_status_1998}{}
Ianelli, J.N., and Zimmermann, M. 1998. Status and future prospects for
the Pacific ocean perch resource in waters off Washington and Oregon as
assessed in 1998. Pacific Fishery Management Council, 7700 Ambassador
Place NE, Suite 200, Portland, OR 97220.

\hypertarget{ref-ianelli_status_1992}{}
Ianelli, J.N., Ito, D.H., and Wilkins, M. 1992. Status and future
prospects for the Pacific ocean perch resource in waters off Washington
and Oregon as assessed in 1992. Pacific Fishery Management Council, 7700
Ambassador Place NE, Suite 200, Portland, OR 97220.

\hypertarget{ref-karnowski_historical_2014}{}
Karnowski, M., Gertseva, V., and Stephens, A. 2014. Historical
Reconstruction of Oregon's Commercial Fisheries Landings. Oregon
Department of Fish; Wildlife, Salem, OR.

\hypertarget{ref-kristensen_tmb:_2016}{}
Kristensen, K., Nielsen, A., Berg, C.W., Skaug, H.J., and Bell, B. 2016.
TMB: Automatic Differentiation and Laplace Approximation. Journal of
Statistical Software \textbf{70}: 1--21.

\hypertarget{ref-mcallister_bayesian_1997}{}
McAllister, M.K., and Ianelli, J.N. 1997. Bayesian stock assessment
using catch-age data and the sampling - importance resampling algorithm.
Canadian Journal of Fisheries and Aquatic Sciences \textbf{54}:
284--300. Available from
\url{http://www.nrcresearchpress.com/doi/pdf/10.1139/f96-285}
{[}accessed 10 March 2017{]}.

\hypertarget{ref-mccoy_predicting_2008}{}
McCoy, M.W., and Gillooly, J.F. 2008. Predicting natural mortality rates
of plants and animals. Ecology Letters \textbf{11}(7): 710--716. doi:
\href{https://doi.org/10.1111/j.1461-0248.2008.01190.x}{10.1111/j.1461-0248.2008.01190.x}.

\hypertarget{ref-methot_stock_2013}{}
Methot, R.D., and Wetzel, C.R. 2013. Stock synthesis: A biological and
statistical framework for fish stock assessment and fishery management.
Fisheries Research \textbf{142}: 86--99. doi:
\href{https://doi.org/10.1016/j.fishres.2012.10.012}{10.1016/j.fishres.2012.10.012}.

\hypertarget{ref-methot_adjusting_2011}{}
Methot, R.D., Taylor, I.G., and Chen, Y. 2011. Adjusting for bias due to
variability of estimated recruitments in fishery assessment models.
Canadian Journal of Fisheries and Aquatic Sciences \textbf{68}(10):
1744--1760. doi:
\href{https://doi.org/10.1139/f2011-092}{10.1139/f2011-092}.

\hypertarget{ref-pikitch_evaluation_1988}{}
Pikitch, E.K., Erickson, D.L., and Wallace, J.R. 1988. An evaluation of
the effectiveness of trip limits as a management tool. Northwest; Alaska
Fisheries Center, National Marine Fisheries Service NWAFC Processed
Report. Available from
\url{https://www.afsc.noaa.gov/Publications/ProcRpt/PR1988-27.pdf}
{[}accessed 28 February 2017{]}.

\hypertarget{ref-punt_quantifying_2008}{}
Punt, A.E., Smith, D.C., KrusicGolub, K., and Robertson, S. 2008.
Quantifying age-reading error for use in fisheries stock assessments,
with application to species in Australia's southern and eastern
scalefish and shark fishery. Canadian Journal of Fisheries and Aquatic
Sciences \textbf{65}(9): 1991--2005. doi:
\href{https://doi.org/10.1139/F08-111}{10.1139/F08-111}.

\hypertarget{ref-ralston_documentation_2010}{}
Ralston, S., Pearson, D.E., Field, J.C., and Key, M. 2010. Documentation
of the California catch reconstruction project. US Department of
Commerce, National Oceanic; Atmospheric Adminstration, National Marine.

\hypertarget{ref-rogers_species_2003}{}
Rogers, J. 2003. Species allocation of \emph{Sebastes} and
\emph{Sebastolobus} species caught by foreign countries off Washington,
Oregon, and California, U.S.A. in 1965-1976. Unpublished document.

\hypertarget{ref-rogers_numerical_1992}{}
Rogers, J.B., and Pikitch, E.K. 1992. Numerical definition of groundfish
assemblages caught off the coasts of Oregon and Washington using
commercial fishing strategies. Canadian Journal of Fisheries and Aquatic
Sciences \textbf{49}(12): 2648--2656. Available from
\url{http://www.nrcresearchpress.com/doi/abs/10.1139/f92-293}
{[}accessed 9 March 2017{]}.

\hypertarget{ref-seeb_genetic_1988}{}
Seeb, L.W., and Gunderson, D.R. 1988. Genetic variation and population
structure of Pacific ocean perch (\emph{Sebastes alutus}). Canadian
Journal of Fisheries and Aquatic Sciences \textbf{45}(1): 78--88.
Available from
\url{http://www.nrcresearchpress.com/doi/abs/10.1139/f88-010}
{[}accessed 28 February 2017{]}.

\hypertarget{ref-stewart_bootstrapping_2014}{}
Stewart, I.J., and Hamel, O.S. 2014. Bootstrapping of sample sizes for
length- or age-composition data used in stock assessments. Canadian
Journal of Fisheries and Aquatic Sciences \textbf{71}(4): 581--588. doi:
\href{https://doi.org/10.1139/cjfas-2013-0289}{10.1139/cjfas-2013-0289}.

\hypertarget{ref-then_evaluating_2015}{}
Then, A.Y., Hoenig, J.M., Hall, N.G., and Hewitt, D.A. 2015. Evaluating
the predictive performance of empirical estimators of natural mortality
rate using information on over 200 fish species. ICES Journal of Marine
Science \textbf{72}(1): 82--92. doi:
\href{https://doi.org/10.1093/icesjms/fsu136}{10.1093/icesjms/fsu136}.

\hypertarget{ref-thorson_comparing_2017}{}
Thorson, J.T., and Barnett, L.A.K. 2017. Comparing estimates of
abundance trends and distribution shifts using single- and multispecies
models of fishes and biogenic habitat. ICES Journal of Marine Science:
Journal du Conseil: fsw193. doi:
\href{https://doi.org/10.1093/icesjms/fsw193}{10.1093/icesjms/fsw193}.

\hypertarget{ref-thorson_implementing_2016}{}
Thorson, J.T., and Kristensen, K. 2016. Implementing a generic method
for bias correction in statistical models using random effects, with
spatial and population dynamics examples. Fisheries Research
\textbf{175}: 66--74. doi:
\href{https://doi.org/10.1016/j.fishres.2015.11.016}{10.1016/j.fishres.2015.11.016}.

\hypertarget{ref-thorson_accounting_2014}{}
Thorson, J.T., and Ward, E.J. 2014. Accounting for vessel effects when
standardizing catch rates from cooperative surveys. Fisheries Research
\textbf{155}: 168--176. doi:
\href{https://doi.org/10.1016/j.fishres.2014.02.036}{10.1016/j.fishres.2014.02.036}.

\hypertarget{ref-thorson_geostatistical_2015}{}
Thorson, J.T., Shelton, A.O., Ward, E.J., and Skaug, H.J. 2015.
Geostatistical delta-generalized linear mixed models improve precision
for estimated abundance indices for West Coast groundfishes. ICES
Journal of Marine Science \textbf{72}(5): 1297--1310. doi:
\href{https://doi.org/10.1093/icesjms/fsu243}{10.1093/icesjms/fsu243}.

\hypertarget{ref-thorson_nwfscageingerror:_2012}{}
Thorson, J.T., Stewart, I.J., and Punt, A.E. 2012. nwfscAgeingError: A
user interface in R for the Punt et al. (2008) method for calculating
ageing error and imprecision. Available from:
http://github.com/nwfsc-assess/nwfscAgeingError/.

\hypertarget{ref-weinberg_estimation_2002}{}
Weinberg, J.R., Rago, P.J., Wakefield, W.W., and Keith, C. 2002.
Estimation of tow distance and spatial heterogeneity using data from
inclinometer sensors: An example using a clam survey dredge. Fisheries
Research \textbf{55}(1--3): 49--61. doi:
\href{https://doi.org/10.1016/S0165-7836(01)00292-2}{10.1016/S0165-7836(01)00292-2}.

\hypertarget{ref-wilkins_condition_1983}{}
Wilkins, M., and Golden, J. 1983. Condition of the Pacific ocean perch
resource off Washington and Oregon during 1979: Results of a cooperative
trawl survey. North American Journal of Fisheries Management \textbf{3}:
103--122.

\hypertarget{ref-withler_co-existing_2001}{}
Withler, R., Beacham, T., Schulze, A., Richards, L., and Miller, K.
2001. Co-existing populations of Pacific ocean perch, Sebastes alutus ,
in Queen Charlotte Sound, British Columbia. Marine Biology
\textbf{139}(1): 1--12. doi:
\href{https://doi.org/10.1007/s002270100560}{10.1007/s002270100560}.

\hypertarget{ref-zimmermann_influence_2003}{}
Zimmermann, M., Wilkins, M., Weinberg, K., Lauth, R., and Shaw, F. 2003.
Influence of improved performance monitoring on the consistency of a
bottom trawl survey. ICES Journal of Marine Science \textbf{60}(4):
818--826. doi:
\href{https://doi.org/10.1016/S1054-3139(03)00043-2}{10.1016/S1054-3139(03)00043-2}.

\end{document}
