\documentclass[pdf]{beamer}
\mode<presentation>
\usetheme[compress]{Singapore} %Berkeley, Palo Alto, Singapore, Warsaw
%\usetheme[compress]{Berlin} 
%\usetheme[compress]{Madrid} 
%\usecolortheme{seagull}  %Beaver, dolphin, dove, lily, orchid, seagull, seahorse

%\usefonttheme{serif}
% font themes: default, professionalfonts, serif, structurebold, structureitalicserif, structuresmallcapsserif

\usepackage{graphicx}
\usepackage{pgf}
\usepackage{array}
\usepackage{tabularx}
\usepackage{booktabs}          %% Used in risk tables
\usepackage{multirow}          %% Used in decision tables
\usepackage[T1]{fontenc}  %to use < or > in tables

%\graphicspath{C:/Users/Chantel.Wetzel/Documents/GitHub/POP_2017}
\newcolumntype{Y}{>{\centering\arraybackslash}X}
\newcommand{\specialcell}[2][c]{\begin{tabular}[#1]{@{}c@{}}#2\end{tabular}}
\newcommand{\subscr}[1]{$_{\text{#1}}$}
\newcommand{\Fforty}{F_{\text{SPR}=40\%}}       % Needs to be done as $\Fforty$
\newcommand{\Bforty}{B_{\text{SPR}=40\%}}

\setbeamersize{text margin left=0.1in}
\setbeamersize{text margin right=0.1in}

\definecolor{pageCol}{rgb}{0.5,0.5,1.0}

\usepackage{tikz}

\usebackgroundtemplate{
  \tikz[overlay,remember picture] 
  \node[opacity=0.3, at=(current page.south east),anchor=south east,inner sep=0pt] {
    \includegraphics[height=0.5in]{noaalogo.jpg}};
}

\setbeamertemplate{footline}
{
  \begin{beamercolorbox}[wd=.05\paperwidth,ht=0ex,dp=0ex,left]{framenumber in head/foot}%
    \insertframenumber/\inserttotalframenumber
    
  \end{beamercolorbox}%
}
\setbeamercolor{footline}{fg=pageCol}

\newcounter{saveenumi}

%  <<load_everything, echo = FALSE, message=FALSE, results='hide', warning=FALSE>>=
%      source("C:/Users/Chantel.Wetzel/Documents/GitHub/POP_2017/Presentation/0_Run_Model_Presentation.R")
%      create.plots = TRUE
%      Run.Model.Present(create.plots)
%  @

\newcommand{\mytableofcontents}{
  \begin{frame}[t]
  \frametitle{Outline}
  \tableofcontents[
    currentsection, sectionstyle=show/show, subsectionstyle=show/show/hide,
  ]
  \end{frame}
}
\AtBeginSection[]{\mytableofcontents}

%------------------------------------------------------------------------------------
% Title Page
%------------------------------------------------------------------------------------
\title{Pacific ocean perch 2017 Assessment}
\subtitle{Biology and Data}
\author{Chantel Wetzel$^{1}$\\
        Lee Cronin-Fine$^{2}$}
\institute[NWFSC]{
Northwest Fisheries Science Center$^1$ \\
University of Washington$^2$ \\
\medskip
}
\date{{\footnotesize STAR Panel \\ June 26-30, 2017}}


\begin{document}

\begin{frame}
  \titlepage
\end{frame}

%------------------------------------------------------------------------------------
\section{Biology}

%------------------------------------------------------------------------------------
\subsection{Overview}
\begin{frame}{Pacific ocean perch (\textit{Sebastes alutus})}
\begin{columns}
  \begin{column}{0.5\textwidth}
      \begin{itemize}
        \item Distributed from  Alaska Aleutian Islands to Northern California
        \item Typically 200 - 400 meters during summer months
        \item Semi-demersal and can be pelagic
        \item Both sexes move to deeper water with age
      \end{itemize}
  \end{column}
  
  \begin{column}{0.5\textwidth}
    \includegraphics[height = 1in]{C:/Users/Chantel.Wetzel/Documents/GitHub/POP_2017/Sebastes_alutus.png}
    %\includegraphics[height = 1in]{Sebastes_alutus.png}
    \begin{itemize}
        \item Female move to deeper waters post-spawning during winter months and return inshore in spring.
      \end{itemize}
  \end{column}
\end{columns}
\end{frame}


\subsection{Maturity}
\begin{frame}{Maturity}
\begin{columns}
  \begin{column}{0.5\textwidth}
      Functional maturity-at-length
      \begin{itemize}
        \item Categorized mature and immature fish based on the proportion of vitellogenin in the cytoplasm and atretic celss
        \item 50\% maturity is at larger lengths vs. biological maturity
        \item functional 50\% = 32.1 cm vs. biological 50\% = 30.1 cm
      \end{itemize}
  \end{column}
  
  \begin{column}{0.5\textwidth}
  \begin{center}
    \includegraphics[height = 2.75in, width = 2.5in]{figures/Functional_Maturity.png}
  \end{center}
  \end{column}
\end{columns}
\end{frame}

\begin{frame}{Maturity Comparison}
  \begin{center}
    %\includegraphics[height = 2.75in, width = 3.5in]{figures/Maturity_Comparison.png}
    \includegraphics[scale = 0.32]{figures/Maturity_Comparison.png}
  \end{center}
  *Sensitivity assumed maturity shown to not have a large impact on results
\end{frame}

\subsection{Fecundity}
\begin{frame}{Fecundity}
  \begin{center}
    \includegraphics[scale = 0.3, trim={0, 0, 1cm, 1cm}, clip]{figures/Fecundity_Comparison.png}
  \end{center}
  *Sensitivity to assumed fecundity shown to not have a large impact on results
\end{frame}

\subsection{Growth}
\begin{frame}{Weight-at-length}
  \begin{center}
    \includegraphics[scale = 0.75]{figures/weightAtLengthPred.png}
  \end{center}
\end{frame}

\begin{frame}{Length-at-age}
  \begin{center}
  \includegraphics[scale = 0.5]{figures/LengthAgeAll_2.png}
  \end{center}
\end{frame}


\begin{frame}{Observed Ages}
  \begin{center}
  \includegraphics[scale = 0.45]{figures/pop2017_agesbysource.png}
  \end{center}
\end{frame}

%-------------------------------------------------------------------------------------
%\section{Data Summary}
%-------------------------------------------------------------------------------------

\subsection{}
\begin{frame}{Data Summary Used in the 2017 Assessment}
  \begin{figure}[ht]
    \begin{center}
      \includegraphics[height=3in]{r4ss/data_plot.png}

    \end{center}
  \end{figure}
\end{frame}


%---------------------------------------------------------------------------------
\section{Removals}
%---------------------------------------------------------------------------------
\subsection{Landing histories}
\begin{frame}{Landings Data: 2017 vs. 2011}
  \begin{center}
    \includegraphics[scale = 0.45]{figures/pop2017_2011vs2017catches_states.png}
  \end{center}
\end{frame}

\begin{frame}{Cummalative catch difference}
  \begin{center}
    \includegraphics[scale = 0.32, trim={0, 0, 0, 2cm}, clip]{figures/Catch_Comparison.png}
  \end{center}
  *Resulted in $<$ 1\% change in $R0$ 
\end{frame}

\subsection{Discarding practices}
\begin{frame}{Discard Data}
  Discarding rates
\end{frame}

%---------------------------------------------------------------------------------
\section{Indices of Abundance}
%---------------------------------------------------------------------------------
\subsection{Fishery CPUE}
\begin{frame}{CPUE}
  CPUE
\end{frame}

\subsection{Survey Indices}
\begin{frame}{Survey}
  Survey
\end{frame}

%---------------------------------------------------------------------------------
\section{Length Compositions}
%---------------------------------------------------------------------------------
\subsection{Fishery Lengths}
\begin{frame}{Fishery}
  lengths
\end{frame}

\subsection{Survey Lengths}
\begin{frame}{Survey}
  length
\end{frame}

%---------------------------------------------------------------------------------
\section{Age Compositions}
%---------------------------------------------------------------------------------
\subsection{Fishery Ages}
\begin{frame}{Fishery}
  ages
\end{frame}

\subsection{Survey Ages}
\begin{frame}{Survey}
  ages
\end{frame}


%\section{Fishery Data}
%\subsection{}

%\section{Survey Data}
%\subsection

\end{document}